export const data = [
  {
    "region": "REGION",
    "council": "COUNCIL",
    "year": "YEAR",
    "enrolment_male": 29791,
    "enrolment_female": 31990,
    "enrolment_total": "ENROLMENT TOTAL",
    "dropout_male": 535,
    "dropout_female": 387,
    "dropout_total": "DROPOUT TOTAL"
  },
    {
      "region": "Arusha",
      "council": "Arusha",
      "year": 2016,
      "enrolment_male": 10433,
      "enrolment_female": 12673,
      "enrolment_total": 23106,
      "dropout_male": 314,
      "dropout_female": 269,
      "dropout_total": 583
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "year": 2016,
      "enrolment_male": 13723,
      "enrolment_female": 14249,
      "enrolment_total": 27972,
      "dropout_male": 137,
      "dropout_female": 131,
      "dropout_total": 268
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "year": 2016,
      "enrolment_male": 4821,
      "enrolment_female": 5619,
      "enrolment_total": 10440,
      "dropout_male": 148,
      "dropout_female": 185,
      "dropout_total": 333
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "year": 2016,
      "enrolment_male": 2868,
      "enrolment_female": 3007,
      "enrolment_total": 5875,
      "dropout_male": 62,
      "dropout_female": 72,
      "dropout_total": 134
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "year": 2016,
      "enrolment_male": 10141,
      "enrolment_female": 11460,
      "enrolment_total": 21601,
      "dropout_male": 223,
      "dropout_female": 143,
      "dropout_total": 366
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "year": 2016,
      "enrolment_male": 4278,
      "enrolment_female": 4309,
      "enrolment_total": 8587,
      "dropout_male": 128,
      "dropout_female": 77,
      "dropout_total": 205
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "year": 2016,
      "enrolment_male": 2848,
      "enrolment_female": 2603,
      "enrolment_total": 5451,
      "dropout_male": 250,
      "dropout_female": 152,
      "dropout_total": 402
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ilala MC",
      "year": 2016,
      "enrolment_male": 29295,
      "enrolment_female": 30309,
      "enrolment_total": 59604,
      "dropout_male": 205,
      "dropout_female": 160,
      "dropout_total": 365
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kigamboni MC",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 92,
      "dropout_female": 64,
      "dropout_total": 156
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kinondoni MC",
      "year": 2016,
      "enrolment_male": 32634,
      "enrolment_female": 34505,
      "enrolment_total": 67139,
      "dropout_male": 160,
      "dropout_female": 129,
      "dropout_total": 289
    },
    {
      "region": "Dar-es-salaam",
      "council": "Temeke MC",
      "year": 2016,
      "enrolment_male": 28005,
      "enrolment_female": 29443,
      "enrolment_total": 57448,
      "dropout_male": 207,
      "dropout_female": 203,
      "dropout_total": 410
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ubungo MC",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 193,
      "dropout_female": 140,
      "dropout_total": 333
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "year": 2016,
      "enrolment_male": 1874,
      "enrolment_female": 1718,
      "enrolment_total": 3592,
      "dropout_male": 194,
      "dropout_female": 173,
      "dropout_total": 367
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "year": 2016,
      "enrolment_male": 3501,
      "enrolment_female": 3497,
      "enrolment_total": 6998,
      "dropout_male": 146,
      "dropout_female": 197,
      "dropout_total": 343
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "year": 2016,
      "enrolment_male": 1834,
      "enrolment_female": 2660,
      "enrolment_total": 4494,
      "dropout_male": 42,
      "dropout_female": 76,
      "dropout_total": 118
    },
    {
      "region": "Dodoma",
      "council": "Dodoma MC",
      "year": 2016,
      "enrolment_male": 10836,
      "enrolment_female": 11604,
      "enrolment_total": 22440,
      "dropout_male": 195,
      "dropout_female": 186,
      "dropout_total": 381
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "year": 2016,
      "enrolment_male": 2123,
      "enrolment_female": 2814,
      "enrolment_total": 4937,
      "dropout_male": 99,
      "dropout_female": 124,
      "dropout_total": 223
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "year": 2016,
      "enrolment_male": 1872,
      "enrolment_female": 2476,
      "enrolment_total": 4348,
      "dropout_male": 40,
      "dropout_female": 30,
      "dropout_total": 70
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "year": 2016,
      "enrolment_male": 3933,
      "enrolment_female": 4598,
      "enrolment_total": 8531,
      "dropout_male": 165,
      "dropout_female": 239,
      "dropout_total": 404
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "year": 2016,
      "enrolment_male": 3856,
      "enrolment_female": 3713,
      "enrolment_total": 7569,
      "dropout_male": 160,
      "dropout_female": 193,
      "dropout_total": 353
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "year": 2016,
      "enrolment_male": 4532,
      "enrolment_female": 3272,
      "enrolment_total": 7804,
      "dropout_male": 247,
      "dropout_female": 229,
      "dropout_total": 476
    },
    {
      "region": "Geita",
      "council": "Chato",
      "year": 2016,
      "enrolment_male": 6599,
      "enrolment_female": 4682,
      "enrolment_total": 11281,
      "dropout_male": 319,
      "dropout_female": 224,
      "dropout_total": 543
    },
    {
      "region": "Geita",
      "council": "Geita",
      "year": 2016,
      "enrolment_male": 10107,
      "enrolment_female": 7241,
      "enrolment_total": 17348,
      "dropout_male": 936,
      "dropout_female": 641,
      "dropout_total": 1577
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "year": 2016,
      "enrolment_male": 5742,
      "enrolment_female": 4908,
      "enrolment_total": 10650,
      "dropout_male": 177,
      "dropout_female": 89,
      "dropout_total": 266
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "year": 2016,
      "enrolment_male": 3423,
      "enrolment_female": 2686,
      "enrolment_total": 6109,
      "dropout_male": 756,
      "dropout_female": 639,
      "dropout_total": 1395
    },
    {
      "region": "Geita",
      "council": "Nyang'hwale",
      "year": 2016,
      "enrolment_male": 2363,
      "enrolment_female": 2001,
      "enrolment_total": 4364,
      "dropout_male": 129,
      "dropout_female": 95,
      "dropout_total": 224
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "year": 2016,
      "enrolment_male": 8475,
      "enrolment_female": 8528,
      "enrolment_total": 17003,
      "dropout_male": 279,
      "dropout_female": 181,
      "dropout_total": 460
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "year": 2016,
      "enrolment_male": 5343,
      "enrolment_female": 7481,
      "enrolment_total": 12824,
      "dropout_male": 100,
      "dropout_female": 118,
      "dropout_total": 218
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "year": 2016,
      "enrolment_male": 5521,
      "enrolment_female": 6445,
      "enrolment_total": 11966,
      "dropout_male": 131,
      "dropout_female": 138,
      "dropout_total": 269
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "year": 2016,
      "enrolment_male": 3894,
      "enrolment_female": 3178,
      "enrolment_total": 7072,
      "dropout_male": 33,
      "dropout_female": 46,
      "dropout_total": 79
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "year": 2016,
      "enrolment_male": 6606,
      "enrolment_female": 7502,
      "enrolment_total": 14108,
      "dropout_male": 295,
      "dropout_female": 300,
      "dropout_total": 595
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "year": 2016,
      "enrolment_male": 4865,
      "enrolment_female": 4063,
      "enrolment_total": 8928,
      "dropout_male": 458,
      "dropout_female": 495,
      "dropout_total": 953
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "year": 2016,
      "enrolment_male": 5917,
      "enrolment_female": 5807,
      "enrolment_total": 11724,
      "dropout_male": 132,
      "dropout_female": 129,
      "dropout_total": 261
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "year": 2016,
      "enrolment_male": 5239,
      "enrolment_female": 5096,
      "enrolment_total": 10335,
      "dropout_male": 45,
      "dropout_female": 45,
      "dropout_total": 90
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "year": 2016,
      "enrolment_male": 4762,
      "enrolment_female": 5550,
      "enrolment_total": 10312,
      "dropout_male": 174,
      "dropout_female": 180,
      "dropout_total": 354
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "year": 2016,
      "enrolment_male": 3691,
      "enrolment_female": 3893,
      "enrolment_total": 7584,
      "dropout_male": 227,
      "dropout_female": 231,
      "dropout_total": 458
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "year": 2016,
      "enrolment_male": 4106,
      "enrolment_female": 4282,
      "enrolment_total": 8388,
      "dropout_male": 142,
      "dropout_female": 123,
      "dropout_total": 265
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "year": 2016,
      "enrolment_male": 9931,
      "enrolment_female": 9430,
      "enrolment_total": 19361,
      "dropout_male": 465,
      "dropout_female": 473,
      "dropout_total": 938
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "year": 2016,
      "enrolment_male": 4639,
      "enrolment_female": 4980,
      "enrolment_total": 9619,
      "dropout_male": 261,
      "dropout_female": 244,
      "dropout_total": 505
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "year": 2016,
      "enrolment_male": 446,
      "enrolment_female": 298,
      "enrolment_total": 744,
      "dropout_male": 38,
      "dropout_female": 30,
      "dropout_total": 68
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "year": 2016,
      "enrolment_male": 1866,
      "enrolment_female": 1390,
      "enrolment_total": 3256,
      "dropout_male": 222,
      "dropout_female": 183,
      "dropout_total": 405
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "year": 2016,
      "enrolment_male": 2603,
      "enrolment_female": 3222,
      "enrolment_total": 5825,
      "dropout_male": 68,
      "dropout_female": 75,
      "dropout_total": 143
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "year": 2016,
      "enrolment_male": 978,
      "enrolment_female": 630,
      "enrolment_total": 1608,
      "dropout_male": 23,
      "dropout_female": 24,
      "dropout_total": 47
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "year": 2016,
      "enrolment_male": 1989,
      "enrolment_female": 1452,
      "enrolment_total": 3441,
      "dropout_male": 100,
      "dropout_female": 93,
      "dropout_total": 193
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "year": 2016,
      "enrolment_male": 3993,
      "enrolment_female": 2565,
      "enrolment_total": 6558,
      "dropout_male": 166,
      "dropout_female": 93,
      "dropout_total": 259
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "year": 2016,
      "enrolment_male": 2291,
      "enrolment_female": 1580,
      "enrolment_total": 3871,
      "dropout_male": 119,
      "dropout_female": 66,
      "dropout_total": 185
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "year": 2016,
      "enrolment_male": 2891,
      "enrolment_female": 1754,
      "enrolment_total": 4645,
      "dropout_male": 77,
      "dropout_female": 53,
      "dropout_total": 130
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "year": 2016,
      "enrolment_male": 4635,
      "enrolment_female": 3598,
      "enrolment_total": 8233,
      "dropout_male": 29,
      "dropout_female": 44,
      "dropout_total": 73
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "year": 2016,
      "enrolment_male": 3786,
      "enrolment_female": 4527,
      "enrolment_total": 8313,
      "dropout_male": 216,
      "dropout_female": 172,
      "dropout_total": 388
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "year": 2016,
      "enrolment_male": 4589,
      "enrolment_female": 2444,
      "enrolment_total": 7033,
      "dropout_male": 73,
      "dropout_female": 39,
      "dropout_total": 112
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "year": 2016,
      "enrolment_male": 6385,
      "enrolment_female": 4495,
      "enrolment_total": 10880,
      "dropout_male": 171,
      "dropout_female": 116,
      "dropout_total": 287
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "year": 2016,
      "enrolment_male": 3510,
      "enrolment_female": 1830,
      "enrolment_total": 5340,
      "dropout_male": 201,
      "dropout_female": 115,
      "dropout_total": 316
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "year": 2016,
      "enrolment_male": 6960,
      "enrolment_female": 8173,
      "enrolment_total": 15133,
      "dropout_male": 128,
      "dropout_female": 152,
      "dropout_total": 280
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "year": 2016,
      "enrolment_male": 17178,
      "enrolment_female": 20669,
      "enrolment_total": 37847,
      "dropout_male": 255,
      "dropout_female": 270,
      "dropout_total": 525
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "year": 2016,
      "enrolment_male": 9549,
      "enrolment_female": 8276,
      "enrolment_total": 17825,
      "dropout_male": 77,
      "dropout_female": 61,
      "dropout_total": 138
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "year": 2016,
      "enrolment_male": 7614,
      "enrolment_female": 8526,
      "enrolment_total": 16140,
      "dropout_male": 108,
      "dropout_female": 108,
      "dropout_total": 216
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "year": 2016,
      "enrolment_male": 8318,
      "enrolment_female": 11479,
      "enrolment_total": 19797,
      "dropout_male": 265,
      "dropout_female": 249,
      "dropout_total": 514
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "year": 2016,
      "enrolment_male": 9847,
      "enrolment_female": 11718,
      "enrolment_total": 21565,
      "dropout_male": 336,
      "dropout_female": 269,
      "dropout_total": 605
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "year": 2016,
      "enrolment_male": 2786,
      "enrolment_female": 4011,
      "enrolment_total": 6797,
      "dropout_male": 70,
      "dropout_female": 50,
      "dropout_total": 120
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "year": 2016,
      "enrolment_male": 2566,
      "enrolment_female": 2947,
      "enrolment_total": 5513,
      "dropout_male": 187,
      "dropout_female": 139,
      "dropout_total": 326
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "year": 2016,
      "enrolment_male": 3104,
      "enrolment_female": 2196,
      "enrolment_total": 5300,
      "dropout_male": 110,
      "dropout_female": 82,
      "dropout_total": 192
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "year": 2016,
      "enrolment_male": 1934,
      "enrolment_female": 1611,
      "enrolment_total": 3545,
      "dropout_male": 46,
      "dropout_female": 42,
      "dropout_total": 88
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "year": 2016,
      "enrolment_male": 2226,
      "enrolment_female": 2024,
      "enrolment_total": 4250,
      "dropout_male": 134,
      "dropout_female": 103,
      "dropout_total": 237
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "year": 2016,
      "enrolment_male": 2738,
      "enrolment_female": 2782,
      "enrolment_total": 5520,
      "dropout_male": 140,
      "dropout_female": 94,
      "dropout_total": 234
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "year": 2016,
      "enrolment_male": 1721,
      "enrolment_female": 1544,
      "enrolment_total": 3265,
      "dropout_male": 62,
      "dropout_female": 49,
      "dropout_total": 111
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "year": 2016,
      "enrolment_male": 5183,
      "enrolment_female": 6994,
      "enrolment_total": 12177,
      "dropout_male": 220,
      "dropout_female": 168,
      "dropout_total": 388
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "year": 2016,
      "enrolment_male": 3253,
      "enrolment_female": 3896,
      "enrolment_total": 7149,
      "dropout_male": 37,
      "dropout_female": 33,
      "dropout_total": 70
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "year": 2016,
      "enrolment_male": 3217,
      "enrolment_female": 4532,
      "enrolment_total": 7749,
      "dropout_male": 190,
      "dropout_female": 174,
      "dropout_total": 364
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "year": 2016,
      "enrolment_male": 2066,
      "enrolment_female": 2476,
      "enrolment_total": 4542,
      "dropout_male": 47,
      "dropout_female": 144,
      "dropout_total": 191
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "year": 2016,
      "enrolment_male": 2237,
      "enrolment_female": 3598,
      "enrolment_total": 5835,
      "dropout_male": 196,
      "dropout_female": 262,
      "dropout_total": 458
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "year": 2016,
      "enrolment_male": 3046,
      "enrolment_female": 3485,
      "enrolment_total": 6531,
      "dropout_male": 163,
      "dropout_female": 150,
      "dropout_total": 313
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "year": 2016,
      "enrolment_male": 2223,
      "enrolment_female": 2130,
      "enrolment_total": 4353,
      "dropout_male": 86,
      "dropout_female": 53,
      "dropout_total": 139
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "year": 2016,
      "enrolment_male": 4977,
      "enrolment_female": 3238,
      "enrolment_total": 8215,
      "dropout_male": 208,
      "dropout_female": 169,
      "dropout_total": 377
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "year": 2016,
      "enrolment_male": 3656,
      "enrolment_female": 3118,
      "enrolment_total": 6774,
      "dropout_male": 140,
      "dropout_female": 122,
      "dropout_total": 262
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "year": 2016,
      "enrolment_male": 4750,
      "enrolment_female": 4179,
      "enrolment_total": 8929,
      "dropout_male": 187,
      "dropout_female": 119,
      "dropout_total": 306
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "year": 2016,
      "enrolment_male": 4377,
      "enrolment_female": 2667,
      "enrolment_total": 7044,
      "dropout_male": 238,
      "dropout_female": 159,
      "dropout_total": 397
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "year": 2016,
      "enrolment_male": 7101,
      "enrolment_female": 4810,
      "enrolment_total": 11911,
      "dropout_male": 128,
      "dropout_female": 76,
      "dropout_total": 204
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "year": 2016,
      "enrolment_male": 5882,
      "enrolment_female": 4239,
      "enrolment_total": 10121,
      "dropout_male": 177,
      "dropout_female": 170,
      "dropout_total": 347
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "year": 2016,
      "enrolment_male": 5121,
      "enrolment_female": 4231,
      "enrolment_total": 9352,
      "dropout_male": 212,
      "dropout_female": 161,
      "dropout_total": 373
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "year": 2016,
      "enrolment_male": 5214,
      "enrolment_female": 3405,
      "enrolment_total": 8619,
      "dropout_male": 209,
      "dropout_female": 167,
      "dropout_total": 376
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "year": 2016,
      "enrolment_male": 3157,
      "enrolment_female": 2169,
      "enrolment_total": 5326,
      "dropout_male": 64,
      "dropout_female": 44,
      "dropout_total": 108
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "year": 2016,
      "enrolment_male": 4216,
      "enrolment_female": 3462,
      "enrolment_total": 7678,
      "dropout_male": 118,
      "dropout_female": 124,
      "dropout_total": 242
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "year": 2016,
      "enrolment_male": 3519,
      "enrolment_female": 3027,
      "enrolment_total": 6546,
      "dropout_male": 97,
      "dropout_female": 101,
      "dropout_total": 198
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "year": 2016,
      "enrolment_male": 7116,
      "enrolment_female": 5929,
      "enrolment_total": 13045,
      "dropout_male": 184,
      "dropout_female": 202,
      "dropout_total": 386
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "year": 2016,
      "enrolment_male": 4799,
      "enrolment_female": 5146,
      "enrolment_total": 9945,
      "dropout_male": 135,
      "dropout_female": 165,
      "dropout_total": 300
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "year": 2016,
      "enrolment_male": 8339,
      "enrolment_female": 9747,
      "enrolment_total": 18086,
      "dropout_male": 130,
      "dropout_female": 179,
      "dropout_total": 309
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "year": 2016,
      "enrolment_male": 18080,
      "enrolment_female": 17338,
      "enrolment_total": 35418,
      "dropout_male": 189,
      "dropout_female": 256,
      "dropout_total": 445
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "year": 2016,
      "enrolment_male": 9358,
      "enrolment_female": 8725,
      "enrolment_total": 18083,
      "dropout_male": 238,
      "dropout_female": 232,
      "dropout_total": 470
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "year": 2016,
      "enrolment_male": 1435,
      "enrolment_female": 1979,
      "enrolment_total": 3414,
      "dropout_male": 92,
      "dropout_female": 135,
      "dropout_total": 227
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "year": 2016,
      "enrolment_male": 2759,
      "enrolment_female": 3776,
      "enrolment_total": 6535,
      "dropout_male": 120,
      "dropout_female": 117,
      "dropout_total": 237
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "year": 2016,
      "enrolment_male": 5527,
      "enrolment_female": 5647,
      "enrolment_total": 11174,
      "dropout_male": 98,
      "dropout_female": 98,
      "dropout_total": 196
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "year": 2016,
      "enrolment_male": 7237,
      "enrolment_female": 6839,
      "enrolment_total": 14076,
      "dropout_male": 178,
      "dropout_female": 203,
      "dropout_total": 381
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "year": 2016,
      "enrolment_male": 2137,
      "enrolment_female": 2003,
      "enrolment_total": 4140,
      "dropout_male": 44,
      "dropout_female": 33,
      "dropout_total": 77
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "year": 2016,
      "enrolment_male": 3698,
      "enrolment_female": 3813,
      "enrolment_total": 7511,
      "dropout_male": 149,
      "dropout_female": 123,
      "dropout_total": 272
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "year": 2016,
      "enrolment_male": 10819,
      "enrolment_female": 12594,
      "enrolment_total": 23413,
      "dropout_male": 146,
      "dropout_female": 132,
      "dropout_total": 278
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "year": 2016,
      "enrolment_male": 4800,
      "enrolment_female": 5449,
      "enrolment_total": 10249,
      "dropout_male": 173,
      "dropout_female": 222,
      "dropout_total": 395
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "year": 2016,
      "enrolment_male": 3591,
      "enrolment_female": 2653,
      "enrolment_total": 6244,
      "dropout_male": 75,
      "dropout_female": 66,
      "dropout_total": 141
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "year": 2016,
      "enrolment_male": 4637,
      "enrolment_female": 3464,
      "enrolment_total": 8101,
      "dropout_male": 221,
      "dropout_female": 192,
      "dropout_total": 413
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "year": 2016,
      "enrolment_male": 1530,
      "enrolment_female": 2219,
      "enrolment_total": 3749,
      "dropout_male": 164,
      "dropout_female": 143,
      "dropout_total": 307
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "year": 2016,
      "enrolment_male": 1827,
      "enrolment_female": 2071,
      "enrolment_total": 3898,
      "dropout_male": 156,
      "dropout_female": 144,
      "dropout_total": 300
    },
    {
      "region": "Mtwara",
      "council": "Mtwara Mikindani MC",
      "year": 2016,
      "enrolment_male": 4030,
      "enrolment_female": 4663,
      "enrolment_total": 8693,
      "dropout_male": 86,
      "dropout_female": 58,
      "dropout_total": 144
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "year": 2016,
      "enrolment_male": 1865,
      "enrolment_female": 1913,
      "enrolment_total": 3778,
      "dropout_male": 158,
      "dropout_female": 190,
      "dropout_total": 348
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "year": 2016,
      "enrolment_male": 1479,
      "enrolment_female": 1559,
      "enrolment_total": 3038,
      "dropout_male": 183,
      "dropout_female": 191,
      "dropout_total": 374
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "year": 2016,
      "enrolment_male": 1628,
      "enrolment_female": 1719,
      "enrolment_total": 3347,
      "dropout_male": 33,
      "dropout_female": 33,
      "dropout_total": 66
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "year": 2016,
      "enrolment_male": 1559,
      "enrolment_female": 2023,
      "enrolment_total": 3582,
      "dropout_male": 64,
      "dropout_female": 38,
      "dropout_total": 102
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "year": 2016,
      "enrolment_male": 3503,
      "enrolment_female": 3947,
      "enrolment_total": 7450,
      "dropout_male": 351,
      "dropout_female": 300,
      "dropout_total": 651
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "year": 2016,
      "enrolment_male": 5720,
      "enrolment_female": 3894,
      "enrolment_total": 9614,
      "dropout_male": 502,
      "dropout_female": 440,
      "dropout_total": 942
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "year": 2016,
      "enrolment_male": 12206,
      "enrolment_female": 12462,
      "enrolment_total": 24668,
      "dropout_male": 190,
      "dropout_female": 174,
      "dropout_total": 364
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "year": 2016,
      "enrolment_male": 6479,
      "enrolment_female": 6735,
      "enrolment_total": 13214,
      "dropout_male": 558,
      "dropout_female": 488,
      "dropout_total": 1046
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "year": 2016,
      "enrolment_male": 6991,
      "enrolment_female": 6086,
      "enrolment_total": 13077,
      "dropout_male": 390,
      "dropout_female": 332,
      "dropout_total": 722
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "year": 2016,
      "enrolment_male": 5184,
      "enrolment_female": 5435,
      "enrolment_total": 10619,
      "dropout_male": 476,
      "dropout_female": 508,
      "dropout_total": 984
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "year": 2016,
      "enrolment_male": 16423,
      "enrolment_female": 15908,
      "enrolment_total": 32331,
      "dropout_male": 243,
      "dropout_female": 247,
      "dropout_total": 490
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "year": 2016,
      "enrolment_male": 9245,
      "enrolment_female": 6630,
      "enrolment_total": 15875,
      "dropout_male": 356,
      "dropout_female": 278,
      "dropout_total": 634
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "year": 2016,
      "enrolment_male": 8822,
      "enrolment_female": 6859,
      "enrolment_total": 15681,
      "dropout_male": 390,
      "dropout_female": 367,
      "dropout_total": 757
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "year": 2016,
      "enrolment_male": 2895,
      "enrolment_female": 3012,
      "enrolment_total": 5907,
      "dropout_male": 100,
      "dropout_female": 84,
      "dropout_total": 184
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "year": 2016,
      "enrolment_male": 2329,
      "enrolment_female": 3737,
      "enrolment_total": 6066,
      "dropout_male": 79,
      "dropout_female": 63,
      "dropout_total": 142
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "year": 2016,
      "enrolment_male": 2739,
      "enrolment_female": 2650,
      "enrolment_total": 5389,
      "dropout_male": 171,
      "dropout_female": 109,
      "dropout_total": 280
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "year": 2016,
      "enrolment_male": 1439,
      "enrolment_female": 2681,
      "enrolment_total": 4120,
      "dropout_male": 135,
      "dropout_female": 115,
      "dropout_total": 250
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "year": 2016,
      "enrolment_male": 4944,
      "enrolment_female": 4933,
      "enrolment_total": 9877,
      "dropout_male": 202,
      "dropout_female": 155,
      "dropout_total": 357
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "year": 2016,
      "enrolment_male": 3769,
      "enrolment_female": 5303,
      "enrolment_total": 9072,
      "dropout_male": 280,
      "dropout_female": 233,
      "dropout_total": 513
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "year": 2016,
      "enrolment_male": 5114,
      "enrolment_female": 5393,
      "enrolment_total": 10507,
      "dropout_male": 48,
      "dropout_female": 36,
      "dropout_total": 84
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "year": 2016,
      "enrolment_male": 4657,
      "enrolment_female": 5282,
      "enrolment_total": 9939,
      "dropout_male": 138,
      "dropout_female": 178,
      "dropout_total": 316
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "year": 2016,
      "enrolment_male": 2219,
      "enrolment_female": 3417,
      "enrolment_total": 5636,
      "dropout_male": 116,
      "dropout_female": 120,
      "dropout_total": 236
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "year": 2016,
      "enrolment_male": 4809,
      "enrolment_female": 5453,
      "enrolment_total": 10262,
      "dropout_male": 89,
      "dropout_female": 99,
      "dropout_total": 188
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 29,
      "dropout_female": 25,
      "dropout_total": 54
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "year": 2016,
      "enrolment_male": 3547,
      "enrolment_female": 2364,
      "enrolment_total": 5911,
      "dropout_male": 136,
      "dropout_female": 84,
      "dropout_total": 220
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "year": 2016,
      "enrolment_male": 754,
      "enrolment_female": 1001,
      "enrolment_total": 1755,
      "dropout_male": 8,
      "dropout_female": 15,
      "dropout_total": 23
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "year": 2016,
      "enrolment_male": 6686,
      "enrolment_female": 5914,
      "enrolment_total": 12600,
      "dropout_male": 220,
      "dropout_female": 231,
      "dropout_total": 451
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "year": 2016,
      "enrolment_male": 4050,
      "enrolment_female": 3709,
      "enrolment_total": 7759,
      "dropout_male": 85,
      "dropout_female": 58,
      "dropout_total": 143
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "year": 2016,
      "enrolment_male": 3053,
      "enrolment_female": 1772,
      "enrolment_total": 4825,
      "dropout_male": 278,
      "dropout_female": 203,
      "dropout_total": 481
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "year": 2016,
      "enrolment_male": 3703,
      "enrolment_female": 2848,
      "enrolment_total": 6551,
      "dropout_male": 234,
      "dropout_female": 212,
      "dropout_total": 446
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "year": 2016,
      "enrolment_male": 3250,
      "enrolment_female": 2225,
      "enrolment_total": 5475,
      "dropout_male": 104,
      "dropout_female": 72,
      "dropout_total": 176
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "year": 2016,
      "enrolment_male": 6941,
      "enrolment_female": 6184,
      "enrolment_total": 13125,
      "dropout_male": 103,
      "dropout_female": 118,
      "dropout_total": 221
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "year": 2016,
      "enrolment_male": 1470,
      "enrolment_female": 1194,
      "enrolment_total": 2664,
      "dropout_male": 38,
      "dropout_female": 60,
      "dropout_total": 98
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "year": 2016,
      "enrolment_male": 5288,
      "enrolment_female": 5937,
      "enrolment_total": 11225,
      "dropout_male": 294,
      "dropout_female": 253,
      "dropout_total": 547
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "year": 2016,
      "enrolment_male": 2518,
      "enrolment_female": 2617,
      "enrolment_total": 5135,
      "dropout_male": 77,
      "dropout_female": 65,
      "dropout_total": 142
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "year": 2016,
      "enrolment_male": 3963,
      "enrolment_female": 3475,
      "enrolment_total": 7438,
      "dropout_male": 261,
      "dropout_female": 239,
      "dropout_total": 500
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "year": 2016,
      "enrolment_male": 2245,
      "enrolment_female": 2148,
      "enrolment_total": 4393,
      "dropout_male": 131,
      "dropout_female": 156,
      "dropout_total": 287
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "year": 2016,
      "enrolment_male": 1975,
      "enrolment_female": 2961,
      "enrolment_total": 4936,
      "dropout_male": 69,
      "dropout_female": 86,
      "dropout_total": 155
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "year": 2016,
      "enrolment_male": 6748,
      "enrolment_female": 7138,
      "enrolment_total": 13886,
      "dropout_male": 33,
      "dropout_female": 37,
      "dropout_total": 70
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "year": 2016,
      "enrolment_male": 4810,
      "enrolment_female": 3329,
      "enrolment_total": 8139,
      "dropout_male": 263,
      "dropout_female": 235,
      "dropout_total": 498
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "year": 2016,
      "enrolment_male": 5868,
      "enrolment_female": 5898,
      "enrolment_total": 11766,
      "dropout_male": 157,
      "dropout_female": 147,
      "dropout_total": 304
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "year": 2016,
      "enrolment_male": 5084,
      "enrolment_female": 3779,
      "enrolment_total": 8863,
      "dropout_male": 161,
      "dropout_female": 167,
      "dropout_total": 328
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "year": 2016,
      "enrolment_male": 3841,
      "enrolment_female": 3429,
      "enrolment_total": 7270,
      "dropout_male": 600,
      "dropout_female": 491,
      "dropout_total": 1091
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "year": 2016,
      "enrolment_male": 4407,
      "enrolment_female": 3871,
      "enrolment_total": 8278,
      "dropout_male": 249,
      "dropout_female": 234,
      "dropout_total": 483
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "year": 2016,
      "enrolment_male": 4428,
      "enrolment_female": 4189,
      "enrolment_total": 8617,
      "dropout_male": 59,
      "dropout_female": 71,
      "dropout_total": 130
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "year": 2016,
      "enrolment_male": 2774,
      "enrolment_female": 2214,
      "enrolment_total": 4988,
      "dropout_male": 211,
      "dropout_female": 161,
      "dropout_total": 372
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "year": 2016,
      "enrolment_male": 3440,
      "enrolment_female": 2512,
      "enrolment_total": 5952,
      "dropout_male": 180,
      "dropout_female": 131,
      "dropout_total": 311
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "year": 2016,
      "enrolment_male": 3573,
      "enrolment_female": 2884,
      "enrolment_total": 6457,
      "dropout_male": 178,
      "dropout_female": 126,
      "dropout_total": 304
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "year": 2016,
      "enrolment_male": 5477,
      "enrolment_female": 4244,
      "enrolment_total": 9721,
      "dropout_male": 156,
      "dropout_female": 118,
      "dropout_total": 274
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "year": 2016,
      "enrolment_male": 3890,
      "enrolment_female": 2649,
      "enrolment_total": 6539,
      "dropout_male": 322,
      "dropout_female": 185,
      "dropout_total": 507
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "year": 2016,
      "enrolment_male": 5404,
      "enrolment_female": 4543,
      "enrolment_total": 9947,
      "dropout_male": 252,
      "dropout_female": 240,
      "dropout_total": 492
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "year": 2016,
      "enrolment_male": 2922,
      "enrolment_female": 2358,
      "enrolment_total": 5280,
      "dropout_male": 141,
      "dropout_female": 171,
      "dropout_total": 312
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "year": 2016,
      "enrolment_male": 3734,
      "enrolment_female": 4630,
      "enrolment_total": 8364,
      "dropout_male": 194,
      "dropout_female": 162,
      "dropout_total": 356
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "year": 2016,
      "enrolment_male": 3183,
      "enrolment_female": 3428,
      "enrolment_total": 6611,
      "dropout_male": 141,
      "dropout_female": 111,
      "dropout_total": 252
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "year": 2016,
      "enrolment_male": 1460,
      "enrolment_female": 1256,
      "enrolment_total": 2716,
      "dropout_male": 22,
      "dropout_female": 25,
      "dropout_total": 47
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "year": 2016,
      "enrolment_male": 2175,
      "enrolment_female": 2249,
      "enrolment_total": 4424,
      "dropout_male": 61,
      "dropout_female": 86,
      "dropout_total": 147
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "year": 2016,
      "enrolment_male": 2032,
      "enrolment_female": 2364,
      "enrolment_total": 4396,
      "dropout_male": 86,
      "dropout_female": 78,
      "dropout_total": 164
    },
    {
      "region": "Singida",
      "council": "Singida",
      "year": 2016,
      "enrolment_male": 3670,
      "enrolment_female": 4510,
      "enrolment_total": 8180,
      "dropout_male": 260,
      "dropout_female": 272,
      "dropout_total": 532
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "year": 2016,
      "enrolment_male": 4305,
      "enrolment_female": 3751,
      "enrolment_total": 8056,
      "dropout_male": 94,
      "dropout_female": 104,
      "dropout_total": 198
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "year": 2016,
      "enrolment_male": 2464,
      "enrolment_female": 2983,
      "enrolment_total": 5447,
      "dropout_male": 63,
      "dropout_female": 96,
      "dropout_total": 159
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "year": 2016,
      "enrolment_male": 10026,
      "enrolment_female": 12294,
      "enrolment_total": 22320,
      "dropout_male": 358,
      "dropout_female": 399,
      "dropout_total": 757
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "year": 2016,
      "enrolment_male": 1301,
      "enrolment_female": 747,
      "enrolment_total": 2048,
      "dropout_male": 117,
      "dropout_female": 45,
      "dropout_total": 162
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 124,
      "dropout_female": 118,
      "dropout_total": 242
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "year": 2016,
      "enrolment_male": 2081,
      "enrolment_female": 1845,
      "enrolment_total": 3926,
      "dropout_male": 90,
      "dropout_female": 47,
      "dropout_total": 137
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "year": 2016,
      "enrolment_male": 5092,
      "enrolment_female": 4884,
      "enrolment_total": 9976,
      "dropout_male": 362,
      "dropout_female": 273,
      "dropout_total": 635
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "year": 2016,
      "enrolment_male": 3798,
      "enrolment_female": 2257,
      "enrolment_total": 6055,
      "dropout_male": 434,
      "dropout_female": 201,
      "dropout_total": 635
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "year": 2016,
      "enrolment_male": 2951,
      "enrolment_female": 2493,
      "enrolment_total": 5444,
      "dropout_male": 333,
      "dropout_female": 288,
      "dropout_total": 621
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "year": 2016,
      "enrolment_male": 1288,
      "enrolment_female": 1696,
      "enrolment_total": 2984,
      "dropout_male": 40,
      "dropout_female": 32,
      "dropout_total": 72
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "year": 2016,
      "enrolment_male": 3405,
      "enrolment_female": 3276,
      "enrolment_total": 6681,
      "dropout_male": 497,
      "dropout_female": 486,
      "dropout_total": 983
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "year": 2016,
      "enrolment_male": 8046,
      "enrolment_female": 6490,
      "enrolment_total": 14536,
      "dropout_male": 163,
      "dropout_female": 128,
      "dropout_total": 291
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "year": 2016,
      "enrolment_male": 3565,
      "enrolment_female": 3322,
      "enrolment_total": 6887,
      "dropout_male": 735,
      "dropout_female": 649,
      "dropout_total": 1384
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "year": 2016,
      "enrolment_male": 2812,
      "enrolment_female": 2495,
      "enrolment_total": 5307,
      "dropout_male": 132,
      "dropout_female": 107,
      "dropout_total": 239
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "year": 2016,
      "enrolment_male": 3570,
      "enrolment_female": 4181,
      "enrolment_total": 7751,
      "dropout_male": 145,
      "dropout_female": 135,
      "dropout_total": 280
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "year": 2016,
      "enrolment_male": 3433,
      "enrolment_female": 3947,
      "enrolment_total": 7380,
      "dropout_male": 267,
      "dropout_female": 259,
      "dropout_total": 526
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "year": 2016,
      "enrolment_male": 1799,
      "enrolment_female": 2258,
      "enrolment_total": 4057,
      "dropout_male": 35,
      "dropout_female": 56,
      "dropout_total": 91
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "year": 2016,
      "enrolment_male": 2753,
      "enrolment_female": 3521,
      "enrolment_total": 6274,
      "dropout_male": 230,
      "dropout_female": 308,
      "dropout_total": 538
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "year": 2016,
      "enrolment_male": 4951,
      "enrolment_female": 5437,
      "enrolment_total": 10388,
      "dropout_male": 232,
      "dropout_female": 179,
      "dropout_total": 411
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "year": 2016,
      "enrolment_male": 1907,
      "enrolment_female": 3534,
      "enrolment_total": 5441,
      "dropout_male": 91,
      "dropout_female": 94,
      "dropout_total": 185
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "year": 2016,
      "enrolment_male": 5786,
      "enrolment_female": 9771,
      "enrolment_total": 15557,
      "dropout_male": 312,
      "dropout_female": 410,
      "dropout_total": 722
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "year": 2016,
      "enrolment_male": 2032,
      "enrolment_female": 2306,
      "enrolment_total": 4338,
      "dropout_male": 147,
      "dropout_female": 133,
      "dropout_total": 280
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "year": 2016,
      "enrolment_male": 4884,
      "enrolment_female": 5451,
      "enrolment_total": 10335,
      "dropout_male": 247,
      "dropout_female": 243,
      "dropout_total": 490
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "year": 2016,
      "enrolment_male": 1206,
      "enrolment_female": 1320,
      "enrolment_total": 2526,
      "dropout_male": 42,
      "dropout_female": 37,
      "dropout_total": 79
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "year": 2016,
      "enrolment_male": 12013,
      "enrolment_female": 10212,
      "enrolment_total": 22225,
      "dropout_male": 118,
      "dropout_female": 108,
      "dropout_total": 226
    },
    {
      "region": "Arusha",
      "council": "Arusha",
      "year": 2017,
      "enrolment_male": 9972,
      "enrolment_female": 12509,
      "enrolment_total": 22481,
      "dropout_male": 144,
      "dropout_female": 123,
      "dropout_total": 267
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "year": 2017,
      "enrolment_male": 13826,
      "enrolment_female": 14789,
      "enrolment_total": 28615,
      "dropout_male": 111,
      "dropout_female": 142,
      "dropout_total": 253
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "year": 2017,
      "enrolment_male": 4806,
      "enrolment_female": 5838,
      "enrolment_total": 10644,
      "dropout_male": 146,
      "dropout_female": 153,
      "dropout_total": 299
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "year": 2017,
      "enrolment_male": 2897,
      "enrolment_female": 3025,
      "enrolment_total": 5922,
      "dropout_male": 59,
      "dropout_female": 38,
      "dropout_total": 97
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "year": 2017,
      "enrolment_male": 9692,
      "enrolment_female": 11040,
      "enrolment_total": 20732,
      "dropout_male": 146,
      "dropout_female": 128,
      "dropout_total": 274
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "year": 2017,
      "enrolment_male": 4065,
      "enrolment_female": 4662,
      "enrolment_total": 8727,
      "dropout_male": 119,
      "dropout_female": 66,
      "dropout_total": 185
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "year": 2017,
      "enrolment_male": 3100,
      "enrolment_female": 2710,
      "enrolment_total": 5810,
      "dropout_male": 44,
      "dropout_female": 47,
      "dropout_total": 91
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ilala MC",
      "year": 2017,
      "enrolment_male": 30316,
      "enrolment_female": 31662,
      "enrolment_total": 61978,
      "dropout_male": 208,
      "dropout_female": 187,
      "dropout_total": 395
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kigamboni MC",
      "year": 2017,
      "enrolment_male": 5761,
      "enrolment_female": 5519,
      "enrolment_total": 11280,
      "dropout_male": 62,
      "dropout_female": 52,
      "dropout_total": 114
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kinondoni MC",
      "year": 2017,
      "enrolment_male": 17076,
      "enrolment_female": 17631,
      "enrolment_total": 34707,
      "dropout_male": 79,
      "dropout_female": 75,
      "dropout_total": 154
    },
    {
      "region": "Dar-es-salaam",
      "council": "Temeke MC",
      "year": 2017,
      "enrolment_male": 23449,
      "enrolment_female": 24856,
      "enrolment_total": 48305,
      "dropout_male": 344,
      "dropout_female": 320,
      "dropout_total": 664
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ubungo MC",
      "year": 2017,
      "enrolment_male": 16267,
      "enrolment_female": 17606,
      "enrolment_total": 33873,
      "dropout_male": 123,
      "dropout_female": 86,
      "dropout_total": 209
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "year": 2017,
      "enrolment_male": 1974,
      "enrolment_female": 1986,
      "enrolment_total": 3960,
      "dropout_male": 222,
      "dropout_female": 204,
      "dropout_total": 426
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "year": 2017,
      "enrolment_male": 3818,
      "enrolment_female": 4148,
      "enrolment_total": 7966,
      "dropout_male": 210,
      "dropout_female": 248,
      "dropout_total": 458
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "year": 2017,
      "enrolment_male": 2213,
      "enrolment_female": 3118,
      "enrolment_total": 5331,
      "dropout_male": 99,
      "dropout_female": 96,
      "dropout_total": 195
    },
    {
      "region": "Dodoma",
      "council": "Dodoma CC",
      "year": 2017,
      "enrolment_male": 11189,
      "enrolment_female": 11919,
      "enrolment_total": 23108,
      "dropout_male": 217,
      "dropout_female": 237,
      "dropout_total": 454
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "year": 2017,
      "enrolment_male": 2383,
      "enrolment_female": 3327,
      "enrolment_total": 5710,
      "dropout_male": 115,
      "dropout_female": 113,
      "dropout_total": 228
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "year": 2017,
      "enrolment_male": 1630,
      "enrolment_female": 3182,
      "enrolment_total": 4812,
      "dropout_male": 33,
      "dropout_female": 30,
      "dropout_total": 63
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "year": 2017,
      "enrolment_male": 4450,
      "enrolment_female": 5119,
      "enrolment_total": 9569,
      "dropout_male": 205,
      "dropout_female": 262,
      "dropout_total": 467
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "year": 2017,
      "enrolment_male": 4256,
      "enrolment_female": 4066,
      "enrolment_total": 8322,
      "dropout_male": 195,
      "dropout_female": 289,
      "dropout_total": 484
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "year": 2017,
      "enrolment_male": 5045,
      "enrolment_female": 3636,
      "enrolment_total": 8681,
      "dropout_male": 329,
      "dropout_female": 267,
      "dropout_total": 596
    },
    {
      "region": "Geita",
      "council": "Chato",
      "year": 2017,
      "enrolment_male": 6739,
      "enrolment_female": 5236,
      "enrolment_total": 11975,
      "dropout_male": 509,
      "dropout_female": 450,
      "dropout_total": 959
    },
    {
      "region": "Geita",
      "council": "Geita",
      "year": 2017,
      "enrolment_male": 10489,
      "enrolment_female": 8051,
      "enrolment_total": 18540,
      "dropout_male": 744,
      "dropout_female": 663,
      "dropout_total": 1407
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "year": 2017,
      "enrolment_male": 6419,
      "enrolment_female": 5875,
      "enrolment_total": 12294,
      "dropout_male": 122,
      "dropout_female": 76,
      "dropout_total": 198
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "year": 2017,
      "enrolment_male": 3159,
      "enrolment_female": 2646,
      "enrolment_total": 5805,
      "dropout_male": 448,
      "dropout_female": 386,
      "dropout_total": 834
    },
    {
      "region": "Geita",
      "council": "Nyanghwale",
      "year": 2017,
      "enrolment_male": 2813,
      "enrolment_female": 2645,
      "enrolment_total": 5458,
      "dropout_male": 213,
      "dropout_female": 189,
      "dropout_total": 402
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "year": 2017,
      "enrolment_male": 9052,
      "enrolment_female": 9797,
      "enrolment_total": 18849,
      "dropout_male": 280,
      "dropout_female": 225,
      "dropout_total": 505
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "year": 2017,
      "enrolment_male": 5562,
      "enrolment_female": 7687,
      "enrolment_total": 13249,
      "dropout_male": 72,
      "dropout_female": 98,
      "dropout_total": 170
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "year": 2017,
      "enrolment_male": 5830,
      "enrolment_female": 7031,
      "enrolment_total": 12861,
      "dropout_male": 266,
      "dropout_female": 219,
      "dropout_total": 485
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "year": 2017,
      "enrolment_male": 3991,
      "enrolment_female": 3421,
      "enrolment_total": 7412,
      "dropout_male": 57,
      "dropout_female": 74,
      "dropout_total": 131
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "year": 2017,
      "enrolment_male": 7242,
      "enrolment_female": 8630,
      "enrolment_total": 15872,
      "dropout_male": 306,
      "dropout_female": 315,
      "dropout_total": 621
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "year": 2017,
      "enrolment_male": 5371,
      "enrolment_female": 4514,
      "enrolment_total": 9885,
      "dropout_male": 286,
      "dropout_female": 322,
      "dropout_total": 608
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "year": 2017,
      "enrolment_male": 6382,
      "enrolment_female": 6293,
      "enrolment_total": 12675,
      "dropout_male": 119,
      "dropout_female": 135,
      "dropout_total": 254
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "year": 2017,
      "enrolment_male": 5850,
      "enrolment_female": 5867,
      "enrolment_total": 11717,
      "dropout_male": 18,
      "dropout_female": 46,
      "dropout_total": 64
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "year": 2017,
      "enrolment_male": 5072,
      "enrolment_female": 6075,
      "enrolment_total": 11147,
      "dropout_male": 280,
      "dropout_female": 239,
      "dropout_total": 519
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "year": 2017,
      "enrolment_male": 4295,
      "enrolment_female": 4623,
      "enrolment_total": 8918,
      "dropout_male": 246,
      "dropout_female": 275,
      "dropout_total": 521
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "year": 2017,
      "enrolment_male": 4479,
      "enrolment_female": 4897,
      "enrolment_total": 9376,
      "dropout_male": 169,
      "dropout_female": 134,
      "dropout_total": 303
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "year": 2017,
      "enrolment_male": 11114,
      "enrolment_female": 11122,
      "enrolment_total": 22236,
      "dropout_male": 594,
      "dropout_female": 565,
      "dropout_total": 1159
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "year": 2017,
      "enrolment_male": 5055,
      "enrolment_female": 5313,
      "enrolment_total": 10368,
      "dropout_male": 329,
      "dropout_female": 333,
      "dropout_total": 662
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "year": 2017,
      "enrolment_male": 531,
      "enrolment_female": 356,
      "enrolment_total": 887,
      "dropout_male": 35,
      "dropout_female": 29,
      "dropout_total": 64
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "year": 2017,
      "enrolment_male": 2197,
      "enrolment_female": 1806,
      "enrolment_total": 4003,
      "dropout_male": 240,
      "dropout_female": 135,
      "dropout_total": 375
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "year": 2017,
      "enrolment_male": 2899,
      "enrolment_female": 3805,
      "enrolment_total": 6704,
      "dropout_male": 91,
      "dropout_female": 124,
      "dropout_total": 215
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "year": 2017,
      "enrolment_male": 1215,
      "enrolment_female": 741,
      "enrolment_total": 1956,
      "dropout_male": 104,
      "dropout_female": 78,
      "dropout_total": 182
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "year": 2017,
      "enrolment_male": 2122,
      "enrolment_female": 1802,
      "enrolment_total": 3924,
      "dropout_male": 240,
      "dropout_female": 145,
      "dropout_total": 385
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "year": 2017,
      "enrolment_male": 4326,
      "enrolment_female": 2800,
      "enrolment_total": 7126,
      "dropout_male": 204,
      "dropout_female": 76,
      "dropout_total": 280
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "year": 2017,
      "enrolment_male": 2450,
      "enrolment_female": 1934,
      "enrolment_total": 4384,
      "dropout_male": 185,
      "dropout_female": 150,
      "dropout_total": 335
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "year": 2017,
      "enrolment_male": 3233,
      "enrolment_female": 2072,
      "enrolment_total": 5305,
      "dropout_male": 136,
      "dropout_female": 59,
      "dropout_total": 195
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "year": 2017,
      "enrolment_male": 4973,
      "enrolment_female": 4021,
      "enrolment_total": 8994,
      "dropout_male": 29,
      "dropout_female": 23,
      "dropout_total": 52
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "year": 2017,
      "enrolment_male": 4181,
      "enrolment_female": 4778,
      "enrolment_total": 8959,
      "dropout_male": 241,
      "dropout_female": 175,
      "dropout_total": 416
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "year": 2017,
      "enrolment_male": 4868,
      "enrolment_female": 3158,
      "enrolment_total": 8026,
      "dropout_male": 97,
      "dropout_female": 70,
      "dropout_total": 167
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "year": 2017,
      "enrolment_male": 6555,
      "enrolment_female": 4829,
      "enrolment_total": 11384,
      "dropout_male": 108,
      "dropout_female": 92,
      "dropout_total": 200
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "year": 2017,
      "enrolment_male": 4462,
      "enrolment_female": 2445,
      "enrolment_total": 6907,
      "dropout_male": 311,
      "dropout_female": 126,
      "dropout_total": 437
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "year": 2017,
      "enrolment_male": 7212,
      "enrolment_female": 8113,
      "enrolment_total": 15325,
      "dropout_male": 197,
      "dropout_female": 184,
      "dropout_total": 381
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "year": 2017,
      "enrolment_male": 16689,
      "enrolment_female": 19931,
      "enrolment_total": 36620,
      "dropout_male": 220,
      "dropout_female": 232,
      "dropout_total": 452
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "year": 2017,
      "enrolment_male": 9054,
      "enrolment_female": 7930,
      "enrolment_total": 16984,
      "dropout_male": 69,
      "dropout_female": 59,
      "dropout_total": 128
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "year": 2017,
      "enrolment_male": 7413,
      "enrolment_female": 8304,
      "enrolment_total": 15717,
      "dropout_male": 220,
      "dropout_female": 194,
      "dropout_total": 414
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "year": 2017,
      "enrolment_male": 8019,
      "enrolment_female": 11213,
      "enrolment_total": 19232,
      "dropout_male": 259,
      "dropout_female": 173,
      "dropout_total": 432
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "year": 2017,
      "enrolment_male": 9589,
      "enrolment_female": 11875,
      "enrolment_total": 21464,
      "dropout_male": 173,
      "dropout_female": 222,
      "dropout_total": 395
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "year": 2017,
      "enrolment_male": 2919,
      "enrolment_female": 4202,
      "enrolment_total": 7121,
      "dropout_male": 56,
      "dropout_female": 75,
      "dropout_total": 131
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "year": 2017,
      "enrolment_male": 2834,
      "enrolment_female": 3256,
      "enrolment_total": 6090,
      "dropout_male": 167,
      "dropout_female": 144,
      "dropout_total": 311
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "year": 2017,
      "enrolment_male": 3417,
      "enrolment_female": 2514,
      "enrolment_total": 5931,
      "dropout_male": 139,
      "dropout_female": 104,
      "dropout_total": 243
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "year": 2017,
      "enrolment_male": 1967,
      "enrolment_female": 1761,
      "enrolment_total": 3728,
      "dropout_male": 49,
      "dropout_female": 48,
      "dropout_total": 97
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "year": 2017,
      "enrolment_male": 1926,
      "enrolment_female": 1916,
      "enrolment_total": 3842,
      "dropout_male": 98,
      "dropout_female": 93,
      "dropout_total": 191
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "year": 2017,
      "enrolment_male": 2975,
      "enrolment_female": 2911,
      "enrolment_total": 5886,
      "dropout_male": 174,
      "dropout_female": 160,
      "dropout_total": 334
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "year": 2017,
      "enrolment_male": 1895,
      "enrolment_female": 1844,
      "enrolment_total": 3739,
      "dropout_male": 65,
      "dropout_female": 86,
      "dropout_total": 151
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "year": 2017,
      "enrolment_male": 5471,
      "enrolment_female": 7238,
      "enrolment_total": 12709,
      "dropout_male": 256,
      "dropout_female": 198,
      "dropout_total": 454
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "year": 2017,
      "enrolment_male": 3462,
      "enrolment_female": 4090,
      "enrolment_total": 7552,
      "dropout_male": 11,
      "dropout_female": 16,
      "dropout_total": 27
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "year": 2017,
      "enrolment_male": 3492,
      "enrolment_female": 4845,
      "enrolment_total": 8337,
      "dropout_male": 211,
      "dropout_female": 186,
      "dropout_total": 397
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "year": 2017,
      "enrolment_male": 2309,
      "enrolment_female": 2740,
      "enrolment_total": 5049,
      "dropout_male": 82,
      "dropout_female": 127,
      "dropout_total": 209
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "year": 2017,
      "enrolment_male": 2269,
      "enrolment_female": 3660,
      "enrolment_total": 5929,
      "dropout_male": 171,
      "dropout_female": 201,
      "dropout_total": 372
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "year": 2017,
      "enrolment_male": 2948,
      "enrolment_female": 3488,
      "enrolment_total": 6436,
      "dropout_male": 147,
      "dropout_female": 150,
      "dropout_total": 297
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "year": 2017,
      "enrolment_male": 2427,
      "enrolment_female": 2358,
      "enrolment_total": 4785,
      "dropout_male": 60,
      "dropout_female": 47,
      "dropout_total": 107
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "year": 2017,
      "enrolment_male": 5612,
      "enrolment_female": 3785,
      "enrolment_total": 9397,
      "dropout_male": 215,
      "dropout_female": 148,
      "dropout_total": 363
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "year": 2017,
      "enrolment_male": 4201,
      "enrolment_female": 3564,
      "enrolment_total": 7765,
      "dropout_male": 92,
      "dropout_female": 89,
      "dropout_total": 181
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "year": 2017,
      "enrolment_male": 5173,
      "enrolment_female": 4659,
      "enrolment_total": 9832,
      "dropout_male": 172,
      "dropout_female": 142,
      "dropout_total": 314
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "year": 2017,
      "enrolment_male": 4905,
      "enrolment_female": 3227,
      "enrolment_total": 8132,
      "dropout_male": 128,
      "dropout_female": 156,
      "dropout_total": 284
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "year": 2017,
      "enrolment_male": 7408,
      "enrolment_female": 5164,
      "enrolment_total": 12572,
      "dropout_male": 85,
      "dropout_female": 51,
      "dropout_total": 136
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "year": 2017,
      "enrolment_male": 7460,
      "enrolment_female": 5532,
      "enrolment_total": 12992,
      "dropout_male": 168,
      "dropout_female": 188,
      "dropout_total": 356
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "year": 2017,
      "enrolment_male": 6028,
      "enrolment_female": 5207,
      "enrolment_total": 11235,
      "dropout_male": 205,
      "dropout_female": 140,
      "dropout_total": 345
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "year": 2017,
      "enrolment_male": 6208,
      "enrolment_female": 4264,
      "enrolment_total": 10472,
      "dropout_male": 258,
      "dropout_female": 151,
      "dropout_total": 409
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "year": 2017,
      "enrolment_male": 3438,
      "enrolment_female": 2540,
      "enrolment_total": 5978,
      "dropout_male": 48,
      "dropout_female": 34,
      "dropout_total": 82
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "year": 2017,
      "enrolment_male": 3891,
      "enrolment_female": 3440,
      "enrolment_total": 7331,
      "dropout_male": 113,
      "dropout_female": 112,
      "dropout_total": 225
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "year": 2017,
      "enrolment_male": 2116,
      "enrolment_female": 1896,
      "enrolment_total": 4012,
      "dropout_male": 119,
      "dropout_female": 125,
      "dropout_total": 244
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "year": 2017,
      "enrolment_male": 7556,
      "enrolment_female": 6002,
      "enrolment_total": 13558,
      "dropout_male": 212,
      "dropout_female": 185,
      "dropout_total": 397
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "year": 2017,
      "enrolment_male": 4836,
      "enrolment_female": 5418,
      "enrolment_total": 10254,
      "dropout_male": 189,
      "dropout_female": 163,
      "dropout_total": 352
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "year": 2017,
      "enrolment_male": 8635,
      "enrolment_female": 9769,
      "enrolment_total": 18404,
      "dropout_male": 185,
      "dropout_female": 185,
      "dropout_total": 370
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "year": 2017,
      "enrolment_male": 17198,
      "enrolment_female": 17770,
      "enrolment_total": 34968,
      "dropout_male": 180,
      "dropout_female": 257,
      "dropout_total": 437
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "year": 2017,
      "enrolment_male": 9132,
      "enrolment_female": 8765,
      "enrolment_total": 17897,
      "dropout_male": 221,
      "dropout_female": 200,
      "dropout_total": 421
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "year": 2017,
      "enrolment_male": 1555,
      "enrolment_female": 2252,
      "enrolment_total": 3807,
      "dropout_male": 76,
      "dropout_female": 118,
      "dropout_total": 194
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "year": 2017,
      "enrolment_male": 2822,
      "enrolment_female": 3789,
      "enrolment_total": 6611,
      "dropout_male": 107,
      "dropout_female": 110,
      "dropout_total": 217
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "year": 2017,
      "enrolment_male": 5626,
      "enrolment_female": 5615,
      "enrolment_total": 11241,
      "dropout_male": 240,
      "dropout_female": 169,
      "dropout_total": 409
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "year": 2017,
      "enrolment_male": 7386,
      "enrolment_female": 7378,
      "enrolment_total": 14764,
      "dropout_male": 148,
      "dropout_female": 160,
      "dropout_total": 308
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "year": 2017,
      "enrolment_male": 2261,
      "enrolment_female": 2153,
      "enrolment_total": 4414,
      "dropout_male": 39,
      "dropout_female": 44,
      "dropout_total": 83
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "year": 2017,
      "enrolment_male": 3841,
      "enrolment_female": 4131,
      "enrolment_total": 7972,
      "dropout_male": 138,
      "dropout_female": 132,
      "dropout_total": 270
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "year": 2017,
      "enrolment_male": 11369,
      "enrolment_female": 13259,
      "enrolment_total": 24628,
      "dropout_male": 118,
      "dropout_female": 101,
      "dropout_total": 219
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "year": 2017,
      "enrolment_male": 5045,
      "enrolment_female": 5796,
      "enrolment_total": 10841,
      "dropout_male": 224,
      "dropout_female": 277,
      "dropout_total": 501
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "year": 2017,
      "enrolment_male": 3793,
      "enrolment_female": 2911,
      "enrolment_total": 6704,
      "dropout_male": 85,
      "dropout_female": 53,
      "dropout_total": 138
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "year": 2017,
      "enrolment_male": 4466,
      "enrolment_female": 3328,
      "enrolment_total": 7794,
      "dropout_male": 230,
      "dropout_female": 261,
      "dropout_total": 491
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "year": 2017,
      "enrolment_male": 1361,
      "enrolment_female": 1850,
      "enrolment_total": 3211,
      "dropout_male": 28,
      "dropout_female": 47,
      "dropout_total": 75
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "year": 2017,
      "enrolment_male": 1884,
      "enrolment_female": 2188,
      "enrolment_total": 4072,
      "dropout_male": 154,
      "dropout_female": 162,
      "dropout_total": 316
    },
    {
      "region": "Mtwara",
      "council": "Mtwara Mikindani MC",
      "year": 2017,
      "enrolment_male": 4236,
      "enrolment_female": 4773,
      "enrolment_total": 9009,
      "dropout_male": 74,
      "dropout_female": 63,
      "dropout_total": 137
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "year": 2017,
      "enrolment_male": 2060,
      "enrolment_female": 2035,
      "enrolment_total": 4095,
      "dropout_male": 280,
      "dropout_female": 215,
      "dropout_total": 495
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "year": 2017,
      "enrolment_male": 1381,
      "enrolment_female": 1471,
      "enrolment_total": 2852,
      "dropout_male": 105,
      "dropout_female": 78,
      "dropout_total": 183
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "year": 2017,
      "enrolment_male": 1786,
      "enrolment_female": 1974,
      "enrolment_total": 3760,
      "dropout_male": 86,
      "dropout_female": 69,
      "dropout_total": 155
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "year": 2017,
      "enrolment_male": 1653,
      "enrolment_female": 2168,
      "enrolment_total": 3821,
      "dropout_male": 67,
      "dropout_female": 95,
      "dropout_total": 162
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "year": 2017,
      "enrolment_male": 3772,
      "enrolment_female": 4324,
      "enrolment_total": 8096,
      "dropout_male": 549,
      "dropout_female": 579,
      "dropout_total": 1128
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "year": 2017,
      "enrolment_male": 6498,
      "enrolment_female": 4649,
      "enrolment_total": 11147,
      "dropout_male": 452,
      "dropout_female": 368,
      "dropout_total": 820
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "year": 2017,
      "enrolment_male": 13288,
      "enrolment_female": 13326,
      "enrolment_total": 26614,
      "dropout_male": 276,
      "dropout_female": 227,
      "dropout_total": 503
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "year": 2017,
      "enrolment_male": 7187,
      "enrolment_female": 7430,
      "enrolment_total": 14617,
      "dropout_male": 389,
      "dropout_female": 441,
      "dropout_total": 830
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "year": 2017,
      "enrolment_male": 7693,
      "enrolment_female": 6864,
      "enrolment_total": 14557,
      "dropout_male": 322,
      "dropout_female": 267,
      "dropout_total": 589
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "year": 2017,
      "enrolment_male": 5754,
      "enrolment_female": 6086,
      "enrolment_total": 11840,
      "dropout_male": 530,
      "dropout_female": 564,
      "dropout_total": 1094
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "year": 2017,
      "enrolment_male": 18261,
      "enrolment_female": 17910,
      "enrolment_total": 36171,
      "dropout_male": 358,
      "dropout_female": 299,
      "dropout_total": 657
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "year": 2017,
      "enrolment_male": 10255,
      "enrolment_female": 7492,
      "enrolment_total": 17747,
      "dropout_male": 349,
      "dropout_female": 389,
      "dropout_total": 738
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "year": 2017,
      "enrolment_male": 9210,
      "enrolment_female": 6614,
      "enrolment_total": 15824,
      "dropout_male": 400,
      "dropout_female": 414,
      "dropout_total": 814
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "year": 2017,
      "enrolment_male": 3243,
      "enrolment_female": 3431,
      "enrolment_total": 6674,
      "dropout_male": 148,
      "dropout_female": 163,
      "dropout_total": 311
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "year": 2017,
      "enrolment_male": 2622,
      "enrolment_female": 4080,
      "enrolment_total": 6702,
      "dropout_male": 44,
      "dropout_female": 89,
      "dropout_total": 133
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "year": 2017,
      "enrolment_male": 2829,
      "enrolment_female": 3173,
      "enrolment_total": 6002,
      "dropout_male": 131,
      "dropout_female": 106,
      "dropout_total": 237
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "year": 2017,
      "enrolment_male": 1564,
      "enrolment_female": 2978,
      "enrolment_total": 4542,
      "dropout_male": 115,
      "dropout_female": 137,
      "dropout_total": 252
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "year": 2017,
      "enrolment_male": 5102,
      "enrolment_female": 5294,
      "enrolment_total": 10396,
      "dropout_male": 114,
      "dropout_female": 121,
      "dropout_total": 235
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "year": 2017,
      "enrolment_male": 3890,
      "enrolment_female": 5614,
      "enrolment_total": 9504,
      "dropout_male": 277,
      "dropout_female": 199,
      "dropout_total": 476
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "year": 2017,
      "enrolment_male": 5098,
      "enrolment_female": 5614,
      "enrolment_total": 10712,
      "dropout_male": 62,
      "dropout_female": 54,
      "dropout_total": 116
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "year": 2017,
      "enrolment_male": 4947,
      "enrolment_female": 5381,
      "enrolment_total": 10328,
      "dropout_male": 160,
      "dropout_female": 159,
      "dropout_total": 319
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "year": 2017,
      "enrolment_male": 2374,
      "enrolment_female": 3632,
      "enrolment_total": 6006,
      "dropout_male": 78,
      "dropout_female": 83,
      "dropout_total": 161
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "year": 2017,
      "enrolment_male": 4904,
      "enrolment_female": 5771,
      "enrolment_total": 10675,
      "dropout_male": 73,
      "dropout_female": 71,
      "dropout_total": 144
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "year": 2017,
      "enrolment_male": 2532,
      "enrolment_female": 2133,
      "enrolment_total": 4665,
      "dropout_male": 73,
      "dropout_female": 84,
      "dropout_total": 157
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "year": 2017,
      "enrolment_male": 3429,
      "enrolment_female": 2523,
      "enrolment_total": 5952,
      "dropout_male": 182,
      "dropout_female": 165,
      "dropout_total": 347
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "year": 2017,
      "enrolment_male": 759,
      "enrolment_female": 887,
      "enrolment_total": 1646,
      "dropout_male": 12,
      "dropout_female": 13,
      "dropout_total": 25
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "year": 2017,
      "enrolment_male": 6323,
      "enrolment_female": 5814,
      "enrolment_total": 12137,
      "dropout_male": 188,
      "dropout_female": 164,
      "dropout_total": 352
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "year": 2017,
      "enrolment_male": 1895,
      "enrolment_female": 1720,
      "enrolment_total": 3615,
      "dropout_male": 38,
      "dropout_female": 24,
      "dropout_total": 62
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "year": 2017,
      "enrolment_male": 3483,
      "enrolment_female": 1941,
      "enrolment_total": 5424,
      "dropout_male": 200,
      "dropout_female": 145,
      "dropout_total": 345
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "year": 2017,
      "enrolment_male": 3905,
      "enrolment_female": 3165,
      "enrolment_total": 7070,
      "dropout_male": 306,
      "dropout_female": 247,
      "dropout_total": 553
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "year": 2017,
      "enrolment_male": 3628,
      "enrolment_female": 2629,
      "enrolment_total": 6257,
      "dropout_male": 300,
      "dropout_female": 232,
      "dropout_total": 532
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "year": 2017,
      "enrolment_male": 7321,
      "enrolment_female": 6914,
      "enrolment_total": 14235,
      "dropout_male": 109,
      "dropout_female": 136,
      "dropout_total": 245
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "year": 2017,
      "enrolment_male": 1459,
      "enrolment_female": 1483,
      "enrolment_total": 2942,
      "dropout_male": 70,
      "dropout_female": 70,
      "dropout_total": 140
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "year": 2017,
      "enrolment_male": 5481,
      "enrolment_female": 6417,
      "enrolment_total": 11898,
      "dropout_male": 218,
      "dropout_female": 229,
      "dropout_total": 447
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "year": 2017,
      "enrolment_male": 2686,
      "enrolment_female": 3032,
      "enrolment_total": 5718,
      "dropout_male": 76,
      "dropout_female": 102,
      "dropout_total": 178
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "year": 2017,
      "enrolment_male": 4080,
      "enrolment_female": 3816,
      "enrolment_total": 7896,
      "dropout_male": 277,
      "dropout_female": 274,
      "dropout_total": 551
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "year": 2017,
      "enrolment_male": 2729,
      "enrolment_female": 2670,
      "enrolment_total": 5399,
      "dropout_male": 142,
      "dropout_female": 169,
      "dropout_total": 311
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "year": 2017,
      "enrolment_male": 2347,
      "enrolment_female": 3465,
      "enrolment_total": 5812,
      "dropout_male": 86,
      "dropout_female": 100,
      "dropout_total": 186
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "year": 2017,
      "enrolment_male": 7644,
      "enrolment_female": 8070,
      "enrolment_total": 15714,
      "dropout_male": 61,
      "dropout_female": 99,
      "dropout_total": 160
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "year": 2017,
      "enrolment_male": 5127,
      "enrolment_female": 3918,
      "enrolment_total": 9045,
      "dropout_male": 258,
      "dropout_female": 258,
      "dropout_total": 516
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "year": 2017,
      "enrolment_male": 6301,
      "enrolment_female": 6401,
      "enrolment_total": 12702,
      "dropout_male": 171,
      "dropout_female": 149,
      "dropout_total": 320
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "year": 2017,
      "enrolment_male": 5308,
      "enrolment_female": 4295,
      "enrolment_total": 9603,
      "dropout_male": 189,
      "dropout_female": 186,
      "dropout_total": 375
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "year": 2017,
      "enrolment_male": 3664,
      "enrolment_female": 3428,
      "enrolment_total": 7092,
      "dropout_male": 305,
      "dropout_female": 291,
      "dropout_total": 596
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "year": 2017,
      "enrolment_male": 4670,
      "enrolment_female": 4619,
      "enrolment_total": 9289,
      "dropout_male": 259,
      "dropout_female": 216,
      "dropout_total": 475
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "year": 2017,
      "enrolment_male": 4619,
      "enrolment_female": 4532,
      "enrolment_total": 9151,
      "dropout_male": 67,
      "dropout_female": 80,
      "dropout_total": 147
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "year": 2017,
      "enrolment_male": 2991,
      "enrolment_female": 2528,
      "enrolment_total": 5519,
      "dropout_male": 209,
      "dropout_female": 142,
      "dropout_total": 351
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "year": 2017,
      "enrolment_male": 3788,
      "enrolment_female": 3331,
      "enrolment_total": 7119,
      "dropout_male": 333,
      "dropout_female": 230,
      "dropout_total": 563
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "year": 2017,
      "enrolment_male": 3480,
      "enrolment_female": 2990,
      "enrolment_total": 6470,
      "dropout_male": 294,
      "dropout_female": 243,
      "dropout_total": 537
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "year": 2017,
      "enrolment_male": 5982,
      "enrolment_female": 4633,
      "enrolment_total": 10615,
      "dropout_male": 368,
      "dropout_female": 260,
      "dropout_total": 628
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "year": 2017,
      "enrolment_male": 3830,
      "enrolment_female": 2828,
      "enrolment_total": 6658,
      "dropout_male": 248,
      "dropout_female": 196,
      "dropout_total": 444
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "year": 2017,
      "enrolment_male": 5713,
      "enrolment_female": 5195,
      "enrolment_total": 10908,
      "dropout_male": 284,
      "dropout_female": 199,
      "dropout_total": 483
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "year": 2017,
      "enrolment_male": 3159,
      "enrolment_female": 2826,
      "enrolment_total": 5985,
      "dropout_male": 131,
      "dropout_female": 112,
      "dropout_total": 243
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "year": 2017,
      "enrolment_male": 3998,
      "enrolment_female": 5126,
      "enrolment_total": 9124,
      "dropout_male": 200,
      "dropout_female": 151,
      "dropout_total": 351
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "year": 2017,
      "enrolment_male": 3431,
      "enrolment_female": 3669,
      "enrolment_total": 7100,
      "dropout_male": 233,
      "dropout_female": 176,
      "dropout_total": 409
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "year": 2017,
      "enrolment_male": 1566,
      "enrolment_female": 1304,
      "enrolment_total": 2870,
      "dropout_male": 47,
      "dropout_female": 50,
      "dropout_total": 97
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "year": 2017,
      "enrolment_male": 2269,
      "enrolment_female": 2503,
      "enrolment_total": 4772,
      "dropout_male": 62,
      "dropout_female": 68,
      "dropout_total": 130
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "year": 2017,
      "enrolment_male": 2239,
      "enrolment_female": 2477,
      "enrolment_total": 4716,
      "dropout_male": 132,
      "dropout_female": 133,
      "dropout_total": 265
    },
    {
      "region": "Singida",
      "council": "Singida",
      "year": 2017,
      "enrolment_male": 3694,
      "enrolment_female": 4811,
      "enrolment_total": 8505,
      "dropout_male": 197,
      "dropout_female": 154,
      "dropout_total": 351
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "year": 2017,
      "enrolment_male": 4416,
      "enrolment_female": 3830,
      "enrolment_total": 8246,
      "dropout_male": 71,
      "dropout_female": 65,
      "dropout_total": 136
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "year": 2017,
      "enrolment_male": 2528,
      "enrolment_female": 3306,
      "enrolment_total": 5834,
      "dropout_male": 69,
      "dropout_female": 101,
      "dropout_total": 170
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "year": 2017,
      "enrolment_male": 10260,
      "enrolment_female": 12735,
      "enrolment_total": 22995,
      "dropout_male": 392,
      "dropout_female": 350,
      "dropout_total": 742
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "year": 2017,
      "enrolment_male": 1424,
      "enrolment_female": 868,
      "enrolment_total": 2292,
      "dropout_male": 188,
      "dropout_female": 89,
      "dropout_total": 277
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "year": 2017,
      "enrolment_male": 1618,
      "enrolment_female": 1363,
      "enrolment_total": 2981,
      "dropout_male": 93,
      "dropout_female": 99,
      "dropout_total": 192
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "year": 2017,
      "enrolment_male": 2306,
      "enrolment_female": 2165,
      "enrolment_total": 4471,
      "dropout_male": 113,
      "dropout_female": 77,
      "dropout_total": 190
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "year": 2017,
      "enrolment_male": 5669,
      "enrolment_female": 5870,
      "enrolment_total": 11539,
      "dropout_male": 491,
      "dropout_female": 457,
      "dropout_total": 948
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "year": 2017,
      "enrolment_male": 4210,
      "enrolment_female": 2866,
      "enrolment_total": 7076,
      "dropout_male": 340,
      "dropout_female": 191,
      "dropout_total": 531
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "year": 2017,
      "enrolment_male": 3380,
      "enrolment_female": 3450,
      "enrolment_total": 6830,
      "dropout_male": 418,
      "dropout_female": 419,
      "dropout_total": 837
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "year": 2017,
      "enrolment_male": 1625,
      "enrolment_female": 2049,
      "enrolment_total": 3674,
      "dropout_male": 87,
      "dropout_female": 72,
      "dropout_total": 159
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "year": 2017,
      "enrolment_male": 2134,
      "enrolment_female": 2162,
      "enrolment_total": 4296,
      "dropout_male": 326,
      "dropout_female": 402,
      "dropout_total": 728
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "year": 2017,
      "enrolment_male": 8254,
      "enrolment_female": 6710,
      "enrolment_total": 14964,
      "dropout_male": 190,
      "dropout_female": 136,
      "dropout_total": 326
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "year": 2017,
      "enrolment_male": 3355,
      "enrolment_female": 3268,
      "enrolment_total": 6623,
      "dropout_male": 366,
      "dropout_female": 332,
      "dropout_total": 698
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "year": 2017,
      "enrolment_male": 2985,
      "enrolment_female": 2772,
      "enrolment_total": 5757,
      "dropout_male": 141,
      "dropout_female": 136,
      "dropout_total": 277
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "year": 2017,
      "enrolment_male": 3603,
      "enrolment_female": 4353,
      "enrolment_total": 7956,
      "dropout_male": 142,
      "dropout_female": 172,
      "dropout_total": 314
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "year": 2017,
      "enrolment_male": 3239,
      "enrolment_female": 3772,
      "enrolment_total": 7011,
      "dropout_male": 121,
      "dropout_female": 204,
      "dropout_total": 325
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "year": 2017,
      "enrolment_male": 1819,
      "enrolment_female": 2214,
      "enrolment_total": 4033,
      "dropout_male": 59,
      "dropout_female": 72,
      "dropout_total": 131
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "year": 2017,
      "enrolment_male": 2749,
      "enrolment_female": 3634,
      "enrolment_total": 6383,
      "dropout_male": 188,
      "dropout_female": 214,
      "dropout_total": 402
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "year": 2017,
      "enrolment_male": 4967,
      "enrolment_female": 5701,
      "enrolment_total": 10668,
      "dropout_male": 314,
      "dropout_female": 223,
      "dropout_total": 537
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "year": 2017,
      "enrolment_male": 1721,
      "enrolment_female": 3300,
      "enrolment_total": 5021,
      "dropout_male": 71,
      "dropout_female": 82,
      "dropout_total": 153
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "year": 2017,
      "enrolment_male": 5619,
      "enrolment_female": 9801,
      "enrolment_total": 15420,
      "dropout_male": 512,
      "dropout_female": 729,
      "dropout_total": 1241
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "year": 2017,
      "enrolment_male": 1844,
      "enrolment_female": 2132,
      "enrolment_total": 3976,
      "dropout_male": 59,
      "dropout_female": 56,
      "dropout_total": 115
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "year": 2017,
      "enrolment_male": 4704,
      "enrolment_female": 5283,
      "enrolment_total": 9987,
      "dropout_male": 125,
      "dropout_female": 136,
      "dropout_total": 261
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "year": 2017,
      "enrolment_male": 1382,
      "enrolment_female": 1282,
      "enrolment_total": 2664,
      "dropout_male": 35,
      "dropout_female": 44,
      "dropout_total": 79
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "year": 2017,
      "enrolment_male": 11855,
      "enrolment_female": 9928,
      "enrolment_total": 21783,
      "dropout_male": 114,
      "dropout_female": 118,
      "dropout_total": 232
    }
   ]