export const data = [
  {
    "region": "REGION",
    "council": "COUNCIL",
    "year": "YEAR",
    "enrolment_male": 29791,
    "enrolment_female": 31990,
    "enrolment_total": "ENROLMENT TOTAL",
    "dropout_male": 535,
    "dropout_female": 387,
    "dropout_total": "DROPOUT TOTAL"
  },
    {
      "region": "Arusha",
      "council": "Arusha",
      "year": 2016,
      "enrolment_male": 29791,
      "enrolment_female": 31990,
      "enrolment_total": 61781,
      "dropout_male": 535,
      "dropout_female": 387,
      "dropout_total": 922
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "year": 2016,
      "enrolment_male": 38946,
      "enrolment_female": 39902,
      "enrolment_total": 78848,
      "dropout_male": 102,
      "dropout_female": 82,
      "dropout_total": 184
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "year": 2016,
      "enrolment_male": 20939,
      "enrolment_female": 21200,
      "enrolment_total": 42139,
      "dropout_male": 158,
      "dropout_female": 107,
      "dropout_total": 265
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "year": 2016,
      "enrolment_male": 9085,
      "enrolment_female": 7403,
      "enrolment_total": 16488,
      "dropout_male": 313,
      "dropout_female": 171,
      "dropout_total": 484
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "year": 2016,
      "enrolment_male": 26308,
      "enrolment_female": 25995,
      "enrolment_total": 52303,
      "dropout_male": 53,
      "dropout_female": 51,
      "dropout_total": 104
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "year": 2016,
      "enrolment_male": 12877,
      "enrolment_female": 13116,
      "enrolment_total": 25993,
      "dropout_male": 86,
      "dropout_female": 63,
      "dropout_total": 149
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "year": 2016,
      "enrolment_male": 14383,
      "enrolment_female": 11198,
      "enrolment_total": 25581,
      "dropout_male": 88,
      "dropout_female": 65,
      "dropout_total": 153
    },
    {
      "region": "Dar es salaam",
      "council": "Ilala MC",
      "year": 2016,
      "enrolment_male": 91041,
      "enrolment_female": 95151,
      "enrolment_total": 186192,
      "dropout_male": 147,
      "dropout_female": 150,
      "dropout_total": 297
    },
    {
      "region": "Dar es salaam",
      "council": "Kigamboni MC",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 70,
      "dropout_female": 79,
      "dropout_total": 149
    },
    {
      "region": "Dar es salaam",
      "council": "Kinondoni MC",
      "year": 2016,
      "enrolment_male": 96914,
      "enrolment_female": 100357,
      "enrolment_total": 197271,
      "dropout_male": 51,
      "dropout_female": 59,
      "dropout_total": 110
    },
    {
      "region": "Dar es salaam",
      "council": "Temeke MC",
      "year": 2016,
      "enrolment_male": 91638,
      "enrolment_female": 97423,
      "enrolment_total": 189061,
      "dropout_male": 361,
      "dropout_female": 356,
      "dropout_total": 717
    },
    {
      "region": "Dar es salaam",
      "council": "Ubungo MC",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 99,
      "dropout_female": 89,
      "dropout_total": 188
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "year": 2016,
      "enrolment_male": 15030,
      "enrolment_female": 16746,
      "enrolment_total": 31776,
      "dropout_male": 274,
      "dropout_female": 227,
      "dropout_total": 501
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "year": 2016,
      "enrolment_male": 26652,
      "enrolment_female": 30310,
      "enrolment_total": 56962,
      "dropout_male": 221,
      "dropout_female": 174,
      "dropout_total": 395
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "year": 2016,
      "enrolment_male": 21479,
      "enrolment_female": 24035,
      "enrolment_total": 45514,
      "dropout_male": 507,
      "dropout_female": 253,
      "dropout_total": 760
    },
    {
      "region": "Dodoma",
      "council": "Dodoma MC",
      "year": 2016,
      "enrolment_male": 39476,
      "enrolment_female": 41369,
      "enrolment_total": 80845,
      "dropout_male": 114,
      "dropout_female": 97,
      "dropout_total": 211
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "year": 2016,
      "enrolment_male": 20344,
      "enrolment_female": 22213,
      "enrolment_total": 42557,
      "dropout_male": 73,
      "dropout_female": 38,
      "dropout_total": 111
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "year": 2016,
      "enrolment_male": 5689,
      "enrolment_female": 6012,
      "enrolment_total": 11701,
      "dropout_male": 11,
      "dropout_female": 6,
      "dropout_total": 17
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "year": 2016,
      "enrolment_male": 28378,
      "enrolment_female": 32904,
      "enrolment_total": 61282,
      "dropout_male": 238,
      "dropout_female": 254,
      "dropout_total": 492
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "year": 2016,
      "enrolment_male": 29065,
      "enrolment_female": 32852,
      "enrolment_total": 61917,
      "dropout_male": 1387,
      "dropout_female": 1251,
      "dropout_total": 2638
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "year": 2016,
      "enrolment_male": 29526,
      "enrolment_female": 29375,
      "enrolment_total": 58901,
      "dropout_male": 117,
      "dropout_female": 107,
      "dropout_total": 224
    },
    {
      "region": "Geita",
      "council": "Chato",
      "year": 2016,
      "enrolment_male": 44695,
      "enrolment_female": 43865,
      "enrolment_total": 88560,
      "dropout_male": 2362,
      "dropout_female": 2146,
      "dropout_total": 4508
    },
    {
      "region": "Geita",
      "council": "Geita",
      "year": 2016,
      "enrolment_male": 83090,
      "enrolment_female": 83540,
      "enrolment_total": 166630,
      "dropout_male": 3998,
      "dropout_female": 3893,
      "dropout_total": 7891
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "year": 2016,
      "enrolment_male": 26140,
      "enrolment_female": 26599,
      "enrolment_total": 52739,
      "dropout_male": 139,
      "dropout_female": 128,
      "dropout_total": 267
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "year": 2016,
      "enrolment_male": 23247,
      "enrolment_female": 23573,
      "enrolment_total": 46820,
      "dropout_male": 790,
      "dropout_female": 713,
      "dropout_total": 1503
    },
    {
      "region": "Geita",
      "council": "Nyang'hwale",
      "year": 2016,
      "enrolment_male": 16064,
      "enrolment_female": 16634,
      "enrolment_total": 32698,
      "dropout_male": 466,
      "dropout_female": 438,
      "dropout_total": 904
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "year": 2016,
      "enrolment_male": 28390,
      "enrolment_female": 29199,
      "enrolment_total": 57589,
      "dropout_male": 127,
      "dropout_female": 77,
      "dropout_total": 204
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "year": 2016,
      "enrolment_male": 13990,
      "enrolment_female": 14538,
      "enrolment_total": 28528,
      "dropout_male": 12,
      "dropout_female": 8,
      "dropout_total": 20
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "year": 2016,
      "enrolment_male": 23545,
      "enrolment_female": 24689,
      "enrolment_total": 48234,
      "dropout_male": 332,
      "dropout_female": 130,
      "dropout_total": 462
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "year": 2016,
      "enrolment_male": 7315,
      "enrolment_female": 7469,
      "enrolment_total": 14784,
      "dropout_male": 21,
      "dropout_female": 14,
      "dropout_total": 35
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "year": 2016,
      "enrolment_male": 25793,
      "enrolment_female": 27185,
      "enrolment_total": 52978,
      "dropout_male": 269,
      "dropout_female": 164,
      "dropout_total": 433
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "year": 2016,
      "enrolment_male": 32340,
      "enrolment_female": 31539,
      "enrolment_total": 63879,
      "dropout_male": 2522,
      "dropout_female": 2081,
      "dropout_total": 4603
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "year": 2016,
      "enrolment_male": 28025,
      "enrolment_female": 28473,
      "enrolment_total": 56498,
      "dropout_male": 80,
      "dropout_female": 76,
      "dropout_total": 156
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "year": 2016,
      "enrolment_male": 11017,
      "enrolment_female": 11351,
      "enrolment_total": 22368,
      "dropout_male": 13,
      "dropout_female": 10,
      "dropout_total": 23
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "year": 2016,
      "enrolment_male": 27110,
      "enrolment_female": 28417,
      "enrolment_total": 55527,
      "dropout_male": 313,
      "dropout_female": 231,
      "dropout_total": 544
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "year": 2016,
      "enrolment_male": 28857,
      "enrolment_female": 30882,
      "enrolment_total": 59739,
      "dropout_male": 166,
      "dropout_female": 145,
      "dropout_total": 311
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "year": 2016,
      "enrolment_male": 18073,
      "enrolment_female": 18204,
      "enrolment_total": 36277,
      "dropout_male": 131,
      "dropout_female": 129,
      "dropout_total": 260
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "year": 2016,
      "enrolment_male": 59043,
      "enrolment_female": 59375,
      "enrolment_total": 118418,
      "dropout_male": 1321,
      "dropout_female": 1244,
      "dropout_total": 2565
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "year": 2016,
      "enrolment_male": 26176,
      "enrolment_female": 26476,
      "enrolment_total": 52652,
      "dropout_male": 217,
      "dropout_female": 145,
      "dropout_total": 362
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "year": 2016,
      "enrolment_male": 3953,
      "enrolment_female": 3773,
      "enrolment_total": 7726,
      "dropout_male": 13,
      "dropout_female": 7,
      "dropout_total": 20
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "year": 2016,
      "enrolment_male": 16953,
      "enrolment_female": 17030,
      "enrolment_total": 33983,
      "dropout_male": 129,
      "dropout_female": 94,
      "dropout_total": 223
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "year": 2016,
      "enrolment_male": 14307,
      "enrolment_female": 14710,
      "enrolment_total": 29017,
      "dropout_male": 183,
      "dropout_female": 179,
      "dropout_total": 362
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "year": 2016,
      "enrolment_male": 8794,
      "enrolment_female": 8618,
      "enrolment_total": 17412,
      "dropout_male": 242,
      "dropout_female": 207,
      "dropout_total": 449
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "year": 2016,
      "enrolment_male": 13671,
      "enrolment_female": 13395,
      "enrolment_total": 27066,
      "dropout_male": 184,
      "dropout_female": 156,
      "dropout_total": 340
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "year": 2016,
      "enrolment_male": 23431,
      "enrolment_female": 23472,
      "enrolment_total": 46903,
      "dropout_male": 554,
      "dropout_female": 455,
      "dropout_total": 1009
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "year": 2016,
      "enrolment_male": 15278,
      "enrolment_female": 15289,
      "enrolment_total": 30567,
      "dropout_male": 34,
      "dropout_female": 18,
      "dropout_total": 52
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "year": 2016,
      "enrolment_male": 26955,
      "enrolment_female": 26458,
      "enrolment_total": 53413,
      "dropout_male": 141,
      "dropout_female": 135,
      "dropout_total": 276
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "year": 2016,
      "enrolment_male": 23708,
      "enrolment_female": 24310,
      "enrolment_total": 48018,
      "dropout_male": 40,
      "dropout_female": 43,
      "dropout_total": 83
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "year": 2016,
      "enrolment_male": 24228,
      "enrolment_female": 23823,
      "enrolment_total": 48051,
      "dropout_male": 556,
      "dropout_female": 457,
      "dropout_total": 1013
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "year": 2016,
      "enrolment_male": 24642,
      "enrolment_female": 24625,
      "enrolment_total": 49267,
      "dropout_male": 122,
      "dropout_female": 165,
      "dropout_total": 287
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "year": 2016,
      "enrolment_male": 20940,
      "enrolment_female": 20906,
      "enrolment_total": 41846,
      "dropout_male": 237,
      "dropout_female": 186,
      "dropout_total": 423
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "year": 2016,
      "enrolment_male": 35316,
      "enrolment_female": 34219,
      "enrolment_total": 69535,
      "dropout_male": 1145,
      "dropout_female": 946,
      "dropout_total": 2091
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "year": 2016,
      "enrolment_male": 17523,
      "enrolment_female": 17072,
      "enrolment_total": 34595,
      "dropout_male": 185,
      "dropout_female": 165,
      "dropout_total": 350
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "year": 2016,
      "enrolment_male": 35070,
      "enrolment_female": 34063,
      "enrolment_total": 69133,
      "dropout_male": 297,
      "dropout_female": 251,
      "dropout_total": 548
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "year": 2016,
      "enrolment_male": 13571,
      "enrolment_female": 13506,
      "enrolment_total": 27077,
      "dropout_male": 57,
      "dropout_female": 51,
      "dropout_total": 108
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "year": 2016,
      "enrolment_male": 12069,
      "enrolment_female": 11424,
      "enrolment_total": 23493,
      "dropout_male": 173,
      "dropout_female": 114,
      "dropout_total": 287
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "year": 2016,
      "enrolment_male": 22952,
      "enrolment_female": 22743,
      "enrolment_total": 45695,
      "dropout_male": 170,
      "dropout_female": 118,
      "dropout_total": 288
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "year": 2016,
      "enrolment_male": 27366,
      "enrolment_female": 26307,
      "enrolment_total": 53673,
      "dropout_male": 437,
      "dropout_female": 396,
      "dropout_total": 833
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "year": 2016,
      "enrolment_male": 9242,
      "enrolment_female": 9328,
      "enrolment_total": 18570,
      "dropout_male": 53,
      "dropout_female": 42,
      "dropout_total": 95
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "year": 2016,
      "enrolment_male": 20042,
      "enrolment_female": 20146,
      "enrolment_total": 40188,
      "dropout_male": 230,
      "dropout_female": 164,
      "dropout_total": 394
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "year": 2016,
      "enrolment_male": 17291,
      "enrolment_female": 18039,
      "enrolment_total": 35330,
      "dropout_male": 279,
      "dropout_female": 180,
      "dropout_total": 459
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "year": 2016,
      "enrolment_male": 6809,
      "enrolment_female": 6918,
      "enrolment_total": 13727,
      "dropout_male": 20,
      "dropout_female": 16,
      "dropout_total": 36
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "year": 2016,
      "enrolment_male": 9577,
      "enrolment_female": 9785,
      "enrolment_total": 19362,
      "dropout_male": 97,
      "dropout_female": 49,
      "dropout_total": 146
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "year": 2016,
      "enrolment_male": 15297,
      "enrolment_female": 15916,
      "enrolment_total": 31213,
      "dropout_male": 57,
      "dropout_female": 33,
      "dropout_total": 90
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "year": 2016,
      "enrolment_male": 10608,
      "enrolment_female": 11211,
      "enrolment_total": 21819,
      "dropout_male": 171,
      "dropout_female": 92,
      "dropout_total": 263
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "year": 2016,
      "enrolment_male": 30409,
      "enrolment_female": 31737,
      "enrolment_total": 62146,
      "dropout_male": 370,
      "dropout_female": 234,
      "dropout_total": 604
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "year": 2016,
      "enrolment_male": 8425,
      "enrolment_female": 8774,
      "enrolment_total": 17199,
      "dropout_male": 19,
      "dropout_female": 12,
      "dropout_total": 31
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "year": 2016,
      "enrolment_male": 27715,
      "enrolment_female": 28524,
      "enrolment_total": 56239,
      "dropout_male": 1410,
      "dropout_female": 888,
      "dropout_total": 2298
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "year": 2016,
      "enrolment_male": 16779,
      "enrolment_female": 16808,
      "enrolment_total": 33587,
      "dropout_male": 135,
      "dropout_female": 129,
      "dropout_total": 264
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "year": 2016,
      "enrolment_male": 16013,
      "enrolment_female": 17247,
      "enrolment_total": 33260,
      "dropout_male": 611,
      "dropout_female": 337,
      "dropout_total": 948
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "year": 2016,
      "enrolment_male": 11501,
      "enrolment_female": 11933,
      "enrolment_total": 23434,
      "dropout_male": 364,
      "dropout_female": 200,
      "dropout_total": 564
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "year": 2016,
      "enrolment_male": 16065,
      "enrolment_female": 14497,
      "enrolment_total": 30562,
      "dropout_male": 233,
      "dropout_female": 168,
      "dropout_total": 401
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "year": 2016,
      "enrolment_male": 29224,
      "enrolment_female": 28572,
      "enrolment_total": 57796,
      "dropout_male": 54,
      "dropout_female": 51,
      "dropout_total": 105
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "year": 2016,
      "enrolment_male": 20773,
      "enrolment_female": 20462,
      "enrolment_total": 41235,
      "dropout_male": 358,
      "dropout_female": 320,
      "dropout_total": 678
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "year": 2016,
      "enrolment_male": 30651,
      "enrolment_female": 30006,
      "enrolment_total": 60657,
      "dropout_male": 1207,
      "dropout_female": 1290,
      "dropout_total": 2497
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "year": 2016,
      "enrolment_male": 28177,
      "enrolment_female": 27436,
      "enrolment_total": 55613,
      "dropout_male": 67,
      "dropout_female": 98,
      "dropout_total": 165
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "year": 2016,
      "enrolment_male": 17961,
      "enrolment_female": 19003,
      "enrolment_total": 36964,
      "dropout_male": 22,
      "dropout_female": 20,
      "dropout_total": 42
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "year": 2016,
      "enrolment_male": 38008,
      "enrolment_female": 37312,
      "enrolment_total": 75320,
      "dropout_male": 179,
      "dropout_female": 164,
      "dropout_total": 343
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "year": 2016,
      "enrolment_male": 33903,
      "enrolment_female": 32149,
      "enrolment_total": 66052,
      "dropout_male": 489,
      "dropout_female": 484,
      "dropout_total": 973
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "year": 2016,
      "enrolment_male": 38811,
      "enrolment_female": 36968,
      "enrolment_total": 75779,
      "dropout_male": 705,
      "dropout_female": 745,
      "dropout_total": 1450
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "year": 2016,
      "enrolment_male": 12872,
      "enrolment_female": 13132,
      "enrolment_total": 26004,
      "dropout_male": 132,
      "dropout_female": 99,
      "dropout_total": 231
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "year": 2016,
      "enrolment_male": 10865,
      "enrolment_female": 11205,
      "enrolment_total": 22070,
      "dropout_male": 29,
      "dropout_female": 11,
      "dropout_total": 40
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "year": 2016,
      "enrolment_male": 24527,
      "enrolment_female": 25834,
      "enrolment_total": 50361,
      "dropout_male": 216,
      "dropout_female": 191,
      "dropout_total": 407
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "year": 2016,
      "enrolment_male": 24849,
      "enrolment_female": 25054,
      "enrolment_total": 49903,
      "dropout_male": 86,
      "dropout_female": 81,
      "dropout_total": 167
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "year": 2016,
      "enrolment_male": 26033,
      "enrolment_female": 27494,
      "enrolment_total": 53527,
      "dropout_male": 28,
      "dropout_female": 37,
      "dropout_total": 65
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "year": 2016,
      "enrolment_male": 32237,
      "enrolment_female": 34075,
      "enrolment_total": 66312,
      "dropout_male": 129,
      "dropout_female": 94,
      "dropout_total": 223
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "year": 2016,
      "enrolment_male": 36878,
      "enrolment_female": 38887,
      "enrolment_total": 75765,
      "dropout_male": 197,
      "dropout_female": 128,
      "dropout_total": 325
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "year": 2016,
      "enrolment_male": 26456,
      "enrolment_female": 27170,
      "enrolment_total": 53626,
      "dropout_male": 310,
      "dropout_female": 203,
      "dropout_total": 513
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "year": 2016,
      "enrolment_male": 13718,
      "enrolment_female": 16232,
      "enrolment_total": 29950,
      "dropout_male": 126,
      "dropout_female": 90,
      "dropout_total": 216
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "year": 2016,
      "enrolment_male": 10769,
      "enrolment_female": 10758,
      "enrolment_total": 21527,
      "dropout_male": 56,
      "dropout_female": 44,
      "dropout_total": 100
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "year": 2016,
      "enrolment_male": 32006,
      "enrolment_female": 32309,
      "enrolment_total": 64315,
      "dropout_male": 118,
      "dropout_female": 126,
      "dropout_total": 244
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "year": 2016,
      "enrolment_male": 37574,
      "enrolment_female": 40444,
      "enrolment_total": 78018,
      "dropout_male": 179,
      "dropout_female": 123,
      "dropout_total": 302
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "year": 2016,
      "enrolment_male": 10961,
      "enrolment_female": 10778,
      "enrolment_total": 21739,
      "dropout_male": 223,
      "dropout_female": 149,
      "dropout_total": 372
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "year": 2016,
      "enrolment_male": 28833,
      "enrolment_female": 27835,
      "enrolment_total": 56668,
      "dropout_male": 195,
      "dropout_female": 143,
      "dropout_total": 338
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "year": 2016,
      "enrolment_male": 29439,
      "enrolment_female": 29719,
      "enrolment_total": 59158,
      "dropout_male": 79,
      "dropout_female": 81,
      "dropout_total": 160
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "year": 2016,
      "enrolment_male": 30094,
      "enrolment_female": 31008,
      "enrolment_total": 61102,
      "dropout_male": 328,
      "dropout_female": 268,
      "dropout_total": 596
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "year": 2016,
      "enrolment_male": 13078,
      "enrolment_female": 13263,
      "enrolment_total": 26341,
      "dropout_male": 181,
      "dropout_female": 109,
      "dropout_total": 290
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "year": 2016,
      "enrolment_male": 22479,
      "enrolment_female": 23628,
      "enrolment_total": 46107,
      "dropout_male": 319,
      "dropout_female": 243,
      "dropout_total": 562
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "year": 2016,
      "enrolment_male": 9245,
      "enrolment_female": 9439,
      "enrolment_total": 18684,
      "dropout_male": 51,
      "dropout_female": 39,
      "dropout_total": 90
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "year": 2016,
      "enrolment_male": 12538,
      "enrolment_female": 13066,
      "enrolment_total": 25604,
      "dropout_male": 117,
      "dropout_female": 71,
      "dropout_total": 188
    },
    {
      "region": "Mtwara",
      "council": "Mtwara mikindani MC",
      "year": 2016,
      "enrolment_male": 9387,
      "enrolment_female": 9741,
      "enrolment_total": 19128,
      "dropout_male": 43,
      "dropout_female": 33,
      "dropout_total": 76
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "year": 2016,
      "enrolment_male": 10156,
      "enrolment_female": 10538,
      "enrolment_total": 20694,
      "dropout_male": 183,
      "dropout_female": 134,
      "dropout_total": 317
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "year": 2016,
      "enrolment_male": 15307,
      "enrolment_female": 15791,
      "enrolment_total": 31098,
      "dropout_male": 38,
      "dropout_female": 29,
      "dropout_total": 67
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "year": 2016,
      "enrolment_male": 9663,
      "enrolment_female": 10169,
      "enrolment_total": 19832,
      "dropout_male": 19,
      "dropout_female": 23,
      "dropout_total": 42
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "year": 2016,
      "enrolment_male": 8261,
      "enrolment_female": 8472,
      "enrolment_total": 16733,
      "dropout_male": 13,
      "dropout_female": 17,
      "dropout_total": 30
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "year": 2016,
      "enrolment_male": 23291,
      "enrolment_female": 23813,
      "enrolment_total": 47104,
      "dropout_male": 63,
      "dropout_female": 64,
      "dropout_total": 127
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "year": 2016,
      "enrolment_male": 40446,
      "enrolment_female": 40455,
      "enrolment_total": 80901,
      "dropout_male": 1692,
      "dropout_female": 1943,
      "dropout_total": 3635
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "year": 2016,
      "enrolment_male": 38455,
      "enrolment_female": 40480,
      "enrolment_total": 78935,
      "dropout_male": 312,
      "dropout_female": 329,
      "dropout_total": 641
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "year": 2016,
      "enrolment_male": 41629,
      "enrolment_female": 43052,
      "enrolment_total": 84681,
      "dropout_male": 1493,
      "dropout_female": 1145,
      "dropout_total": 2638
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "year": 2016,
      "enrolment_male": 35635,
      "enrolment_female": 37750,
      "enrolment_total": 73385,
      "dropout_male": 121,
      "dropout_female": 119,
      "dropout_total": 240
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "year": 2016,
      "enrolment_male": 36482,
      "enrolment_female": 38020,
      "enrolment_total": 74502,
      "dropout_male": 398,
      "dropout_female": 259,
      "dropout_total": 657
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "year": 2016,
      "enrolment_male": 43576,
      "enrolment_female": 46364,
      "enrolment_total": 89940,
      "dropout_male": 113,
      "dropout_female": 127,
      "dropout_total": 240
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "year": 2016,
      "enrolment_male": 40090,
      "enrolment_female": 41070,
      "enrolment_total": 81160,
      "dropout_male": 433,
      "dropout_female": 422,
      "dropout_total": 855
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "year": 2016,
      "enrolment_male": 43579,
      "enrolment_female": 43550,
      "enrolment_total": 87129,
      "dropout_male": 341,
      "dropout_female": 472,
      "dropout_total": 813
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "year": 2016,
      "enrolment_male": 14802,
      "enrolment_female": 15230,
      "enrolment_total": 30032,
      "dropout_male": 64,
      "dropout_female": 46,
      "dropout_total": 110
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "year": 2016,
      "enrolment_male": 10273,
      "enrolment_female": 11012,
      "enrolment_total": 21285,
      "dropout_male": 4,
      "dropout_female": 3,
      "dropout_total": 7
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "year": 2016,
      "enrolment_male": 9917,
      "enrolment_female": 9692,
      "enrolment_total": 19609,
      "dropout_male": 43,
      "dropout_female": 25,
      "dropout_total": 68
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "year": 2016,
      "enrolment_male": 8652,
      "enrolment_female": 9567,
      "enrolment_total": 18219,
      "dropout_male": 63,
      "dropout_female": 50,
      "dropout_total": 113
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "year": 2016,
      "enrolment_male": 16365,
      "enrolment_female": 16418,
      "enrolment_total": 32783,
      "dropout_male": 5,
      "dropout_female": 5,
      "dropout_total": 10
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "year": 2016,
      "enrolment_male": 16277,
      "enrolment_female": 17258,
      "enrolment_total": 33535,
      "dropout_male": 104,
      "dropout_female": 71,
      "dropout_total": 175
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "year": 2016,
      "enrolment_male": 10696,
      "enrolment_female": 10597,
      "enrolment_total": 21293,
      "dropout_male": 15,
      "dropout_female": 18,
      "dropout_total": 33
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "year": 2016,
      "enrolment_male": 21886,
      "enrolment_female": 22426,
      "enrolment_total": 44312,
      "dropout_male": 310,
      "dropout_female": 246,
      "dropout_total": 556
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "year": 2016,
      "enrolment_male": 7277,
      "enrolment_female": 7169,
      "enrolment_total": 14446,
      "dropout_male": 13,
      "dropout_female": 15,
      "dropout_total": 28
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "year": 2016,
      "enrolment_male": 13479,
      "enrolment_female": 13694,
      "enrolment_total": 27173,
      "dropout_male": 4,
      "dropout_female": 2,
      "dropout_total": 6
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 316,
      "dropout_female": 254,
      "dropout_total": 570
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "year": 2016,
      "enrolment_male": 12489,
      "enrolment_female": 12308,
      "enrolment_total": 24797,
      "dropout_male": 96,
      "dropout_female": 77,
      "dropout_total": 173
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "year": 2016,
      "enrolment_male": 4627,
      "enrolment_female": 4928,
      "enrolment_total": 9555,
      "dropout_male": 16,
      "dropout_female": 7,
      "dropout_total": 23
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "year": 2016,
      "enrolment_male": 30070,
      "enrolment_female": 30195,
      "enrolment_total": 60265,
      "dropout_male": 266,
      "dropout_female": 231,
      "dropout_total": 497
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "year": 2016,
      "enrolment_male": 26904,
      "enrolment_female": 26995,
      "enrolment_total": 53899,
      "dropout_male": 101,
      "dropout_female": 80,
      "dropout_total": 181
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "year": 2016,
      "enrolment_male": 23252,
      "enrolment_female": 23288,
      "enrolment_total": 46540,
      "dropout_male": 320,
      "dropout_female": 276,
      "dropout_total": 596
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "year": 2016,
      "enrolment_male": 30029,
      "enrolment_female": 31870,
      "enrolment_total": 61899,
      "dropout_male": 1801,
      "dropout_female": 1785,
      "dropout_total": 3586
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "year": 2016,
      "enrolment_male": 33650,
      "enrolment_female": 33995,
      "enrolment_total": 67645,
      "dropout_male": 521,
      "dropout_female": 430,
      "dropout_total": 951
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "year": 2016,
      "enrolment_male": 24313,
      "enrolment_female": 26677,
      "enrolment_total": 50990,
      "dropout_male": 294,
      "dropout_female": 224,
      "dropout_total": 518
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "year": 2016,
      "enrolment_male": 5079,
      "enrolment_female": 5061,
      "enrolment_total": 10140,
      "dropout_male": 12,
      "dropout_female": 12,
      "dropout_total": 24
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "year": 2016,
      "enrolment_male": 23171,
      "enrolment_female": 24642,
      "enrolment_total": 47813,
      "dropout_male": 15,
      "dropout_female": 15,
      "dropout_total": 30
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "year": 2016,
      "enrolment_male": 11343,
      "enrolment_female": 12396,
      "enrolment_total": 23739,
      "dropout_male": 49,
      "dropout_female": 28,
      "dropout_total": 77
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "year": 2016,
      "enrolment_male": 20993,
      "enrolment_female": 20878,
      "enrolment_total": 41871,
      "dropout_male": 63,
      "dropout_female": 47,
      "dropout_total": 110
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "year": 2016,
      "enrolment_male": 16281,
      "enrolment_female": 16400,
      "enrolment_total": 32681,
      "dropout_male": 24,
      "dropout_female": 16,
      "dropout_total": 40
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "year": 2016,
      "enrolment_male": 11883,
      "enrolment_female": 11916,
      "enrolment_total": 23799,
      "dropout_male": 12,
      "dropout_female": 16,
      "dropout_total": 28
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "year": 2016,
      "enrolment_male": 19917,
      "enrolment_female": 21164,
      "enrolment_total": 41081,
      "dropout_male": 7,
      "dropout_female": 9,
      "dropout_total": 16
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "year": 2016,
      "enrolment_male": 27913,
      "enrolment_female": 27876,
      "enrolment_total": 55789,
      "dropout_male": 117,
      "dropout_female": 76,
      "dropout_total": 193
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "year": 2016,
      "enrolment_male": 28540,
      "enrolment_female": 30050,
      "enrolment_total": 58590,
      "dropout_male": 97,
      "dropout_female": 51,
      "dropout_total": 148
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "year": 2016,
      "enrolment_male": 22004,
      "enrolment_female": 24214,
      "enrolment_total": 46218,
      "dropout_male": 351,
      "dropout_female": 272,
      "dropout_total": 623
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "year": 2016,
      "enrolment_male": 25059,
      "enrolment_female": 25869,
      "enrolment_total": 50928,
      "dropout_male": 613,
      "dropout_female": 542,
      "dropout_total": 1155
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "year": 2016,
      "enrolment_male": 30283,
      "enrolment_female": 32546,
      "enrolment_total": 62829,
      "dropout_male": 197,
      "dropout_female": 179,
      "dropout_total": 376
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "year": 2016,
      "enrolment_male": 17116,
      "enrolment_female": 17864,
      "enrolment_total": 34980,
      "dropout_male": 96,
      "dropout_female": 97,
      "dropout_total": 193
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "year": 2016,
      "enrolment_male": 27549,
      "enrolment_female": 28169,
      "enrolment_total": 55718,
      "dropout_male": 107,
      "dropout_female": 106,
      "dropout_total": 213
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "year": 2016,
      "enrolment_male": 26489,
      "enrolment_female": 28917,
      "enrolment_total": 55406,
      "dropout_male": 439,
      "dropout_female": 475,
      "dropout_total": 914
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "year": 2016,
      "enrolment_male": 16934,
      "enrolment_female": 18347,
      "enrolment_total": 35281,
      "dropout_male": 404,
      "dropout_female": 493,
      "dropout_total": 897
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "year": 2016,
      "enrolment_male": 28848,
      "enrolment_female": 29345,
      "enrolment_total": 58193,
      "dropout_male": 382,
      "dropout_female": 489,
      "dropout_total": 871
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "year": 2016,
      "enrolment_male": 29930,
      "enrolment_female": 32060,
      "enrolment_total": 61990,
      "dropout_male": 1076,
      "dropout_female": 731,
      "dropout_total": 1807
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "year": 2016,
      "enrolment_male": 32280,
      "enrolment_female": 34585,
      "enrolment_total": 66865,
      "dropout_male": 256,
      "dropout_female": 201,
      "dropout_total": 457
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "year": 2016,
      "enrolment_male": 27829,
      "enrolment_female": 30095,
      "enrolment_total": 57924,
      "dropout_male": 1375,
      "dropout_female": 1254,
      "dropout_total": 2629
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "year": 2016,
      "enrolment_male": 23671,
      "enrolment_female": 25841,
      "enrolment_total": 49512,
      "dropout_male": 385,
      "dropout_female": 248,
      "dropout_total": 633
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "year": 2016,
      "enrolment_male": 21995,
      "enrolment_female": 22085,
      "enrolment_total": 44080,
      "dropout_male": 186,
      "dropout_female": 134,
      "dropout_total": 320
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "year": 2016,
      "enrolment_male": 10706,
      "enrolment_female": 10349,
      "enrolment_total": 21055,
      "dropout_male": 546,
      "dropout_female": 431,
      "dropout_total": 977
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "year": 2016,
      "enrolment_male": 16039,
      "enrolment_female": 16760,
      "enrolment_total": 32799,
      "dropout_male": 1439,
      "dropout_female": 1148,
      "dropout_total": 2587
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "year": 2016,
      "enrolment_male": 18029,
      "enrolment_female": 19009,
      "enrolment_total": 37038,
      "dropout_male": 229,
      "dropout_female": 136,
      "dropout_total": 365
    },
    {
      "region": "Singida",
      "council": "Singida",
      "year": 2016,
      "enrolment_male": 21896,
      "enrolment_female": 23858,
      "enrolment_total": 45754,
      "dropout_male": 277,
      "dropout_female": 162,
      "dropout_total": 439
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "year": 2016,
      "enrolment_male": 14967,
      "enrolment_female": 16135,
      "enrolment_total": 31102,
      "dropout_male": 107,
      "dropout_female": 59,
      "dropout_total": 166
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "year": 2016,
      "enrolment_male": 11758,
      "enrolment_female": 12320,
      "enrolment_total": 24078,
      "dropout_male": 35,
      "dropout_female": 27,
      "dropout_total": 62
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "year": 2016,
      "enrolment_male": 44989,
      "enrolment_female": 47888,
      "enrolment_total": 92877,
      "dropout_male": 174,
      "dropout_female": 131,
      "dropout_total": 305
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "year": 2016,
      "enrolment_male": 16210,
      "enrolment_female": 16539,
      "enrolment_total": 32749,
      "dropout_male": 634,
      "dropout_female": 595,
      "dropout_total": 1229
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "year": 2016,
      "enrolment_male": null,
      "enrolment_female": null,
      "enrolment_total": null,
      "dropout_male": 651,
      "dropout_female": 631,
      "dropout_total": 1282
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "year": 2016,
      "enrolment_male": 14559,
      "enrolment_female": 15471,
      "enrolment_total": 30030,
      "dropout_male": 213,
      "dropout_female": 164,
      "dropout_total": 377
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "year": 2016,
      "enrolment_male": 37255,
      "enrolment_female": 39164,
      "enrolment_total": 76419,
      "dropout_male": 1163,
      "dropout_female": 943,
      "dropout_total": 2106
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "year": 2016,
      "enrolment_male": 35681,
      "enrolment_female": 33689,
      "enrolment_total": 69370,
      "dropout_male": 2515,
      "dropout_female": 2040,
      "dropout_total": 4555
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "year": 2016,
      "enrolment_male": 38719,
      "enrolment_female": 39386,
      "enrolment_total": 78105,
      "dropout_male": 1371,
      "dropout_female": 1008,
      "dropout_total": 2379
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "year": 2016,
      "enrolment_male": 8744,
      "enrolment_female": 9013,
      "enrolment_total": 17757,
      "dropout_male": 76,
      "dropout_female": 53,
      "dropout_total": 129
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "year": 2016,
      "enrolment_male": 18393,
      "enrolment_female": 17545,
      "enrolment_total": 35938,
      "dropout_male": 205,
      "dropout_female": 173,
      "dropout_total": 378
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "year": 2016,
      "enrolment_male": 24362,
      "enrolment_female": 24727,
      "enrolment_total": 49089,
      "dropout_male": 166,
      "dropout_female": 225,
      "dropout_total": 391
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "year": 2016,
      "enrolment_male": 37290,
      "enrolment_female": 36077,
      "enrolment_total": 73367,
      "dropout_male": 1456,
      "dropout_female": 1240,
      "dropout_total": 2696
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "year": 2016,
      "enrolment_male": 20615,
      "enrolment_female": 20167,
      "enrolment_total": 40782,
      "dropout_male": 703,
      "dropout_female": 514,
      "dropout_total": 1217
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "year": 2016,
      "enrolment_male": 18620,
      "enrolment_female": 18699,
      "enrolment_total": 37319,
      "dropout_male": 14,
      "dropout_female": 27,
      "dropout_total": 41
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "year": 2016,
      "enrolment_male": 30025,
      "enrolment_female": 29620,
      "enrolment_total": 59645,
      "dropout_male": 470,
      "dropout_female": 353,
      "dropout_total": 823
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "year": 2016,
      "enrolment_male": 8429,
      "enrolment_female": 8649,
      "enrolment_total": 17078,
      "dropout_male": 32,
      "dropout_female": 27,
      "dropout_total": 59
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "year": 2016,
      "enrolment_male": 23534,
      "enrolment_female": 23934,
      "enrolment_total": 47468,
      "dropout_male": 435,
      "dropout_female": 400,
      "dropout_total": 835
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "year": 2016,
      "enrolment_male": 26560,
      "enrolment_female": 25901,
      "enrolment_total": 52461,
      "dropout_male": 191,
      "dropout_female": 104,
      "dropout_total": 295
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "year": 2016,
      "enrolment_male": 6848,
      "enrolment_female": 6632,
      "enrolment_total": 13480,
      "dropout_male": 2,
      "dropout_female": 5,
      "dropout_total": 7
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "year": 2016,
      "enrolment_male": 40155,
      "enrolment_female": 42603,
      "enrolment_total": 82758,
      "dropout_male": 1002,
      "dropout_female": 698,
      "dropout_total": 1700
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "year": 2016,
      "enrolment_male": 12437,
      "enrolment_female": 12315,
      "enrolment_total": 24752,
      "dropout_male": 127,
      "dropout_female": 119,
      "dropout_total": 246
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "year": 2016,
      "enrolment_male": 20263,
      "enrolment_female": 20116,
      "enrolment_total": 40379,
      "dropout_male": 38,
      "dropout_female": 26,
      "dropout_total": 64
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "year": 2016,
      "enrolment_male": 5472,
      "enrolment_female": 5282,
      "enrolment_total": 10754,
      "dropout_male": 21,
      "dropout_female": 19,
      "dropout_total": 40
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "year": 2016,
      "enrolment_male": 27207,
      "enrolment_female": 27333,
      "enrolment_total": 54540,
      "dropout_male": 75,
      "dropout_female": 51,
      "dropout_total": 126
    },
    {
      "region": "Arusha",
      "council": "Arusha",
      "year": 2017,
      "enrolment_male": 31530,
      "enrolment_female": 33612,
      "enrolment_total": 65142,
      "dropout_male": 243,
      "dropout_female": 121,
      "dropout_total": 364
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "year": 2017,
      "enrolment_male": 42161,
      "enrolment_female": 42888,
      "enrolment_total": 85049,
      "dropout_male": 76,
      "dropout_female": 72,
      "dropout_total": 148
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "year": 2017,
      "enrolment_male": 22378,
      "enrolment_female": 22111,
      "enrolment_total": 44489,
      "dropout_male": 70,
      "dropout_female": 43,
      "dropout_total": 113
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "year": 2017,
      "enrolment_male": 9498,
      "enrolment_female": 7708,
      "enrolment_total": 17206,
      "dropout_male": 158,
      "dropout_female": 84,
      "dropout_total": 242
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "year": 2017,
      "enrolment_male": 27508,
      "enrolment_female": 26597,
      "enrolment_total": 54105,
      "dropout_male": 44,
      "dropout_female": 40,
      "dropout_total": 84
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "year": 2017,
      "enrolment_male": 14310,
      "enrolment_female": 14414,
      "enrolment_total": 28724,
      "dropout_male": 68,
      "dropout_female": 74,
      "dropout_total": 142
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "year": 2017,
      "enrolment_male": 16143,
      "enrolment_female": 12411,
      "enrolment_total": 28554,
      "dropout_male": 48,
      "dropout_female": 25,
      "dropout_total": 73
    },
    {
      "region": "Dar Es Salaam",
      "council": "Ilala MC",
      "year": 2017,
      "enrolment_male": 97007,
      "enrolment_female": 100323,
      "enrolment_total": 197330,
      "dropout_male": 43,
      "dropout_female": 30,
      "dropout_total": 73
    },
    {
      "region": "Dar Es Salaam",
      "council": "Kigamboni MC",
      "year": 2017,
      "enrolment_male": 14626,
      "enrolment_female": 14755,
      "enrolment_total": 29381,
      "dropout_male": 32,
      "dropout_female": 19,
      "dropout_total": 51
    },
    {
      "region": "Dar Es Salaam",
      "council": "Kinondoni MC",
      "year": 2017,
      "enrolment_male": 50706,
      "enrolment_female": 52008,
      "enrolment_total": 102714,
      "dropout_male": 95,
      "dropout_female": 77,
      "dropout_total": 172
    },
    {
      "region": "Dar Es Salaam",
      "council": "Temeke MC",
      "year": 2017,
      "enrolment_male": 80297,
      "enrolment_female": 83626,
      "enrolment_total": 163923,
      "dropout_male": 194,
      "dropout_female": 166,
      "dropout_total": 360
    },
    {
      "region": "Dar Es Salaam",
      "council": "Ubungo MC",
      "year": 2017,
      "enrolment_male": 49890,
      "enrolment_female": 50525,
      "enrolment_total": 100415,
      "dropout_male": 97,
      "dropout_female": 87,
      "dropout_total": 184
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "year": 2017,
      "enrolment_male": 17370,
      "enrolment_female": 18873,
      "enrolment_total": 36243,
      "dropout_male": 252,
      "dropout_female": 209,
      "dropout_total": 461
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "year": 2017,
      "enrolment_male": 31014,
      "enrolment_female": 33992,
      "enrolment_total": 65006,
      "dropout_male": 139,
      "dropout_female": 156,
      "dropout_total": 295
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "year": 2017,
      "enrolment_male": 24817,
      "enrolment_female": 26627,
      "enrolment_total": 51444,
      "dropout_male": 322,
      "dropout_female": 197,
      "dropout_total": 519
    },
    {
      "region": "Dodoma",
      "council": "Dodoma CC",
      "year": 2017,
      "enrolment_male": 43736,
      "enrolment_female": 45079,
      "enrolment_total": 88815,
      "dropout_male": 39,
      "dropout_female": 56,
      "dropout_total": 95
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "year": 2017,
      "enrolment_male": 22069,
      "enrolment_female": 23286,
      "enrolment_total": 45355,
      "dropout_male": 147,
      "dropout_female": 66,
      "dropout_total": 213
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "year": 2017,
      "enrolment_male": 6329,
      "enrolment_female": 6529,
      "enrolment_total": 12858,
      "dropout_male": 8,
      "dropout_female": 7,
      "dropout_total": 15
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "year": 2017,
      "enrolment_male": 32422,
      "enrolment_female": 36425,
      "enrolment_total": 68847,
      "dropout_male": 197,
      "dropout_female": 211,
      "dropout_total": 408
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "year": 2017,
      "enrolment_male": 30229,
      "enrolment_female": 34031,
      "enrolment_total": 64260,
      "dropout_male": 757,
      "dropout_female": 573,
      "dropout_total": 1330
    },
    {
      "region": "Geita",
      "council": " Nyang'hwale DC",
      "year": 2017,
      "enrolment_male": 33537,
      "enrolment_female": 33085,
      "enrolment_total": 66622,
      "dropout_male": 208,
      "dropout_female": 168,
      "dropout_total": 376
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "year": 2017,
      "enrolment_male": 52711,
      "enrolment_female": 51813,
      "enrolment_total": 104524,
      "dropout_male": 392,
      "dropout_female": 303,
      "dropout_total": 695
    },
    {
      "region": "Geita",
      "council": "Chato",
      "year": 2017,
      "enrolment_male": 90472,
      "enrolment_female": 90369,
      "enrolment_total": 180841,
      "dropout_male": 1410,
      "dropout_female": 1242,
      "dropout_total": 2652
    },
    {
      "region": "Geita",
      "council": "Geita",
      "year": 2017,
      "enrolment_male": 28701,
      "enrolment_female": 29724,
      "enrolment_total": 58425,
      "dropout_male": 1019,
      "dropout_female": 904,
      "dropout_total": 1923
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "year": 2017,
      "enrolment_male": 26195,
      "enrolment_female": 26448,
      "enrolment_total": 52643,
      "dropout_male": 110,
      "dropout_female": 133,
      "dropout_total": 243
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "year": 2017,
      "enrolment_male": 17519,
      "enrolment_female": 18097,
      "enrolment_total": 35616,
      "dropout_male": 460,
      "dropout_female": 429,
      "dropout_total": 889
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "year": 2017,
      "enrolment_male": 29954,
      "enrolment_female": 30434,
      "enrolment_total": 60388,
      "dropout_male": 58,
      "dropout_female": 41,
      "dropout_total": 99
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "year": 2017,
      "enrolment_male": 14451,
      "enrolment_female": 15134,
      "enrolment_total": 29585,
      "dropout_male": 3,
      "dropout_female": 2,
      "dropout_total": 5
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "year": 2017,
      "enrolment_male": 24488,
      "enrolment_female": 25294,
      "enrolment_total": 49782,
      "dropout_male": 100,
      "dropout_female": 51,
      "dropout_total": 151
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "year": 2017,
      "enrolment_male": 7781,
      "enrolment_female": 7863,
      "enrolment_total": 15644,
      "dropout_male": 7,
      "dropout_female": 6,
      "dropout_total": 13
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "year": 2017,
      "enrolment_male": 27736,
      "enrolment_female": 28648,
      "enrolment_total": 56384,
      "dropout_male": 147,
      "dropout_female": 72,
      "dropout_total": 219
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "year": 2017,
      "enrolment_male": 35809,
      "enrolment_female": 34919,
      "enrolment_total": 70728,
      "dropout_male": 2488,
      "dropout_female": 2035,
      "dropout_total": 4523
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "year": 2017,
      "enrolment_male": 31232,
      "enrolment_female": 31092,
      "enrolment_total": 62324,
      "dropout_male": 88,
      "dropout_female": 60,
      "dropout_total": 148
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "year": 2017,
      "enrolment_male": 11635,
      "enrolment_female": 11744,
      "enrolment_total": 23379,
      "dropout_male": 13,
      "dropout_female": 16,
      "dropout_total": 29
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "year": 2017,
      "enrolment_male": 30192,
      "enrolment_female": 31474,
      "enrolment_total": 61666,
      "dropout_male": 191,
      "dropout_female": 150,
      "dropout_total": 341
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "year": 2017,
      "enrolment_male": 32140,
      "enrolment_female": 33733,
      "enrolment_total": 65873,
      "dropout_male": 346,
      "dropout_female": 250,
      "dropout_total": 596
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "year": 2017,
      "enrolment_male": 20231,
      "enrolment_female": 20132,
      "enrolment_total": 40363,
      "dropout_male": 302,
      "dropout_female": 251,
      "dropout_total": 553
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "year": 2017,
      "enrolment_male": 61531,
      "enrolment_female": 62108,
      "enrolment_total": 123639,
      "dropout_male": 628,
      "dropout_female": 494,
      "dropout_total": 1122
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "year": 2017,
      "enrolment_male": 31195,
      "enrolment_female": 31390,
      "enrolment_total": 62585,
      "dropout_male": 269,
      "dropout_female": 206,
      "dropout_total": 475
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "year": 2017,
      "enrolment_male": 5102,
      "enrolment_female": 4654,
      "enrolment_total": 9756,
      "dropout_male": 110,
      "dropout_female": 88,
      "dropout_total": 198
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "year": 2017,
      "enrolment_male": 21686,
      "enrolment_female": 21081,
      "enrolment_total": 42767,
      "dropout_male": 100,
      "dropout_female": 87,
      "dropout_total": 187
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "year": 2017,
      "enrolment_male": 15955,
      "enrolment_female": 16387,
      "enrolment_total": 32342,
      "dropout_male": 34,
      "dropout_female": 19,
      "dropout_total": 53
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "year": 2017,
      "enrolment_male": 10259,
      "enrolment_female": 10049,
      "enrolment_total": 20308,
      "dropout_male": 73,
      "dropout_female": 71,
      "dropout_total": 144
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "year": 2017,
      "enrolment_male": 15582,
      "enrolment_female": 15318,
      "enrolment_total": 30900,
      "dropout_male": 185,
      "dropout_female": 148,
      "dropout_total": 333
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "year": 2017,
      "enrolment_male": 27547,
      "enrolment_female": 27486,
      "enrolment_total": 55033,
      "dropout_male": 327,
      "dropout_female": 217,
      "dropout_total": 544
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "year": 2017,
      "enrolment_male": 17088,
      "enrolment_female": 17062,
      "enrolment_total": 34150,
      "dropout_male": 59,
      "dropout_female": 33,
      "dropout_total": 92
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "year": 2017,
      "enrolment_male": 33493,
      "enrolment_female": 32431,
      "enrolment_total": 65924,
      "dropout_male": 413,
      "dropout_female": 396,
      "dropout_total": 809
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "year": 2017,
      "enrolment_male": 25295,
      "enrolment_female": 25546,
      "enrolment_total": 50841,
      "dropout_male": 24,
      "dropout_female": 27,
      "dropout_total": 51
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "year": 2017,
      "enrolment_male": 28174,
      "enrolment_female": 27487,
      "enrolment_total": 55661,
      "dropout_male": 204,
      "dropout_female": 175,
      "dropout_total": 379
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "year": 2017,
      "enrolment_male": 27213,
      "enrolment_female": 27040,
      "enrolment_total": 54253,
      "dropout_male": 66,
      "dropout_female": 62,
      "dropout_total": 128
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "year": 2017,
      "enrolment_male": 21345,
      "enrolment_female": 21330,
      "enrolment_total": 42675,
      "dropout_male": 113,
      "dropout_female": 96,
      "dropout_total": 209
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "year": 2017,
      "enrolment_male": 38950,
      "enrolment_female": 37774,
      "enrolment_total": 76724,
      "dropout_male": 635,
      "dropout_female": 558,
      "dropout_total": 1193
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "year": 2017,
      "enrolment_male": 17710,
      "enrolment_female": 17141,
      "enrolment_total": 34851,
      "dropout_male": 140,
      "dropout_female": 99,
      "dropout_total": 239
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "year": 2017,
      "enrolment_male": 35429,
      "enrolment_female": 34249,
      "enrolment_total": 69678,
      "dropout_male": 95,
      "dropout_female": 81,
      "dropout_total": 176
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "year": 2017,
      "enrolment_male": 13523,
      "enrolment_female": 13386,
      "enrolment_total": 26909,
      "dropout_male": 12,
      "dropout_female": 13,
      "dropout_total": 25
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "year": 2017,
      "enrolment_male": 11667,
      "enrolment_female": 11066,
      "enrolment_total": 22733,
      "dropout_male": 15,
      "dropout_female": 6,
      "dropout_total": 21
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "year": 2017,
      "enrolment_male": 24358,
      "enrolment_female": 23328,
      "enrolment_total": 47686,
      "dropout_male": 157,
      "dropout_female": 71,
      "dropout_total": 228
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "year": 2017,
      "enrolment_male": 26714,
      "enrolment_female": 25773,
      "enrolment_total": 52487,
      "dropout_male": 39,
      "dropout_female": 30,
      "dropout_total": 69
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "year": 2017,
      "enrolment_male": 9881,
      "enrolment_female": 9917,
      "enrolment_total": 19798,
      "dropout_male": 42,
      "dropout_female": 17,
      "dropout_total": 59
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "year": 2017,
      "enrolment_male": 22278,
      "enrolment_female": 22107,
      "enrolment_total": 44385,
      "dropout_male": 69,
      "dropout_female": 54,
      "dropout_total": 123
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "year": 2017,
      "enrolment_male": 18267,
      "enrolment_female": 18837,
      "enrolment_total": 37104,
      "dropout_male": 212,
      "dropout_female": 117,
      "dropout_total": 329
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "year": 2017,
      "enrolment_male": 7045,
      "enrolment_female": 7195,
      "enrolment_total": 14240,
      "dropout_male": 36,
      "dropout_female": 26,
      "dropout_total": 62
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "year": 2017,
      "enrolment_male": 10330,
      "enrolment_female": 10388,
      "enrolment_total": 20718,
      "dropout_male": 59,
      "dropout_female": 29,
      "dropout_total": 88
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "year": 2017,
      "enrolment_male": 16741,
      "enrolment_female": 16950,
      "enrolment_total": 33691,
      "dropout_male": 26,
      "dropout_female": 13,
      "dropout_total": 39
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "year": 2017,
      "enrolment_male": 12135,
      "enrolment_female": 12248,
      "enrolment_total": 24383,
      "dropout_male": 93,
      "dropout_female": 42,
      "dropout_total": 135
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "year": 2017,
      "enrolment_male": 32802,
      "enrolment_female": 33740,
      "enrolment_total": 66542,
      "dropout_male": 269,
      "dropout_female": 148,
      "dropout_total": 417
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "year": 2017,
      "enrolment_male": 9147,
      "enrolment_female": 9392,
      "enrolment_total": 18539,
      "dropout_male": 4,
      "dropout_female": 1,
      "dropout_total": 5
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "year": 2017,
      "enrolment_male": 29721,
      "enrolment_female": 30433,
      "enrolment_total": 60154,
      "dropout_male": 161,
      "dropout_female": 98,
      "dropout_total": 259
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "year": 2017,
      "enrolment_male": 19874,
      "enrolment_female": 19300,
      "enrolment_total": 39174,
      "dropout_male": 161,
      "dropout_female": 116,
      "dropout_total": 277
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "year": 2017,
      "enrolment_male": 16494,
      "enrolment_female": 17867,
      "enrolment_total": 34361,
      "dropout_male": 238,
      "dropout_female": 108,
      "dropout_total": 346
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "year": 2017,
      "enrolment_male": 11765,
      "enrolment_female": 12157,
      "enrolment_total": 23922,
      "dropout_male": 51,
      "dropout_female": 16,
      "dropout_total": 67
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "year": 2017,
      "enrolment_male": 17638,
      "enrolment_female": 15901,
      "enrolment_total": 33539,
      "dropout_male": 179,
      "dropout_female": 108,
      "dropout_total": 287
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "year": 2017,
      "enrolment_male": 30236,
      "enrolment_female": 29161,
      "enrolment_total": 59397,
      "dropout_male": 24,
      "dropout_female": 19,
      "dropout_total": 43
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "year": 2017,
      "enrolment_male": 21146,
      "enrolment_female": 20519,
      "enrolment_total": 41665,
      "dropout_male": 49,
      "dropout_female": 40,
      "dropout_total": 89
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "year": 2017,
      "enrolment_male": 31766,
      "enrolment_female": 30763,
      "enrolment_total": 62529,
      "dropout_male": 95,
      "dropout_female": 95,
      "dropout_total": 190
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "year": 2017,
      "enrolment_male": 29625,
      "enrolment_female": 28653,
      "enrolment_total": 58278,
      "dropout_male": 83,
      "dropout_female": 84,
      "dropout_total": 167
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "year": 2017,
      "enrolment_male": 18157,
      "enrolment_female": 19049,
      "enrolment_total": 37206,
      "dropout_male": 4,
      "dropout_female": 1,
      "dropout_total": 5
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "year": 2017,
      "enrolment_male": 40466,
      "enrolment_female": 39568,
      "enrolment_total": 80034,
      "dropout_male": 39,
      "dropout_female": 59,
      "dropout_total": 98
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "year": 2017,
      "enrolment_male": 38056,
      "enrolment_female": 35664,
      "enrolment_total": 73720,
      "dropout_male": 257,
      "dropout_female": 195,
      "dropout_total": 452
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "year": 2017,
      "enrolment_male": 43568,
      "enrolment_female": 41517,
      "enrolment_total": 85085,
      "dropout_male": 232,
      "dropout_female": 183,
      "dropout_total": 415
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "year": 2017,
      "enrolment_male": 13194,
      "enrolment_female": 13472,
      "enrolment_total": 26666,
      "dropout_male": 66,
      "dropout_female": 74,
      "dropout_total": 140
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "year": 2017,
      "enrolment_male": 10895,
      "enrolment_female": 10802,
      "enrolment_total": 21697,
      "dropout_male": 11,
      "dropout_female": 3,
      "dropout_total": 14
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "year": 2017,
      "enrolment_male": 14954,
      "enrolment_female": 15512,
      "enrolment_total": 30466,
      "dropout_male": 166,
      "dropout_female": 121,
      "dropout_total": 287
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "year": 2017,
      "enrolment_male": 24679,
      "enrolment_female": 24626,
      "enrolment_total": 49305,
      "dropout_male": 20,
      "dropout_female": 23,
      "dropout_total": 43
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "year": 2017,
      "enrolment_male": 28429,
      "enrolment_female": 29352,
      "enrolment_total": 57781,
      "dropout_male": 72,
      "dropout_female": 54,
      "dropout_total": 126
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "year": 2017,
      "enrolment_male": 33434,
      "enrolment_female": 34952,
      "enrolment_total": 68386,
      "dropout_male": 93,
      "dropout_female": 53,
      "dropout_total": 146
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "year": 2017,
      "enrolment_male": 38793,
      "enrolment_female": 40819,
      "enrolment_total": 79612,
      "dropout_male": 44,
      "dropout_female": 32,
      "dropout_total": 76
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "year": 2017,
      "enrolment_male": 26332,
      "enrolment_female": 26589,
      "enrolment_total": 52921,
      "dropout_male": 24,
      "dropout_female": 18,
      "dropout_total": 42
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "year": 2017,
      "enrolment_male": 14840,
      "enrolment_female": 17535,
      "enrolment_total": 32375,
      "dropout_male": 42,
      "dropout_female": 34,
      "dropout_total": 76
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "year": 2017,
      "enrolment_male": 11278,
      "enrolment_female": 11131,
      "enrolment_total": 22409,
      "dropout_male": 8,
      "dropout_female": 12,
      "dropout_total": 20
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "year": 2017,
      "enrolment_male": 33351,
      "enrolment_female": 32681,
      "enrolment_total": 66032,
      "dropout_male": 56,
      "dropout_female": 49,
      "dropout_total": 105
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "year": 2017,
      "enrolment_male": 40906,
      "enrolment_female": 43023,
      "enrolment_total": 83929,
      "dropout_male": 194,
      "dropout_female": 171,
      "dropout_total": 365
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "year": 2017,
      "enrolment_male": 11869,
      "enrolment_female": 11471,
      "enrolment_total": 23340,
      "dropout_male": 132,
      "dropout_female": 110,
      "dropout_total": 242
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "year": 2017,
      "enrolment_male": 29859,
      "enrolment_female": 28722,
      "enrolment_total": 58581,
      "dropout_male": 59,
      "dropout_female": 33,
      "dropout_total": 92
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "year": 2017,
      "enrolment_male": 31186,
      "enrolment_female": 31487,
      "enrolment_total": 62673,
      "dropout_male": 73,
      "dropout_female": 94,
      "dropout_total": 167
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "year": 2017,
      "enrolment_male": 32048,
      "enrolment_female": 32569,
      "enrolment_total": 64617,
      "dropout_male": 56,
      "dropout_female": 50,
      "dropout_total": 106
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "year": 2017,
      "enrolment_male": 14370,
      "enrolment_female": 14299,
      "enrolment_total": 28669,
      "dropout_male": 87,
      "dropout_female": 67,
      "dropout_total": 154
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "year": 2017,
      "enrolment_male": 24310,
      "enrolment_female": 25135,
      "enrolment_total": 49445,
      "dropout_male": 166,
      "dropout_female": 92,
      "dropout_total": 258
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "year": 2017,
      "enrolment_male": 9883,
      "enrolment_female": 10129,
      "enrolment_total": 20012,
      "dropout_male": 15,
      "dropout_female": 9,
      "dropout_total": 24
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "year": 2017,
      "enrolment_male": 13572,
      "enrolment_female": 13850,
      "enrolment_total": 27422,
      "dropout_male": 122,
      "dropout_female": 100,
      "dropout_total": 222
    },
    {
      "region": "Mtwara",
      "council": "Mtwara Mikindani MC",
      "year": 2017,
      "enrolment_male": 9967,
      "enrolment_female": 10187,
      "enrolment_total": 20154,
      "dropout_male": 8,
      "dropout_female": 9,
      "dropout_total": 17
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "year": 2017,
      "enrolment_male": 10980,
      "enrolment_female": 11123,
      "enrolment_total": 22103,
      "dropout_male": 92,
      "dropout_female": 48,
      "dropout_total": 140
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "year": 2017,
      "enrolment_male": 16385,
      "enrolment_female": 16622,
      "enrolment_total": 33007,
      "dropout_male": 57,
      "dropout_female": 42,
      "dropout_total": 99
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "year": 2017,
      "enrolment_male": 10398,
      "enrolment_female": 10672,
      "enrolment_total": 21070,
      "dropout_male": 15,
      "dropout_female": 10,
      "dropout_total": 25
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "year": 2017,
      "enrolment_male": 8881,
      "enrolment_female": 8932,
      "enrolment_total": 17813,
      "dropout_male": 53,
      "dropout_female": 28,
      "dropout_total": 81
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "year": 2017,
      "enrolment_male": 24959,
      "enrolment_female": 25209,
      "enrolment_total": 50168,
      "dropout_male": 57,
      "dropout_female": 40,
      "dropout_total": 97
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "year": 2017,
      "enrolment_male": 42917,
      "enrolment_female": 41859,
      "enrolment_total": 84776,
      "dropout_male": 1348,
      "dropout_female": 1159,
      "dropout_total": 2507
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "year": 2017,
      "enrolment_male": 40080,
      "enrolment_female": 41945,
      "enrolment_total": 82025,
      "dropout_male": 102,
      "dropout_female": 88,
      "dropout_total": 190
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "year": 2017,
      "enrolment_male": 46574,
      "enrolment_female": 47631,
      "enrolment_total": 94205,
      "dropout_male": 658,
      "dropout_female": 616,
      "dropout_total": 1274
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "year": 2017,
      "enrolment_male": 40232,
      "enrolment_female": 41757,
      "enrolment_total": 81989,
      "dropout_male": 49,
      "dropout_female": 40,
      "dropout_total": 89
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "year": 2017,
      "enrolment_male": 40773,
      "enrolment_female": 42078,
      "enrolment_total": 82851,
      "dropout_male": 322,
      "dropout_female": 303,
      "dropout_total": 625
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "year": 2017,
      "enrolment_male": 46268,
      "enrolment_female": 49026,
      "enrolment_total": 95294,
      "dropout_male": 131,
      "dropout_female": 104,
      "dropout_total": 235
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "year": 2017,
      "enrolment_male": 43700,
      "enrolment_female": 44369,
      "enrolment_total": 88069,
      "dropout_male": 156,
      "dropout_female": 130,
      "dropout_total": 286
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "year": 2017,
      "enrolment_male": 45349,
      "enrolment_female": 44728,
      "enrolment_total": 90077,
      "dropout_male": 120,
      "dropout_female": 121,
      "dropout_total": 241
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "year": 2017,
      "enrolment_male": 15069,
      "enrolment_female": 15479,
      "enrolment_total": 30548,
      "dropout_male": 35,
      "dropout_female": 18,
      "dropout_total": 53
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "year": 2017,
      "enrolment_male": 10947,
      "enrolment_female": 11744,
      "enrolment_total": 22691,
      "dropout_male": 25,
      "dropout_female": 7,
      "dropout_total": 32
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "year": 2017,
      "enrolment_male": 9778,
      "enrolment_female": 9444,
      "enrolment_total": 19222,
      "dropout_male": 13,
      "dropout_female": 8,
      "dropout_total": 21
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "year": 2017,
      "enrolment_male": 9006,
      "enrolment_female": 9841,
      "enrolment_total": 18847,
      "dropout_male": 20,
      "dropout_female": 9,
      "dropout_total": 29
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "year": 2017,
      "enrolment_male": 14686,
      "enrolment_female": 14958,
      "enrolment_total": 29644,
      "dropout_male": 11,
      "dropout_female": 13,
      "dropout_total": 24
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "year": 2017,
      "enrolment_male": 17393,
      "enrolment_female": 17905,
      "enrolment_total": 35298,
      "dropout_male": 34,
      "dropout_female": 23,
      "dropout_total": 57
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "year": 2017,
      "enrolment_male": 11966,
      "enrolment_female": 11638,
      "enrolment_total": 23604,
      "dropout_male": 77,
      "dropout_female": 71,
      "dropout_total": 148
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "year": 2017,
      "enrolment_male": 23804,
      "enrolment_female": 23838,
      "enrolment_total": 47642,
      "dropout_male": 85,
      "dropout_female": 65,
      "dropout_total": 150
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "year": 2017,
      "enrolment_male": 7923,
      "enrolment_female": 7912,
      "enrolment_total": 15835,
      "dropout_male": 8,
      "dropout_female": 11,
      "dropout_total": 19
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "year": 2017,
      "enrolment_male": 14767,
      "enrolment_female": 14850,
      "enrolment_total": 29617,
      "dropout_male": 15,
      "dropout_female": 17,
      "dropout_total": 32
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "year": 2017,
      "enrolment_male": 17026,
      "enrolment_female": 16510,
      "enrolment_total": 33536,
      "dropout_male": 135,
      "dropout_female": 68,
      "dropout_total": 203
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "year": 2017,
      "enrolment_male": 13258,
      "enrolment_female": 12812,
      "enrolment_total": 26070,
      "dropout_male": 114,
      "dropout_female": 86,
      "dropout_total": 200
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "year": 2017,
      "enrolment_male": 4924,
      "enrolment_female": 5051,
      "enrolment_total": 9975,
      "dropout_male": 9,
      "dropout_female": 18,
      "dropout_total": 27
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "year": 2017,
      "enrolment_male": 33115,
      "enrolment_female": 32737,
      "enrolment_total": 65852,
      "dropout_male": 105,
      "dropout_female": 100,
      "dropout_total": 205
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "year": 2017,
      "enrolment_male": 12925,
      "enrolment_female": 12616,
      "enrolment_total": 25541,
      "dropout_male": 23,
      "dropout_female": 18,
      "dropout_total": 41
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "year": 2017,
      "enrolment_male": 24429,
      "enrolment_female": 24770,
      "enrolment_total": 49199,
      "dropout_male": 441,
      "dropout_female": 359,
      "dropout_total": 800
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "year": 2017,
      "enrolment_male": 32947,
      "enrolment_female": 35007,
      "enrolment_total": 67954,
      "dropout_male": 1009,
      "dropout_female": 926,
      "dropout_total": 1935
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "year": 2017,
      "enrolment_male": 35802,
      "enrolment_female": 36420,
      "enrolment_total": 72222,
      "dropout_male": 466,
      "dropout_female": 437,
      "dropout_total": 903
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "year": 2017,
      "enrolment_male": 25133,
      "enrolment_female": 27411,
      "enrolment_total": 52544,
      "dropout_male": 210,
      "dropout_female": 186,
      "dropout_total": 396
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "year": 2017,
      "enrolment_male": 5250,
      "enrolment_female": 5138,
      "enrolment_total": 10388,
      "dropout_male": 7,
      "dropout_female": 6,
      "dropout_total": 13
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "year": 2017,
      "enrolment_male": 25812,
      "enrolment_female": 26156,
      "enrolment_total": 51968,
      "dropout_male": 6,
      "dropout_female": 8,
      "dropout_total": 14
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "year": 2017,
      "enrolment_male": 12657,
      "enrolment_female": 13552,
      "enrolment_total": 26209,
      "dropout_male": 31,
      "dropout_female": 16,
      "dropout_total": 47
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "year": 2017,
      "enrolment_male": 22504,
      "enrolment_female": 22219,
      "enrolment_total": 44723,
      "dropout_male": 33,
      "dropout_female": 60,
      "dropout_total": 93
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "year": 2017,
      "enrolment_male": 17972,
      "enrolment_female": 17591,
      "enrolment_total": 35563,
      "dropout_male": 29,
      "dropout_female": 18,
      "dropout_total": 47
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "year": 2017,
      "enrolment_male": 13110,
      "enrolment_female": 12934,
      "enrolment_total": 26044,
      "dropout_male": 27,
      "dropout_female": 14,
      "dropout_total": 41
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "year": 2017,
      "enrolment_male": 21865,
      "enrolment_female": 22854,
      "enrolment_total": 44719,
      "dropout_male": 42,
      "dropout_female": 40,
      "dropout_total": 82
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "year": 2017,
      "enrolment_male": 31281,
      "enrolment_female": 30827,
      "enrolment_total": 62108,
      "dropout_male": 120,
      "dropout_female": 120,
      "dropout_total": 240
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "year": 2017,
      "enrolment_male": 33436,
      "enrolment_female": 34620,
      "enrolment_total": 68056,
      "dropout_male": 185,
      "dropout_female": 143,
      "dropout_total": 328
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "year": 2017,
      "enrolment_male": 27793,
      "enrolment_female": 29170,
      "enrolment_total": 56963,
      "dropout_male": 505,
      "dropout_female": 367,
      "dropout_total": 872
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "year": 2017,
      "enrolment_male": 29061,
      "enrolment_female": 29814,
      "enrolment_total": 58875,
      "dropout_male": 622,
      "dropout_female": 602,
      "dropout_total": 1224
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "year": 2017,
      "enrolment_male": 35348,
      "enrolment_female": 37404,
      "enrolment_total": 72752,
      "dropout_male": 215,
      "dropout_female": 143,
      "dropout_total": 358
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "year": 2017,
      "enrolment_male": 19122,
      "enrolment_female": 19455,
      "enrolment_total": 38577,
      "dropout_male": 115,
      "dropout_female": 113,
      "dropout_total": 228
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "year": 2017,
      "enrolment_male": 32607,
      "enrolment_female": 33261,
      "enrolment_total": 65868,
      "dropout_male": 134,
      "dropout_female": 128,
      "dropout_total": 262
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "year": 2017,
      "enrolment_male": 31593,
      "enrolment_female": 33390,
      "enrolment_total": 64983,
      "dropout_male": 346,
      "dropout_female": 336,
      "dropout_total": 682
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "year": 2017,
      "enrolment_male": 20321,
      "enrolment_female": 21197,
      "enrolment_total": 41518,
      "dropout_male": 203,
      "dropout_female": 152,
      "dropout_total": 355
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "year": 2017,
      "enrolment_male": 30853,
      "enrolment_female": 30888,
      "enrolment_total": 61741,
      "dropout_male": 177,
      "dropout_female": 173,
      "dropout_total": 350
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "year": 2017,
      "enrolment_male": 35568,
      "enrolment_female": 37465,
      "enrolment_total": 73033,
      "dropout_male": 748,
      "dropout_female": 443,
      "dropout_total": 1191
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "year": 2017,
      "enrolment_male": 36085,
      "enrolment_female": 38119,
      "enrolment_total": 74204,
      "dropout_male": 302,
      "dropout_female": 374,
      "dropout_total": 676
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "year": 2017,
      "enrolment_male": 31644,
      "enrolment_female": 33358,
      "enrolment_total": 65002,
      "dropout_male": 490,
      "dropout_female": 381,
      "dropout_total": 871
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "year": 2017,
      "enrolment_male": 26625,
      "enrolment_female": 28653,
      "enrolment_total": 55278,
      "dropout_male": 162,
      "dropout_female": 105,
      "dropout_total": 267
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "year": 2017,
      "enrolment_male": 23987,
      "enrolment_female": 24276,
      "enrolment_total": 48263,
      "dropout_male": 118,
      "dropout_female": 82,
      "dropout_total": 200
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "year": 2017,
      "enrolment_male": 13168,
      "enrolment_female": 12439,
      "enrolment_total": 25607,
      "dropout_male": 112,
      "dropout_female": 110,
      "dropout_total": 222
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "year": 2017,
      "enrolment_male": 18828,
      "enrolment_female": 19461,
      "enrolment_total": 38289,
      "dropout_male": 568,
      "dropout_female": 479,
      "dropout_total": 1047
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "year": 2017,
      "enrolment_male": 20674,
      "enrolment_female": 21499,
      "enrolment_total": 42173,
      "dropout_male": 87,
      "dropout_female": 88,
      "dropout_total": 175
    },
    {
      "region": "Singida",
      "council": "Singida",
      "year": 2017,
      "enrolment_male": 25175,
      "enrolment_female": 26727,
      "enrolment_total": 51902,
      "dropout_male": 103,
      "dropout_female": 60,
      "dropout_total": 163
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "year": 2017,
      "enrolment_male": 16448,
      "enrolment_female": 17478,
      "enrolment_total": 33926,
      "dropout_male": 25,
      "dropout_female": 13,
      "dropout_total": 38
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "year": 2017,
      "enrolment_male": 11562,
      "enrolment_female": 12026,
      "enrolment_total": 23588,
      "dropout_male": 13,
      "dropout_female": 13,
      "dropout_total": 26
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "year": 2017,
      "enrolment_male": 47735,
      "enrolment_female": 50103,
      "enrolment_total": 97838,
      "dropout_male": 227,
      "dropout_female": 154,
      "dropout_total": 381
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "year": 2017,
      "enrolment_male": 18326,
      "enrolment_female": 18695,
      "enrolment_total": 37021,
      "dropout_male": 333,
      "dropout_female": 321,
      "dropout_total": 654
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "year": 2017,
      "enrolment_male": 11972,
      "enrolment_female": 12714,
      "enrolment_total": 24686,
      "dropout_male": 259,
      "dropout_female": 265,
      "dropout_total": 524
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "year": 2017,
      "enrolment_male": 15559,
      "enrolment_female": 15930,
      "enrolment_total": 31489,
      "dropout_male": 58,
      "dropout_female": 49,
      "dropout_total": 107
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "year": 2017,
      "enrolment_male": 38925,
      "enrolment_female": 41291,
      "enrolment_total": 80216,
      "dropout_male": 1194,
      "dropout_female": 1049,
      "dropout_total": 2243
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "year": 2017,
      "enrolment_male": 39153,
      "enrolment_female": 37331,
      "enrolment_total": 76484,
      "dropout_male": 1350,
      "dropout_female": 1186,
      "dropout_total": 2536
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "year": 2017,
      "enrolment_male": 40011,
      "enrolment_female": 41043,
      "enrolment_total": 81054,
      "dropout_male": 984,
      "dropout_female": 723,
      "dropout_total": 1707
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "year": 2017,
      "enrolment_male": 9297,
      "enrolment_female": 9601,
      "enrolment_total": 18898,
      "dropout_male": 77,
      "dropout_female": 72,
      "dropout_total": 149
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "year": 2017,
      "enrolment_male": 19456,
      "enrolment_female": 18665,
      "enrolment_total": 38121,
      "dropout_male": 206,
      "dropout_female": 147,
      "dropout_total": 353
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "year": 2017,
      "enrolment_male": 24567,
      "enrolment_female": 24464,
      "enrolment_total": 49031,
      "dropout_male": 19,
      "dropout_female": 23,
      "dropout_total": 42
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "year": 2017,
      "enrolment_male": 40435,
      "enrolment_female": 38627,
      "enrolment_total": 79062,
      "dropout_male": 1079,
      "dropout_female": 857,
      "dropout_total": 1936
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "year": 2017,
      "enrolment_male": 24457,
      "enrolment_female": 23493,
      "enrolment_total": 47950,
      "dropout_male": 217,
      "dropout_female": 211,
      "dropout_total": 428
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "year": 2017,
      "enrolment_male": 18767,
      "enrolment_female": 18363,
      "enrolment_total": 37130,
      "dropout_male": 29,
      "dropout_female": 25,
      "dropout_total": 54
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "year": 2017,
      "enrolment_male": 31927,
      "enrolment_female": 31305,
      "enrolment_total": 63232,
      "dropout_male": 365,
      "dropout_female": 272,
      "dropout_total": 637
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "year": 2017,
      "enrolment_male": 9119,
      "enrolment_female": 9256,
      "enrolment_total": 18375,
      "dropout_male": 21,
      "dropout_female": 27,
      "dropout_total": 48
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "year": 2017,
      "enrolment_male": 27124,
      "enrolment_female": 27027,
      "enrolment_total": 54151,
      "dropout_male": 32,
      "dropout_female": 34,
      "dropout_total": 66
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "year": 2017,
      "enrolment_male": 27828,
      "enrolment_female": 26830,
      "enrolment_total": 54658,
      "dropout_male": 60,
      "dropout_female": 32,
      "dropout_total": 92
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "year": 2017,
      "enrolment_male": 7437,
      "enrolment_female": 7094,
      "enrolment_total": 14531,
      "dropout_male": 14,
      "dropout_female": 23,
      "dropout_total": 37
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "year": 2017,
      "enrolment_male": 41223,
      "enrolment_female": 42951,
      "enrolment_total": 84174,
      "dropout_male": 202,
      "dropout_female": 120,
      "dropout_total": 322
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "year": 2017,
      "enrolment_male": 13217,
      "enrolment_female": 12687,
      "enrolment_total": 25904,
      "dropout_male": 95,
      "dropout_female": 69,
      "dropout_total": 164
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "year": 2017,
      "enrolment_male": 21054,
      "enrolment_female": 20558,
      "enrolment_total": 41612,
      "dropout_male": 53,
      "dropout_female": 39,
      "dropout_total": 92
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "year": 2017,
      "enrolment_male": 5880,
      "enrolment_female": 5606,
      "enrolment_total": 11486,
      "dropout_male": 24,
      "dropout_female": 25,
      "dropout_total": 49
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "year": 2017,
      "enrolment_male": 29076,
      "enrolment_female": 28499,
      "enrolment_total": 57575,
      "dropout_male": 50,
      "dropout_female": 49,
      "dropout_total": 99
    }
   ]