export const data = [
    {
       "year": "YEAR",
       "region": "region",
       "category": "Primary",
       "enrolment_male": 'Enrollment male',
       "enrolment_female": 'Enrollment female',
       "enrolment_total": 'Enrollment total',
       "dropout_male": 'Dropout male',
       "dropout_female": 'Dropout female',
       "dropout_total": "DROPOUT TOTAL",
       "PTR": 37,
       "PQTR": 38,
       "PCR": 45,
       "PLR": 45
     },
    
    {
       "year": 2012,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": 166237,
       "enrolment_female": 162138,
       "enrolment_total": 328375,
       "dropout_male": 1343,
       "dropout_female": 976,
       "dropout_total": 2319,
       "PTR": 37,
       "PQTR": 38,
       "PCR": 45,
       "PLR": 45
     },
    
     {
       "year": 2012,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": 166237,
       "enrolment_female": 162138,
       "enrolment_total": 328375,
       "dropout_male": 1343,
       "dropout_female": 976,
       "dropout_total": 2319,
       "PTR": 37,
       "PQTR": 38,
       "PCR": 45,
       "PLR": 45
     },
     {
       "year": 2012,
       "region": "Dar es salaam",
       "category": "Primary",
       "enrolment_male": 249801,
       "enrolment_female": 261043,
       "enrolment_total": 510844,
       "dropout_male": 907,
       "dropout_female": 714,
       "dropout_total": 1621,
       "PTR": 35,
       "PQTR": 36,
       "PCR": 65,
       "PLR": 70
     },
     {
       "year": 2012,
       "region": "Dodoma",
       "category": "Primary",
       "enrolment_male": 185496,
       "enrolment_female": 198816,
       "enrolment_total": 384312,
       "dropout_male": 2192,
       "dropout_female": 1694,
       "dropout_total": 3886,
       "PTR": 47,
       "PQTR": 49,
       "PCR": 72,
       "PLR": 62
     },
     {
       "year": 2012,
       "region": "Geita",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": null,
       "dropout_male": 1926,
       "dropout_female": 1779,
       "dropout_total": 3705,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2012,
       "region": "Iringa",
       "category": "Primary",
       "enrolment_male": 180514,
       "enrolment_female": 186538,
       "enrolment_total": 367052,
       "dropout_male": 149,
       "dropout_female": 97,
       "dropout_total": 246,
       "PTR": 42,
       "PQTR": 43,
       "PCR": 53,
       "PLR": 42
     },
     {
       "year": 2012,
       "region": "Kagera",
       "category": "Primary",
       "enrolment_male": 261349,
       "enrolment_female": 265866,
       "enrolment_total": 527215,
       "dropout_male": 2183,
       "dropout_female": 1931,
       "dropout_total": 4114,
       "PTR": 48,
       "PQTR": 50,
       "PCR": 75,
       "PLR": 60
     },
     {
       "year": 2012,
       "region": "Katavi",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": null,
       "dropout_male": 1470,
       "dropout_female": 1224,
       "dropout_total": 2694,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2012,
       "region": "Kigoma",
       "category": "Primary",
       "enrolment_male": 168898,
       "enrolment_female": 171069,
       "enrolment_total": 339967,
       "dropout_male": 2249,
       "dropout_female": 2229,
       "dropout_total": 4478,
       "PTR": 50,
       "PQTR": 53,
       "PCR": 77,
       "PLR": 70
     },
     {
       "year": 2012,
       "region": "Kilimanjaro",
       "category": "Primary",
       "enrolment_male": 149419,
       "enrolment_female": 147679,
       "enrolment_total": 297098,
       "dropout_male": 338,
       "dropout_female": 240,
       "dropout_total": 578,
       "PTR": 32,
       "PQTR": 33,
       "PCR": 42,
       "PLR": 28
     },
     {
       "year": 2012,
       "region": "Lindi",
       "category": "Primary",
       "enrolment_male": 78511,
       "enrolment_female": 81271,
       "enrolment_total": 159782,
       "dropout_male": 636,
       "dropout_female": 451,
       "dropout_total": 1087,
       "PTR": 49,
       "PQTR": 52,
       "PCR": 51,
       "PLR": 45
     },
     {
       "year": 2012,
       "region": "Manyara",
       "category": "Primary",
       "enrolment_male": 124618,
       "enrolment_female": 124969,
       "enrolment_total": 249587,
       "dropout_male": 3722,
       "dropout_female": 3246,
       "dropout_total": 6968,
       "PTR": 44,
       "PQTR": 44,
       "PCR": 60,
       "PLR": 34
     },
     {
       "year": 2012,
       "region": "Mara",
       "category": "Primary",
       "enrolment_male": 213355,
       "enrolment_female": 209713,
       "enrolment_total": 423068,
       "dropout_male": 805,
       "dropout_female": 689,
       "dropout_total": 1494,
       "PTR": 50,
       "PQTR": 52,
       "PCR": 79,
       "PLR": 62
     },
     {
       "year": 2012,
       "region": "Mbeya",
       "category": "Primary",
       "enrolment_male": 266346,
       "enrolment_female": 275118,
       "enrolment_total": 541464,
       "dropout_male": 1745,
       "dropout_female": 1108,
       "dropout_total": 2853,
       "PTR": 45,
       "PQTR": 48,
       "PCR": 76,
       "PLR": 52
     },
     {
       "year": 2012,
       "region": "Morogoro",
       "category": "Primary",
       "enrolment_male": 196122,
       "enrolment_female": 202040,
       "enrolment_total": 398162,
       "dropout_male": 1645,
       "dropout_female": 1328,
       "dropout_total": 2973,
       "PTR": 41,
       "PQTR": 42,
       "PCR": 71,
       "PLR": 53
     },
     {
       "year": 2012,
       "region": "Mtwara",
       "category": "Primary",
       "enrolment_male": 116174,
       "enrolment_female": 120962,
       "enrolment_total": 237136,
       "dropout_male": 1241,
       "dropout_female": 837,
       "dropout_total": 2078,
       "PTR": 46,
       "PQTR": 49,
       "PCR": 59,
       "PLR": 57
     },
     {
       "year": 2012,
       "region": "Mwanza",
       "category": "Primary",
       "enrolment_male": 435165,
       "enrolment_female": 443394,
       "enrolment_total": 878559,
       "dropout_male": 3080,
       "dropout_female": 2653,
       "dropout_total": 5733,
       "PTR": 52,
       "PQTR": 53,
       "PCR": 93,
       "PLR": 77
     },
     {
       "year": 2012,
       "region": "Njombe",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": null,
       "dropout_male": 62,
       "dropout_female": 53,
       "dropout_total": 115,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2012,
       "region": "Pwani",
       "category": "Primary",
       "enrolment_male": 109416,
       "enrolment_female": 111494,
       "enrolment_total": 220910,
       "dropout_male": 945,
       "dropout_female": 684,
       "dropout_total": 1629,
       "PTR": 40,
       "PQTR": 40,
       "PCR": 53,
       "PLR": 44
     },
     {
       "year": 2012,
       "region": "Rukwa",
       "category": "Primary",
       "enrolment_male": 139073,
       "enrolment_female": 141231,
       "enrolment_total": 280304,
       "dropout_male": 866,
       "dropout_female": 769,
       "dropout_total": 1635,
       "PTR": 49,
       "PQTR": 51,
       "PCR": 80,
       "PLR": 51
     },
     {
       "year": 2012,
       "region": "Ruvuma",
       "category": "Primary",
       "enrolment_male": 145031,
       "enrolment_female": 145041,
       "enrolment_total": 290072,
       "dropout_male": 266,
       "dropout_female": 269,
       "dropout_total": 535,
       "PTR": 48,
       "PQTR": 49,
       "PCR": 56,
       "PLR": 50
     },
     {
       "year": 2012,
       "region": "Shinyanga",
       "category": "Primary",
       "enrolment_male": 324049,
       "enrolment_female": 338750,
       "enrolment_total": 662799,
       "dropout_male": 1395,
       "dropout_female": 1131,
       "dropout_total": 2526,
       "PTR": 49,
       "PQTR": 49,
       "PCR": 77,
       "PLR": 77
     },
     {
       "year": 2012,
       "region": "Simiyu",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": null,
       "dropout_male": 2172,
       "dropout_female": 1851,
       "dropout_total": 4023,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2012,
       "region": "Singida",
       "category": "Primary",
       "enrolment_male": 124926,
       "enrolment_female": 126755,
       "enrolment_total": 251681,
       "dropout_male": 2094,
       "dropout_female": 1726,
       "dropout_total": 3820,
       "PTR": 70,
       "PQTR": 71,
       "PCR": 112,
       "PLR": 85
     },
     {
       "year": 2012,
       "region": "Tabora",
       "category": "Primary",
       "enrolment_male": 211680,
       "enrolment_female": 206371,
       "enrolment_total": 418051,
       "dropout_male": 3086,
       "dropout_female": 2784,
       "dropout_total": 5870,
       "PTR": 56,
       "PQTR": 59,
       "PCR": 88,
       "PLR": 69
     },
     {
       "year": 2012,
       "region": "Tanga",
       "category": "Primary",
       "enrolment_male": 240100,
       "enrolment_female": 240634,
       "enrolment_total": 480734,
       "dropout_male": 1684,
       "dropout_female": 1493,
       "dropout_total": 3177,
       "PTR": 46,
       "PQTR": 53,
       "PCR": 75,
       "PLR": 49
     },
     {
       "year": 2013,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": 161019,
       "enrolment_female": 157546,
       "enrolment_total": 318565,
       "dropout_male": 1149,
       "dropout_female": 866,
       "dropout_total": 2015,
       "PTR": 35,
       "PQTR": 36,
       "PCR": 54,
       "PLR": 42
     },
     {
       "year": 2013,
       "region": "Dar es salaam",
       "category": "Primary",
       "enrolment_male": 222733,
       "enrolment_female": 227276,
       "enrolment_total": 450009,
       "dropout_male": 938,
       "dropout_female": 815,
       "dropout_total": 1753,
       "PTR": 31,
       "PQTR": 32,
       "PCR": 72,
       "PLR": 64
     },
     {
       "year": 2013,
       "region": "Dodoma",
       "category": "Primary",
       "enrolment_male": 188822,
       "enrolment_female": 200474,
       "enrolment_total": 389296,
       "dropout_male": 1585,
       "dropout_female": 3240,
       "dropout_total": 4825,
       "PTR": 46,
       "PQTR": 47,
       "PCR": 75,
       "PLR": 57
     },
     {
       "year": 2013,
       "region": "Geita",
       "category": "Primary",
       "enrolment_male": 218850,
       "enrolment_female": 219199,
       "enrolment_total": 438049,
       "dropout_male": 751,
       "dropout_female": 668,
       "dropout_total": 1419,
       "PTR": 59,
       "PQTR": 59,
       "PCR": 126,
       "PLR": 107
     },
     {
       "year": 2013,
       "region": "Iringa",
       "category": "Primary",
       "enrolment_male": 104574,
       "enrolment_female": 112667,
       "enrolment_total": 217241,
       "dropout_male": 288,
       "dropout_female": 182,
       "dropout_total": 470,
       "PTR": 41,
       "PQTR": 42,
       "PCR": 61,
       "PLR": 36
     },
     {
       "year": 2013,
       "region": "Kagera",
       "category": "Primary",
       "enrolment_male": 228849,
       "enrolment_female": 236919,
       "enrolment_total": 465768,
       "dropout_male": 1820,
       "dropout_female": 1584,
       "dropout_total": 3404,
       "PTR": 47,
       "PQTR": 49,
       "PCR": 75,
       "PLR": 55
     },
     {
       "year": 2013,
       "region": "Katavi",
       "category": "Primary",
       "enrolment_male": 46277,
       "enrolment_female": 46105,
       "enrolment_total": 92382,
       "dropout_male": 1336,
       "dropout_female": 1056,
       "dropout_total": 2392,
       "PTR": 35,
       "PQTR": 35,
       "PCR": 88,
       "PLR": 61
     },
     {
       "year": 2013,
       "region": "Kigoma",
       "category": "Primary",
       "enrolment_male": 168594,
       "enrolment_female": 169284,
       "enrolment_total": 337878,
       "dropout_male": 1858,
       "dropout_female": 1559,
       "dropout_total": 3417,
       "PTR": 48,
       "PQTR": 48,
       "PCR": 85,
       "PLR": 73
     },
     {
       "year": 2013,
       "region": "Kilimanjaro",
       "category": "Primary",
       "enrolment_male": 147704,
       "enrolment_female": 144765,
       "enrolment_total": 292469,
       "dropout_male": 269,
       "dropout_female": 162,
       "dropout_total": 431,
       "PTR": 32,
       "PQTR": 32,
       "PCR": 43,
       "PLR": 26
     },
     {
       "year": 2013,
       "region": "Lindi",
       "category": "Primary",
       "enrolment_male": 78780,
       "enrolment_female": 81832,
       "enrolment_total": 160612,
       "dropout_male": 660,
       "dropout_female": 596,
       "dropout_total": 1256,
       "PTR": 46,
       "PQTR": 46,
       "PCR": 50,
       "PLR": 47
     },
     {
       "year": 2013,
       "region": "Manyara",
       "category": "Primary",
       "enrolment_male": 122431,
       "enrolment_female": 123861,
       "enrolment_total": 246292,
       "dropout_male": 2176,
       "dropout_female": 1204,
       "dropout_total": 3380,
       "PTR": 42,
       "PQTR": 42,
       "PCR": 54,
       "PLR": 35
     },
     {
       "year": 2013,
       "region": "Mara",
       "category": "Primary",
       "enrolment_male": 217570,
       "enrolment_female": 214492,
       "enrolment_total": 432062,
       "dropout_male": 1062,
       "dropout_female": 988,
       "dropout_total": 2050,
       "PTR": 50,
       "PQTR": 50,
       "PCR": 76,
       "PLR": 58
     },
     {
       "year": 2013,
       "region": "Mbeya",
       "category": "Primary",
       "enrolment_male": 259505,
       "enrolment_female": 269842,
       "enrolment_total": 529347,
       "dropout_male": 1370,
       "dropout_female": 963,
       "dropout_total": 2333,
       "PTR": 42,
       "PQTR": 42,
       "PCR": 76,
       "PLR": 46
     },
     {
       "year": 2013,
       "region": "Morogoro",
       "category": "Primary",
       "enrolment_male": 190203,
       "enrolment_female": 196868,
       "enrolment_total": 387071,
       "dropout_male": 870,
       "dropout_female": 717,
       "dropout_total": 1587,
       "PTR": 40,
       "PQTR": 40,
       "PCR": 72,
       "PLR": 54
     },
     {
       "year": 2013,
       "region": "Mtwara",
       "category": "Primary",
       "enrolment_male": 115213,
       "enrolment_female": 120647,
       "enrolment_total": 235860,
       "dropout_male": 1024,
       "dropout_female": 622,
       "dropout_total": 1646,
       "PTR": 44,
       "PQTR": 45,
       "PCR": 60,
       "PLR": 47
     },
     {
       "year": 2013,
       "region": "Mwanza",
       "category": "Primary",
       "enrolment_male": 295908,
       "enrolment_female": 305832,
       "enrolment_total": 601740,
       "dropout_male": 1984,
       "dropout_female": 1626,
       "dropout_total": 3610,
       "PTR": 48,
       "PQTR": 48,
       "PCR": 110,
       "PLR": 77
     },
     {
       "year": 2013,
       "region": "Njombe",
       "category": "Primary",
       "enrolment_male": 77145,
       "enrolment_female": 79540,
       "enrolment_total": 156685,
       "dropout_male": 48,
       "dropout_female": 27,
       "dropout_total": 75,
       "PTR": 43,
       "PQTR": 44,
       "PCR": 48,
       "PLR": 40
     },
     {
       "year": 2013,
       "region": "Pwani",
       "category": "Primary",
       "enrolment_male": 109272,
       "enrolment_female": 111768,
       "enrolment_total": 221040,
       "dropout_male": 793,
       "dropout_female": 695,
       "dropout_total": 1488,
       "PTR": 39,
       "PQTR": 39,
       "PCR": 66,
       "PLR": 45
     },
     {
       "year": 2013,
       "region": "Rukwa",
       "category": "Primary",
       "enrolment_male": 101084,
       "enrolment_female": 101341,
       "enrolment_total": 202425,
       "dropout_male": 775,
       "dropout_female": 710,
       "dropout_total": 1485,
       "PTR": 49,
       "PQTR": 49,
       "PCR": 184,
       "PLR": 58
     },
     {
       "year": 2013,
       "region": "Ruvuma",
       "category": "Primary",
       "enrolment_male": 133308,
       "enrolment_female": 137410,
       "enrolment_total": 270718,
       "dropout_male": 231,
       "dropout_female": 208,
       "dropout_total": 439,
       "PTR": 43,
       "PQTR": 44,
       "PCR": 53,
       "PLR": 40
     },
     {
       "year": 2013,
       "region": "Shinyanga",
       "category": "Primary",
       "enrolment_male": 144020,
       "enrolment_female": 150768,
       "enrolment_total": 294788,
       "dropout_male": 771,
       "dropout_female": 643,
       "dropout_total": 1414,
       "PTR": 45,
       "PQTR": 45,
       "PCR": 65,
       "PLR": 70
     },
     {
       "year": 2013,
       "region": "Simiyu",
       "category": "Primary",
       "enrolment_male": 156325,
       "enrolment_female": 169340,
       "enrolment_total": 325665,
       "dropout_male": 3301,
       "dropout_female": 2711,
       "dropout_total": 6012,
       "PTR": 50,
       "PQTR": 50,
       "PCR": 89,
       "PLR": 85
     },
     {
       "year": 2013,
       "region": "Singida",
       "category": "Primary",
       "enrolment_male": 125977,
       "enrolment_female": 128956,
       "enrolment_total": 254933,
       "dropout_male": 1747,
       "dropout_female": 1335,
       "dropout_total": 3082,
       "PTR": 46,
       "PQTR": 46,
       "PCR": 65,
       "PLR": 44
     },
     {
       "year": 2013,
       "region": "Tabora",
       "category": "Primary",
       "enrolment_male": 207339,
       "enrolment_female": 206722,
       "enrolment_total": 414061,
       "dropout_male": 2066,
       "dropout_female": 1696,
       "dropout_total": 3762,
       "PTR": 52,
       "PQTR": 53,
       "PCR": 84,
       "PLR": 66
     },
     {
       "year": 2013,
       "region": "Tanga",
       "category": "Primary",
       "enrolment_male": 217618,
       "enrolment_female": 220810,
       "enrolment_total": 438428,
       "dropout_male": 1503,
       "dropout_female": 1325,
       "dropout_total": 2828,
       "PTR": 44,
       "PQTR": 44,
       "PCR": 67,
       "PLR": 42
     },
     {
       "year": 2015,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": 153024,
       "enrolment_female": 150484,
       "enrolment_total": 303508,
       "dropout_male": 1456,
       "dropout_female": 835,
       "dropout_total": 2291,
       "PTR": 31,
       "PQTR": 32,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Dodoma",
       "category": "Primary",
       "enrolment_male": 178462,
       "enrolment_female": 197534,
       "enrolment_total": 375996,
       "dropout_male": 752,
       "dropout_female": 593,
       "dropout_total": 1345,
       "PTR": 43,
       "PQTR": 43,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Dar es salaam",
       "category": "Primary",
       "enrolment_male": 267237,
       "enrolment_female": 280452,
       "enrolment_total": 547689,
       "dropout_male": 2858,
       "dropout_female": 2150,
       "dropout_total": 5009,
       "PTR": 35,
       "PQTR": 35,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Geita",
       "category": "Primary",
       "enrolment_male": 198896,
       "enrolment_female": 201140,
       "enrolment_total": 400036,
       "dropout_male": 4974,
       "dropout_female": 5070,
       "dropout_total": 10044,
       "PTR": 51,
       "PQTR": 51,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Iringa",
       "category": "Primary",
       "enrolment_male": 95042,
       "enrolment_female": 100013,
       "enrolment_total": 195055,
       "dropout_male": 276,
       "dropout_female": 147,
       "dropout_total": 423,
       "PTR": 35,
       "PQTR": 35,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Kagera",
       "category": "Primary",
       "enrolment_male": 214654,
       "enrolment_female": 221609,
       "enrolment_total": 436263,
       "dropout_male": 4207,
       "dropout_female": 3789,
       "dropout_total": 7996,
       "PTR": 43,
       "PQTR": 44,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Katavi",
       "category": "Primary",
       "enrolment_male": 50871,
       "enrolment_female": 49580,
       "enrolment_total": 100451,
       "dropout_male": 818,
       "dropout_female": 814,
       "dropout_total": 1632,
       "PTR": 45,
       "PQTR": 45,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Kigoma",
       "category": "Primary",
       "enrolment_male": 170346,
       "enrolment_female": 171427,
       "enrolment_total": 341773,
       "dropout_male": 1483,
       "dropout_female": 1309,
       "dropout_total": 2792,
       "PTR": 46,
       "PQTR": 46,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Kilimanjaro",
       "category": "Primary",
       "enrolment_male": 139135,
       "enrolment_female": 137274,
       "enrolment_total": 276409,
       "dropout_male": 335,
       "dropout_female": 228,
       "dropout_total": 563,
       "PTR": 30,
       "PQTR": 30,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Lindi",
       "category": "Primary",
       "enrolment_male": 75715,
       "enrolment_female": 78718,
       "enrolment_total": 154433,
       "dropout_male": 1403,
       "dropout_female": 1028,
       "dropout_total": 2431,
       "PTR": 39,
       "PQTR": 40,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Manyara",
       "category": "Primary",
       "enrolment_male": 121266,
       "enrolment_female": 124825,
       "enrolment_total": 246091,
       "dropout_male": 1840,
       "dropout_female": 1046,
       "dropout_total": 2886,
       "PTR": 38,
       "PQTR": 38,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Mara",
       "category": "Primary",
       "enrolment_male": 222438,
       "enrolment_female": 219063,
       "enrolment_total": 441501,
       "dropout_male": 992,
       "dropout_female": 925,
       "dropout_total": 1917,
       "PTR": 51,
       "PQTR": 51,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Mbeya",
       "category": "Primary",
       "enrolment_male": 175225,
       "enrolment_female": 183136,
       "enrolment_total": 358361,
       "dropout_male": 882,
       "dropout_female": 592,
       "dropout_total": 1474,
       "PTR": 28,
       "PQTR": 28,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Morogoro",
       "category": "Primary",
       "enrolment_male": 194775,
       "enrolment_female": 200803,
       "enrolment_total": 395578,
       "dropout_male": 1249,
       "dropout_female": 995,
       "dropout_total": 2244,
       "PTR": 38,
       "PQTR": 38,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Mtwara",
       "category": "Primary",
       "enrolment_male": 112806,
       "enrolment_female": 119201,
       "enrolment_total": 232007,
       "dropout_male": 739,
       "dropout_female": 446,
       "dropout_total": 1185,
       "PTR": 40,
       "PQTR": 40,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Mwanza",
       "category": "Primary",
       "enrolment_male": 305918,
       "enrolment_female": 318579,
       "enrolment_total": 624497,
       "dropout_male": 1686,
       "dropout_female": 1610,
       "dropout_total": 3296,
       "PTR": 45,
       "PQTR": 46,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Njombe",
       "category": "Primary",
       "enrolment_male": 71314,
       "enrolment_female": 75135,
       "enrolment_total": 146449,
       "dropout_male": 71,
       "dropout_female": 55,
       "dropout_total": 126,
       "PTR": 36,
       "PQTR": 37,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Pwani",
       "category": "Primary",
       "enrolment_male": 114810,
       "enrolment_female": 117192,
       "enrolment_total": 232002,
       "dropout_male": 1415,
       "dropout_female": 998,
       "dropout_total": 2413,
       "PTR": 36,
       "PQTR": 36,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Rukwa",
       "category": "Primary",
       "enrolment_male": 97097,
       "enrolment_female": 101029,
       "enrolment_total": 198126,
       "dropout_male": 1261,
       "dropout_female": 1248,
       "dropout_total": 2509,
       "PTR": 44,
       "PQTR": 44,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Ruvuma",
       "category": "Primary",
       "enrolment_male": 128187,
       "enrolment_female": 134254,
       "enrolment_total": 262441,
       "dropout_male": 255,
       "dropout_female": 208,
       "dropout_total": 463,
       "PTR": 40,
       "PQTR": 40,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Shinyanga",
       "category": "Primary",
       "enrolment_male": 134341,
       "enrolment_female": 143605,
       "enrolment_total": 277946,
       "dropout_male": 1560,
       "dropout_female": 1377,
       "dropout_total": 2937,
       "PTR": 42,
       "PQTR": 44,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Simiyu",
       "category": "Primary",
       "enrolment_male": 154826,
       "enrolment_female": 166472,
       "enrolment_total": 321298,
       "dropout_male": 3769,
       "dropout_female": 3350,
       "dropout_total": 7121,
       "PTR": 47,
       "PQTR": 47,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Singida",
       "category": "Primary",
       "enrolment_male": 119514,
       "enrolment_female": 127298,
       "enrolment_total": 246812,
       "dropout_male": 2073,
       "dropout_female": 1541,
       "dropout_total": 3614,
       "PTR": 46,
       "PQTR": 46,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Songwe",
       "category": "Primary",
       "enrolment_male": 81703,
       "enrolment_female": 86493,
       "enrolment_total": 168196,
       "dropout_male": 499,
       "dropout_female": 433,
       "dropout_total": 932,
       "PTR": 51,
       "PQTR": 51,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Tabora",
       "category": "Primary",
       "enrolment_male": 206718,
       "enrolment_female": 204837,
       "enrolment_total": 411555,
       "dropout_male": 5190,
       "dropout_female": 4559,
       "dropout_total": 9749,
       "PTR": 41,
       "PQTR": 41,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2015,
       "region": "Tanga",
       "category": "Primary",
       "enrolment_male": 208598,
       "enrolment_female": 213544,
       "enrolment_total": 422142,
       "dropout_male": 4699,
       "dropout_female": 3897,
       "dropout_total": 8596,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2016,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": 152329,
       "enrolment_female": 150804,
       "enrolment_total": 323269,
       "dropout_male": 1335,
       "dropout_female": 926,
       "dropout_total": 2261,
       "PTR": 31,
       "PQTR": 33,
       "PCR": 53,
       "PLR": 35
     },
     {
       "year": 2016,
       "region": "Dar es salaam",
       "category": "Primary",
       "enrolment_male": 279593,
       "enrolment_female": 292931,
       "enrolment_total": 593763,
       "dropout_male": 728,
       "dropout_female": 733,
       "dropout_total": 1461,
       "PTR": 33,
       "PQTR": 35,
       "PCR": 74,
       "PLR": 63
     },
     {
       "year": 2016,
       "region": "Dodoma",
       "category": "Primary",
       "enrolment_male": 186113,
       "enrolment_female": 206441,
       "enrolment_total": 432828,
       "dropout_male": 2825,
       "dropout_female": 2300,
       "dropout_total": 5125,
       "PTR": 44,
       "PQTR": 46,
       "PCR": 77,
       "PLR": 57
     },
     {
       "year": 2016,
       "region": "Geita",
       "category": "Primary",
       "enrolment_male": 222762,
       "enrolment_female": 223586,
       "enrolment_total": 498671,
       "dropout_male": 7872,
       "dropout_female": 7425,
       "dropout_total": 15297,
       "PTR": 47,
       "PQTR": 48,
       "PCR": 116,
       "PLR": 100
     },
     {
       "year": 2016,
       "region": "Iringa",
       "category": "Primary",
       "enrolment_male": 99033,
       "enrolment_female": 103080,
       "enrolment_total": 211783,
       "dropout_male": 761,
       "dropout_female": 393,
       "dropout_total": 1154,
       "PTR": 36,
       "PQTR": 37,
       "PCR": 53,
       "PLR": 31
     },
     {
       "year": 2016,
       "region": "Kagera",
       "category": "Primary",
       "enrolment_male": 230641,
       "enrolment_female": 234717,
       "enrolment_total": 510557,
       "dropout_male": 4763,
       "dropout_female": 4061,
       "dropout_total": 8824,
       "PTR": 42,
       "PQTR": 43,
       "PCR": 76,
       "PLR": 55
     },
     {
       "year": 2016,
       "region": "Katavi",
       "category": "Primary",
       "enrolment_male": 57678,
       "enrolment_female": 57526,
       "enrolment_total": 136073,
       "dropout_male": 751,
       "dropout_female": 643,
       "dropout_total": 1394,
       "PTR": 51,
       "PQTR": 51,
       "PCR": 102,
       "PLR": 70
     },
     {
       "year": 2016,
       "region": "Kigoma",
       "category": "Primary",
       "enrolment_male": 194498,
       "enrolment_female": 193102,
       "enrolment_total": 431070,
       "dropout_male": 2829,
       "dropout_female": 2405,
       "dropout_total": 5234,
       "PTR": 51,
       "PQTR": 52,
       "PCR": 103,
       "PLR": 81
     },
     {
       "year": 2016,
       "region": "Kilimanjaro",
       "category": "Primary",
       "enrolment_male": 137793,
       "enrolment_female": 134443,
       "enrolment_total": 252747,
       "dropout_male": 1372,
       "dropout_female": 1137,
       "dropout_total": 2509,
       "PTR": 29,
       "PQTR": 30,
       "PCR": 40,
       "PLR": 26
     },
     {
       "year": 2016,
       "region": "Lindi",
       "category": "Primary",
       "enrolment_male": 79624,
       "enrolment_female": 82015,
       "enrolment_total": 174149,
       "dropout_male": 854,
       "dropout_female": 534,
       "dropout_total": 1388,
       "PTR": 41,
       "PQTR": 42,
       "PCR": 52,
       "PLR": 47
     },
     {
       "year": 2016,
       "region": "Manyara",
       "category": "Primary",
       "enrolment_male": 126907,
       "enrolment_female": 129520,
       "enrolment_total": 269798,
       "dropout_male": 3142,
       "dropout_female": 1968,
       "dropout_total": 5110,
       "PTR": 39,
       "PQTR": 40,
       "PCR": 63,
       "PLR": 32
     },
     {
       "year": 2016,
       "region": "Mara",
       "category": "Primary",
       "enrolment_male": 250380,
       "enrolment_female": 245040,
       "enrolment_total": 510733,
       "dropout_male": 3213,
       "dropout_female": 3271,
       "dropout_total": 6484,
       "PTR": 49,
       "PQTR": 50,
       "PCR": 91,
       "PLR": 67
     },
     {
       "year": 2016,
       "region": "Mbeya",
       "category": "Primary",
       "enrolment_male": 181845,
       "enrolment_female": 189719,
       "enrolment_total": 349481,
       "dropout_male": 995,
       "dropout_female": 745,
       "dropout_total": 1740,
       "PTR": 41,
       "PQTR": 41,
       "PCR": 67,
       "PLR": 47
     },
     {
       "year": 2016,
       "region": "Morogoro",
       "category": "Primary",
       "enrolment_male": 206472,
       "enrolment_female": 212346,
       "enrolment_total": 427179,
       "dropout_male": 1485,
       "dropout_female": 1133,
       "dropout_total": 2618,
       "PTR": 40,
       "PQTR": 41,
       "PCR": 74,
       "PLR": 55
     },
     {
       "year": 2016,
       "region": "Mtwara",
       "category": "Primary",
       "enrolment_male": 120327,
       "enrolment_female": 124657,
       "enrolment_total": 259499,
       "dropout_male": 846,
       "dropout_female": 653,
       "dropout_total": 1499,
       "PTR": 43,
       "PQTR": 44,
       "PCR": 61,
       "PLR": 46
     },
     {
       "year": 2016,
       "region": "Mwanza",
       "category": "Primary",
       "enrolment_male": 319892,
       "enrolment_female": 330741,
       "enrolment_total": 672846,
       "dropout_male": 4903,
       "dropout_female": 4816,
       "dropout_total": 9719,
       "PTR": 46,
       "PQTR": 47,
       "PCR": 98,
       "PLR": 78
     },
     {
       "year": 2016,
       "region": "Njombe",
       "category": "Primary",
       "enrolment_male": 76286,
       "enrolment_female": 79177,
       "enrolment_total": 152566,
       "dropout_male": 283,
       "dropout_female": 200,
       "dropout_total": 483,
       "PTR": 38,
       "PQTR": 39,
       "PCR": 48,
       "PLR": 26
     },
     {
       "year": 2016,
       "region": "Pwani",
       "category": "Primary",
       "enrolment_male": 127428,
       "enrolment_female": 128312,
       "enrolment_total": 266554,
       "dropout_male": 1137,
       "dropout_female": 930,
       "dropout_total": 2067,
       "PTR": 38,
       "PQTR": 38,
       "PCR": 66,
       "PLR": 52
     },
     {
       "year": 2016,
       "region": "Rukwa",
       "category": "Primary",
       "enrolment_male": 111244,
       "enrolment_female": 115830,
       "enrolment_total": 239846,
       "dropout_male": 2936,
       "dropout_female": 2715,
       "dropout_total": 5651,
       "PTR": 50,
       "PQTR": 51,
       "PCR": 93,
       "PLR": 60
     },
     {
       "year": 2016,
       "region": "Ruvuma",
       "category": "Primary",
       "enrolment_male": 136580,
       "enrolment_female": 140333,
       "enrolment_total": 296102,
       "dropout_male": 299,
       "dropout_female": 219,
       "dropout_total": 518,
       "PTR": 42,
       "PQTR": 44,
       "PCR": 56,
       "PLR": 46
     },
     {
       "year": 2016,
       "region": "Shinyanga",
       "category": "Primary",
       "enrolment_male": 150551,
       "enrolment_female": 158712,
       "enrolment_total": 350337,
       "dropout_male": 1461,
       "dropout_female": 1247,
       "dropout_total": 2708,
       "PTR": 45,
       "PQTR": 46,
       "PCR": 75,
       "PLR": 71
     },
     {
       "year": 2016,
       "region": "Simiyu",
       "category": "Primary",
       "enrolment_male": 162310,
       "enrolment_female": 173349,
       "enrolment_total": 378352,
       "dropout_male": 3932,
       "dropout_female": 3643,
       "dropout_total": 7575,
       "PTR": 47,
       "PQTR": 47,
       "PCR": 91,
       "PLR": 89
     },
     {
       "year": 2016,
       "region": "Singida",
       "category": "Primary",
       "enrolment_male": 127303,
       "enrolment_female": 134037,
       "enrolment_total": 291955,
       "dropout_male": 3169,
       "dropout_female": 2318,
       "dropout_total": 5487,
       "PTR": 48,
       "PQTR": 49,
       "PCR": 74,
       "PLR": 44
     },
     {
       "year": 2016,
       "region": "Songwe",
       "category": "Primary",
       "enrolment_male": 87516,
       "enrolment_female": 92218,
       "enrolment_total": 212584,
       "dropout_male": 1707,
       "dropout_female": 1548,
       "dropout_total": 3255,
       "PTR": 46,
       "PQTR": 47,
       "PCR": 79,
       "PLR": 54
     },
     {
       "year": 2016,
       "region": "Tabora",
       "category": "Primary",
       "enrolment_male": 221059,
       "enrolment_female": 219768,
       "enrolment_total": 465022,
       "dropout_male": 7655,
       "dropout_female": 6196,
       "dropout_total": 13851,
       "PTR": 44,
       "PQTR": 46,
       "PCR": 89,
       "PLR": 65
     },
     {
       "year": 2016,
       "region": "Tanga",
       "category": "Primary",
       "enrolment_male": 219550,
       "enrolment_female": 221084,
       "enrolment_total": 449793,
       "dropout_male": 2407,
       "dropout_female": 1829,
       "dropout_total": 4236,
       "PTR": 41,
       "PQTR": 42,
       "PCR": 67,
       "PLR": 50
     },
     {
       "year": 2017,
       "region": "Arusha",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 323269,
       "dropout_male": 707,
       "dropout_female": 459,
       "dropout_total": 1166,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Dar es salaam",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 593763,
       "dropout_male": 461,
       "dropout_female": 379,
       "dropout_total": 840,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Dodoma",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 432828,
       "dropout_male": 1861,
       "dropout_female": 1475,
       "dropout_total": 3336,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Geita",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 498671,
       "dropout_male": 3599,
       "dropout_female": 3179,
       "dropout_total": 6778,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Iringa",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 211783,
       "dropout_male": 315,
       "dropout_female": 172,
       "dropout_total": 487,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Kagera",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 510557,
       "dropout_male": 4325,
       "dropout_female": 3462,
       "dropout_total": 7787,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Katavi",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 136073,
       "dropout_male": 502,
       "dropout_female": 413,
       "dropout_total": 915,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Kigoma",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 435261,
       "dropout_male": 1841,
       "dropout_female": 1564,
       "dropout_total": 3405,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Kilimanjaro",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 274142,
       "dropout_male": 500,
       "dropout_female": 317,
       "dropout_total": 817,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Lindi",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 174521,
       "dropout_male": 495,
       "dropout_female": 281,
       "dropout_total": 776,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Manyara",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 276231,
       "dropout_male": 1063,
       "dropout_female": 595,
       "dropout_total": 1658,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Mara",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 524580,
       "dropout_male": 849,
       "dropout_female": 750,
       "dropout_total": 1599,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Mbeya",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 360168,
       "dropout_male": 430,
       "dropout_female": 304,
       "dropout_total": 734,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Morogoro",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 442625,
       "dropout_male": 707,
       "dropout_female": 620,
       "dropout_total": 1327,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Mtwara",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 261194,
       "dropout_male": 585,
       "dropout_female": 378,
       "dropout_total": 963,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Mwanza",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 699286,
       "dropout_male": 2886,
       "dropout_female": 2561,
       "dropout_total": 5447,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Njombe",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 156250,
       "dropout_male": 138,
       "dropout_female": 78,
       "dropout_total": 216,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Pwani",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 277672,
       "dropout_male": 571,
       "dropout_female": 454,
       "dropout_total": 1025,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Rukwa",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 241919,
       "dropout_male": 2126,
       "dropout_female": 1908,
       "dropout_total": 4034,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Ruvuma",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 301722,
       "dropout_male": 295,
       "dropout_female": 282,
       "dropout_total": 577,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Shinyanga",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 361091,
       "dropout_male": 1776,
       "dropout_female": 1496,
       "dropout_total": 3272,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Simiyu",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 380481,
       "dropout_male": 2266,
       "dropout_female": 1859,
       "dropout_total": 4125,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Singida",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 295438,
       "dropout_male": 1175,
       "dropout_female": 937,
       "dropout_total": 2112,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Songwe",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 214622,
       "dropout_male": 890,
       "dropout_female": 802,
       "dropout_total": 1692,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Tabora",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 470816,
       "dropout_male": 5126,
       "dropout_female": 4268,
       "dropout_total": 9394,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     },
     {
       "year": 2017,
       "region": "Tanga",
       "category": "Primary",
       "enrolment_male": null,
       "enrolment_female": null,
       "enrolment_total": 462828,
       "dropout_male": 945,
       "dropout_female": 715,
       "dropout_total": 1660,
       "PTR": null,
       "PQTR": null,
       "PCR": null,
       "PLR": null
     }
     
    ]