export const data=[
    {
        "region": "REGION",
        "council": "Council",
        "year": 2016,
        "Category": "Secondary",
        "enrolment_male": 29791,
        "Enrolment_female": 31990,
        "enrolment_total": "Total Enrollment",
        "Dropout_male": 535,
        "Dropout_female": 387,
        "dropout_total": "Total dropout",
        "PTR": 32,
        "PQTR": 33,
        "PCR": 54,
        "PLR": 37
    },
    {
      "region": "Arusha",
      "council": "Arusha",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10433,
      "Enrolment_female": 12673,
      "enrolment_total": 23106,
      "Dropout_male": 314,
      "Dropout_female": 269,
      "dropout_total": 583,
      "PTR": 21,
      "PQTR": 21,
      "PCR": 45,
      "PLR": 31
    },
    {
      "region": "Arusha",
      "council": "Arusha CC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 13723,
      "Enrolment_female": 14249,
      "enrolment_total": 27972,
      "Dropout_male": 137,
      "Dropout_female": 131,
      "dropout_total": 268,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 48,
      "PLR": 22
    },
    {
      "region": "Arusha",
      "council": "Karatu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4821,
      "Enrolment_female": 5619,
      "enrolment_total": 10440,
      "Dropout_male": 148,
      "Dropout_female": 185,
      "dropout_total": 333,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 41,
      "PLR": 20
    },
    {
      "region": "Arusha",
      "council": "Longido",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2868,
      "Enrolment_female": 3007,
      "enrolment_total": 5875,
      "Dropout_male": 62,
      "Dropout_female": 72,
      "dropout_total": 134,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 69,
      "PLR": 35
    },
    {
      "region": "Arusha",
      "council": "Meru",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10141,
      "Enrolment_female": 11460,
      "enrolment_total": 21601,
      "Dropout_male": 223,
      "Dropout_female": 143,
      "dropout_total": 366,
      "PTR": 12,
      "PQTR": 12,
      "PCR": 38,
      "PLR": 18
    },
    {
      "region": "Arusha",
      "council": "Monduli",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4278,
      "Enrolment_female": 4309,
      "enrolment_total": 8587,
      "Dropout_male": 128,
      "Dropout_female": 77,
      "dropout_total": 205,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 43,
      "PLR": 24
    },
    {
      "region": "Arusha",
      "council": "Ngorongoro",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2848,
      "Enrolment_female": 2603,
      "enrolment_total": 5451,
      "Dropout_male": 250,
      "Dropout_female": 152,
      "dropout_total": 402,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 51,
      "PLR": 25
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ilala MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 29295,
      "Enrolment_female": 30309,
      "enrolment_total": 59604,
      "Dropout_male": 205,
      "Dropout_female": 160,
      "dropout_total": 365,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 50,
      "PLR": 36
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kigamboni MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": "",
      "Enrolment_female": "",
      "enrolment_total": "",
      "Dropout_male": 92,
      "Dropout_female": 64,
      "dropout_total": 156,
      "PTR": "",
      "PQTR": "",
      "PCR": "",
      "PLR": ""
    },
    {
      "region": "Dar-es-salaam",
      "council": "Kinondoni MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 32634,
      "Enrolment_female": 34505,
      "enrolment_total": 67139,
      "Dropout_male": 160,
      "Dropout_female": 129,
      "dropout_total": 289,
      "PTR": 23,
      "PQTR": 23,
      "PCR": 40,
      "PLR": 24
    },
    {
      "region": "Dar-es-salaam",
      "council": "Temeke MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 28005,
      "Enrolment_female": 29443,
      "enrolment_total": 57448,
      "Dropout_male": 207,
      "Dropout_female": 203,
      "dropout_total": 410,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 47,
      "PLR": 39
    },
    {
      "region": "Dar-es-salaam",
      "council": "Ubungo MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": "",
      "Enrolment_female": "",
      "enrolment_total": "",
      "Dropout_male": 193,
      "Dropout_female": 140,
      "dropout_total": 333,
      "PTR": "",
      "PQTR": "",
      "PCR": "",
      "PLR": ""
    },
    {
      "region": "Dodoma",
      "council": "Bahi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1874,
      "Enrolment_female": 1718,
      "enrolment_total": 3592,
      "Dropout_male": 194,
      "Dropout_female": 173,
      "dropout_total": 367,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 29,
      "PLR": 22
    },
    {
      "region": "Dodoma",
      "council": "Chamwino",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3501,
      "Enrolment_female": 3497,
      "enrolment_total": 6998,
      "Dropout_male": 146,
      "Dropout_female": 197,
      "dropout_total": 343,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 34,
      "PLR": 27
    },
    {
      "region": "Dodoma",
      "council": "Chemba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1834,
      "Enrolment_female": 2660,
      "enrolment_total": 4494,
      "Dropout_male": 42,
      "Dropout_female": 76,
      "dropout_total": 118,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 29,
      "PLR": 23
    },
    {
      "region": "Dodoma",
      "council": "Dodoma MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10836,
      "Enrolment_female": 11604,
      "enrolment_total": 22440,
      "Dropout_male": 195,
      "Dropout_female": 186,
      "dropout_total": 381,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 25
    },
    {
      "region": "Dodoma",
      "council": "Kondoa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2123,
      "Enrolment_female": 2814,
      "enrolment_total": 4937,
      "Dropout_male": 99,
      "Dropout_female": 124,
      "dropout_total": 223,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 23
    },
    {
      "region": "Dodoma",
      "council": "Kondoa TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1872,
      "Enrolment_female": 2476,
      "enrolment_total": 4348,
      "Dropout_male": 40,
      "Dropout_female": 30,
      "dropout_total": 70,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 37,
      "PLR": 20
    },
    {
      "region": "Dodoma",
      "council": "Kongwa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3933,
      "Enrolment_female": 4598,
      "enrolment_total": 8531,
      "Dropout_male": 165,
      "Dropout_female": 239,
      "dropout_total": 404,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 34,
      "PLR": 27
    },
    {
      "region": "Dodoma",
      "council": "Mpwapwa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3856,
      "Enrolment_female": 3713,
      "enrolment_total": 7569,
      "Dropout_male": 160,
      "Dropout_female": 193,
      "dropout_total": 353,
      "PTR": 10,
      "PQTR": 10,
      "PCR": 29,
      "PLR": 25
    },
    {
      "region": "Geita",
      "council": "Bukombe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4532,
      "Enrolment_female": 3272,
      "enrolment_total": 7804,
      "Dropout_male": 247,
      "Dropout_female": 229,
      "dropout_total": 476,
      "PTR": 12,
      "PQTR": 12,
      "PCR": 65,
      "PLR": 41
    },
    {
      "region": "Geita",
      "council": "Chato",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6599,
      "Enrolment_female": 4682,
      "enrolment_total": 11281,
      "Dropout_male": 319,
      "Dropout_female": 224,
      "dropout_total": 543,
      "PTR": 21,
      "PQTR": 21,
      "PCR": 46,
      "PLR": 43
    },
    {
      "region": "Geita",
      "council": "Geita",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10107,
      "Enrolment_female": 7241,
      "enrolment_total": 17348,
      "Dropout_male": 936,
      "Dropout_female": 641,
      "dropout_total": 1577,
      "PTR": 21,
      "PQTR": 22,
      "PCR": 51,
      "PLR": 48
    },
    {
      "region": "Geita",
      "council": "Geita TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5742,
      "Enrolment_female": 4908,
      "enrolment_total": 10650,
      "Dropout_male": 177,
      "Dropout_female": 89,
      "dropout_total": 266,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 28
    },
    {
      "region": "Geita",
      "council": "Mbogwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3423,
      "Enrolment_female": 2686,
      "enrolment_total": 6109,
      "Dropout_male": 756,
      "Dropout_female": 639,
      "dropout_total": 1395,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 57,
      "PLR": 51
    },
    {
      "region": "Geita",
      "council": "Nyang'hwale",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2363,
      "Enrolment_female": 2001,
      "enrolment_total": 4364,
      "Dropout_male": 129,
      "Dropout_female": 95,
      "dropout_total": 224,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 48,
      "PLR": 39
    },
    {
      "region": "Iringa",
      "council": "Iringa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 8475,
      "Enrolment_female": 8528,
      "enrolment_total": 17003,
      "Dropout_male": 279,
      "Dropout_female": 181,
      "dropout_total": 460,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 38,
      "PLR": 19
    },
    {
      "region": "Iringa",
      "council": "Iringa MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5343,
      "Enrolment_female": 7481,
      "enrolment_total": 12824,
      "Dropout_male": 100,
      "Dropout_female": 118,
      "dropout_total": 218,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 36,
      "PLR": 20
    },
    {
      "region": "Iringa",
      "council": "Kilolo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5521,
      "Enrolment_female": 6445,
      "enrolment_total": 11966,
      "Dropout_male": 131,
      "Dropout_female": 138,
      "dropout_total": 269,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 35,
      "PLR": 17
    },
    {
      "region": "Iringa",
      "council": "Mafinga TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3894,
      "Enrolment_female": 3178,
      "enrolment_total": 7072,
      "Dropout_male": 33,
      "Dropout_female": 46,
      "dropout_total": 79,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 33,
      "PLR": 14
    },
    {
      "region": "Iringa",
      "council": "Mufindi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6606,
      "Enrolment_female": 7502,
      "enrolment_total": 14108,
      "Dropout_male": 295,
      "Dropout_female": 300,
      "dropout_total": 595,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 30,
      "PLR": 16
    },
    {
      "region": "Kagera",
      "council": "Biharamulo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4865,
      "Enrolment_female": 4063,
      "enrolment_total": 8928,
      "Dropout_male": 458,
      "Dropout_female": 495,
      "dropout_total": 953,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 44,
      "PLR": 33
    },
    {
      "region": "Kagera",
      "council": "Bukoba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5917,
      "Enrolment_female": 5807,
      "enrolment_total": 11724,
      "Dropout_male": 132,
      "Dropout_female": 129,
      "dropout_total": 261,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 33,
      "PLR": 20
    },
    {
      "region": "Kagera",
      "council": "Bukoba MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5239,
      "Enrolment_female": 5096,
      "enrolment_total": 10335,
      "Dropout_male": 45,
      "Dropout_female": 45,
      "dropout_total": 90,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 35,
      "PLR": 16
    },
    {
      "region": "Kagera",
      "council": "Karagwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4762,
      "Enrolment_female": 5550,
      "enrolment_total": 10312,
      "Dropout_male": 174,
      "Dropout_female": 180,
      "dropout_total": 354,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 41,
      "PLR": 25
    },
    {
      "region": "Kagera",
      "council": "Kyerwa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3691,
      "Enrolment_female": 3893,
      "enrolment_total": 7584,
      "Dropout_male": 227,
      "Dropout_female": 231,
      "dropout_total": 458,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 36,
      "PLR": 25
    },
    {
      "region": "Kagera",
      "council": "Missenyi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4106,
      "Enrolment_female": 4282,
      "enrolment_total": 8388,
      "Dropout_male": 142,
      "Dropout_female": 123,
      "dropout_total": 265,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 35,
      "PLR": 21
    },
    {
      "region": "Kagera",
      "council": "Muleba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 9931,
      "Enrolment_female": 9430,
      "enrolment_total": 19361,
      "Dropout_male": 465,
      "Dropout_female": 473,
      "dropout_total": 938,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 40,
      "PLR": 25
    },
    {
      "region": "Kagera",
      "council": "Ngara",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4639,
      "Enrolment_female": 4980,
      "enrolment_total": 9619,
      "Dropout_male": 261,
      "Dropout_female": 244,
      "dropout_total": 505,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 22
    },
    {
      "region": "Katavi",
      "council": "Mlele",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 446,
      "Enrolment_female": 298,
      "enrolment_total": 744,
      "Dropout_male": 38,
      "Dropout_female": 30,
      "dropout_total": 68,
      "PTR": 11,
      "PQTR": 11,
      "PCR": 39,
      "PLR": 17
    },
    {
      "region": "Katavi",
      "council": "Mpanda",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1866,
      "Enrolment_female": 1390,
      "enrolment_total": 3256,
      "Dropout_male": 222,
      "Dropout_female": 183,
      "dropout_total": 405,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 40,
      "PLR": 22
    },
    {
      "region": "Katavi",
      "council": "Mpanda MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2603,
      "Enrolment_female": 3222,
      "enrolment_total": 5825,
      "Dropout_male": 68,
      "Dropout_female": 75,
      "dropout_total": 143,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 40,
      "PLR": 23
    },
    {
      "region": "Katavi",
      "council": "Mpimbwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 978,
      "Enrolment_female": 630,
      "enrolment_total": 1608,
      "Dropout_male": 23,
      "Dropout_female": 24,
      "dropout_total": 47,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 37,
      "PLR": 32
    },
    {
      "region": "Katavi",
      "council": "Nsimbo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1989,
      "Enrolment_female": 1452,
      "enrolment_total": 3441,
      "Dropout_male": 100,
      "Dropout_female": 93,
      "dropout_total": 193,
      "PTR": 32,
      "PQTR": 33,
      "PCR": 40,
      "PLR": 27
    },
    {
      "region": "Kigoma",
      "council": "Buhigwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3993,
      "Enrolment_female": 2565,
      "enrolment_total": 6558,
      "Dropout_male": 166,
      "Dropout_female": 93,
      "dropout_total": 259,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 36,
      "PLR": 20
    },
    {
      "region": "Kigoma",
      "council": "Kakonko",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2291,
      "Enrolment_female": 1580,
      "enrolment_total": 3871,
      "Dropout_male": 119,
      "Dropout_female": 66,
      "dropout_total": 185,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 36,
      "PLR": 20
    },
    {
      "region": "Kigoma",
      "council": "Kasulu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2891,
      "Enrolment_female": 1754,
      "enrolment_total": 4645,
      "Dropout_male": 77,
      "Dropout_female": 53,
      "dropout_total": 130,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 34,
      "PLR": 22
    },
    {
      "region": "Kigoma",
      "council": "Kasulu TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4635,
      "Enrolment_female": 3598,
      "enrolment_total": 8233,
      "Dropout_male": 29,
      "Dropout_female": 44,
      "dropout_total": 73,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 35,
      "PLR": 22
    },
    {
      "region": "Kigoma",
      "council": "Kibondo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3786,
      "Enrolment_female": 4527,
      "enrolment_total": 8313,
      "Dropout_male": 216,
      "Dropout_female": 172,
      "dropout_total": 388,
      "PTR": 14,
      "PQTR": 15,
      "PCR": 41,
      "PLR": 26
    },
    {
      "region": "Kigoma",
      "council": "Kigoma",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4589,
      "Enrolment_female": 2444,
      "enrolment_total": 7033,
      "Dropout_male": 73,
      "Dropout_female": 39,
      "dropout_total": 112,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 34,
      "PLR": 20
    },
    {
      "region": "Kigoma",
      "council": "Kigoma/Ujiji MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6385,
      "Enrolment_female": 4495,
      "enrolment_total": 10880,
      "Dropout_male": 171,
      "Dropout_female": 116,
      "dropout_total": 287,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 39,
      "PLR": 32
    },
    {
      "region": "Kigoma",
      "council": "Uvinza",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3510,
      "Enrolment_female": 1830,
      "enrolment_total": 5340,
      "Dropout_male": 201,
      "Dropout_female": 115,
      "dropout_total": 316,
      "PTR": 21,
      "PQTR": 22,
      "PCR": 40,
      "PLR": 29
    },
    {
      "region": "Kilimanjaro",
      "council": "Hai",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6960,
      "Enrolment_female": 8173,
      "enrolment_total": 15133,
      "Dropout_male": 128,
      "Dropout_female": 152,
      "dropout_total": 280,
      "PTR": 15,
      "PQTR": 16,
      "PCR": 39,
      "PLR": 20
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 17178,
      "Enrolment_female": 20669,
      "enrolment_total": 37847,
      "Dropout_male": 255,
      "Dropout_female": 270,
      "dropout_total": 525,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 39,
      "PLR": 18
    },
    {
      "region": "Kilimanjaro",
      "council": "Moshi MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 9549,
      "Enrolment_female": 8276,
      "enrolment_total": 17825,
      "Dropout_male": 77,
      "Dropout_female": 61,
      "dropout_total": 138,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 22,
      "PLR": 24
    },
    {
      "region": "Kilimanjaro",
      "council": "Mwanga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 7614,
      "Enrolment_female": 8526,
      "enrolment_total": 16140,
      "Dropout_male": 108,
      "Dropout_female": 108,
      "dropout_total": 216,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 37,
      "PLR": 18
    },
    {
      "region": "Kilimanjaro",
      "council": "Rombo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 8318,
      "Enrolment_female": 11479,
      "enrolment_total": 19797,
      "Dropout_male": 265,
      "Dropout_female": 249,
      "dropout_total": 514,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 40,
      "PLR": 23
    },
    {
      "region": "Kilimanjaro",
      "council": "Same",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 9847,
      "Enrolment_female": 11718,
      "enrolment_total": 21565,
      "Dropout_male": 336,
      "Dropout_female": 269,
      "dropout_total": 605,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 41,
      "PLR": 21
    },
    {
      "region": "Kilimanjaro",
      "council": "Siha",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2786,
      "Enrolment_female": 4011,
      "enrolment_total": 6797,
      "Dropout_male": 70,
      "Dropout_female": 50,
      "dropout_total": 120,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 38,
      "PLR": 18
    },
    {
      "region": "Lindi",
      "council": "Kilwa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2566,
      "Enrolment_female": 2947,
      "enrolment_total": 5513,
      "Dropout_male": 187,
      "Dropout_female": 139,
      "dropout_total": 326,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 35,
      "PLR": 22
    },
    {
      "region": "Lindi",
      "council": "Lindi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3104,
      "Enrolment_female": 2196,
      "enrolment_total": 5300,
      "Dropout_male": 110,
      "Dropout_female": 82,
      "dropout_total": 192,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 26,
      "PLR": 16
    },
    {
      "region": "Lindi",
      "council": "Lindi MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1934,
      "Enrolment_female": 1611,
      "enrolment_total": 3545,
      "Dropout_male": 46,
      "Dropout_female": 42,
      "dropout_total": 88,
      "PTR": 15,
      "PQTR": 16,
      "PCR": 36,
      "PLR": 21
    },
    {
      "region": "Lindi",
      "council": "Liwale",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2226,
      "Enrolment_female": 2024,
      "enrolment_total": 4250,
      "Dropout_male": 134,
      "Dropout_female": 103,
      "dropout_total": 237,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 44,
      "PLR": 31
    },
    {
      "region": "Lindi",
      "council": "Nachingwea",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2738,
      "Enrolment_female": 2782,
      "enrolment_total": 5520,
      "Dropout_male": 140,
      "Dropout_female": 94,
      "dropout_total": 234,
      "PTR": 15,
      "PQTR": 16,
      "PCR": 29,
      "PLR": 23
    },
    {
      "region": "Lindi",
      "council": "Ruangwa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1721,
      "Enrolment_female": 1544,
      "enrolment_total": 3265,
      "Dropout_male": 62,
      "Dropout_female": 49,
      "dropout_total": 111,
      "PTR": 12,
      "PQTR": 12,
      "PCR": 36,
      "PLR": 27
    },
    {
      "region": "Manyara",
      "council": "Babati",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5183,
      "Enrolment_female": 6994,
      "enrolment_total": 12177,
      "Dropout_male": 220,
      "Dropout_female": 168,
      "dropout_total": 388,
      "PTR": 14,
      "PQTR": 15,
      "PCR": 43,
      "PLR": 34
    },
    {
      "region": "Manyara",
      "council": "Babati TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3253,
      "Enrolment_female": 3896,
      "enrolment_total": 7149,
      "Dropout_male": 37,
      "Dropout_female": 33,
      "dropout_total": 70,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 39,
      "PLR": 30
    },
    {
      "region": "Manyara",
      "council": "Hanang",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3217,
      "Enrolment_female": 4532,
      "enrolment_total": 7749,
      "Dropout_male": 190,
      "Dropout_female": 174,
      "dropout_total": 364,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 35,
      "PLR": 20
    },
    {
      "region": "Manyara",
      "council": "Kiteto",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2066,
      "Enrolment_female": 2476,
      "enrolment_total": 4542,
      "Dropout_male": 47,
      "Dropout_female": 144,
      "dropout_total": 191,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 33,
      "PLR": 22
    },
    {
      "region": "Manyara",
      "council": "Mbulu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2237,
      "Enrolment_female": 3598,
      "enrolment_total": 5835,
      "Dropout_male": 196,
      "Dropout_female": 262,
      "dropout_total": 458,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 34,
      "PLR": 23
    },
    {
      "region": "Manyara",
      "council": "Mbulu TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3046,
      "Enrolment_female": 3485,
      "enrolment_total": 6531,
      "Dropout_male": 163,
      "Dropout_female": 150,
      "dropout_total": 313,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 35,
      "PLR": 23
    },
    {
      "region": "Manyara",
      "council": "Simanjiro",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2223,
      "Enrolment_female": 2130,
      "enrolment_total": 4353,
      "Dropout_male": 86,
      "Dropout_female": 53,
      "dropout_total": 139,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 41,
      "PLR": 24
    },
    {
      "region": "Mara",
      "council": "Bunda",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4977,
      "Enrolment_female": 3238,
      "enrolment_total": 8215,
      "Dropout_male": 208,
      "Dropout_female": 169,
      "dropout_total": 377,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 35,
      "PLR": 32
    },
    {
      "region": "Mara",
      "council": "Bunda TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3656,
      "Enrolment_female": 3118,
      "enrolment_total": 6774,
      "Dropout_male": 140,
      "Dropout_female": 122,
      "dropout_total": 262,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 40,
      "PLR": 35
    },
    {
      "region": "Mara",
      "council": "Butiama",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4750,
      "Enrolment_female": 4179,
      "enrolment_total": 8929,
      "Dropout_male": 187,
      "Dropout_female": 119,
      "dropout_total": 306,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 36,
      "PLR": 26
    },
    {
      "region": "Mara",
      "council": "Musoma",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4377,
      "Enrolment_female": 2667,
      "enrolment_total": 7044,
      "Dropout_male": 238,
      "Dropout_female": 159,
      "dropout_total": 397,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 43,
      "PLR": 30
    },
    {
      "region": "Mara",
      "council": "Musoma MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 7101,
      "Enrolment_female": 4810,
      "enrolment_total": 11911,
      "Dropout_male": 128,
      "Dropout_female": 76,
      "dropout_total": 204,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 38,
      "PLR": 26
    },
    {
      "region": "Mara",
      "council": "Rorya",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5882,
      "Enrolment_female": 4239,
      "enrolment_total": 10121,
      "Dropout_male": 177,
      "Dropout_female": 170,
      "dropout_total": 347,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 39,
      "PLR": 31
    },
    {
      "region": "Mara",
      "council": "Serengeti",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5121,
      "Enrolment_female": 4231,
      "enrolment_total": 9352,
      "Dropout_male": 212,
      "Dropout_female": 161,
      "dropout_total": 373,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 41,
      "PLR": 28
    },
    {
      "region": "Mara",
      "council": "Tarime",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5214,
      "Enrolment_female": 3405,
      "enrolment_total": 8619,
      "Dropout_male": 209,
      "Dropout_female": 167,
      "dropout_total": 376,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 38,
      "PLR": 23
    },
    {
      "region": "Mara",
      "council": "Tarime TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3157,
      "Enrolment_female": 2169,
      "enrolment_total": 5326,
      "Dropout_male": 64,
      "Dropout_female": 44,
      "dropout_total": 108,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 44,
      "PLR": 22
    },
    {
      "region": "Mbeya",
      "council": "Busokelo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4216,
      "Enrolment_female": 3462,
      "enrolment_total": 7678,
      "Dropout_male": 118,
      "Dropout_female": 124,
      "dropout_total": 242,
      "PTR": 21,
      "PQTR": 21,
      "PCR": 47,
      "PLR": 21
    },
    {
      "region": "Mbeya",
      "council": "Chunya",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3519,
      "Enrolment_female": 3027,
      "enrolment_total": 6546,
      "Dropout_male": 97,
      "Dropout_female": 101,
      "dropout_total": 198,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 27,
      "PLR": 23
    },
    {
      "region": "Mbeya",
      "council": "Kyela",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 7116,
      "Enrolment_female": 5929,
      "enrolment_total": 13045,
      "Dropout_male": 184,
      "Dropout_female": 202,
      "dropout_total": 386,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 39,
      "PLR": 37
    },
    {
      "region": "Mbeya",
      "council": "Mbarali",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4799,
      "Enrolment_female": 5146,
      "enrolment_total": 9945,
      "Dropout_male": 135,
      "Dropout_female": 165,
      "dropout_total": 300,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 29
    },
    {
      "region": "Mbeya",
      "council": "Mbeya",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 8339,
      "Enrolment_female": 9747,
      "enrolment_total": 18086,
      "Dropout_male": 130,
      "Dropout_female": 179,
      "dropout_total": 309,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 45,
      "PLR": 30
    },
    {
      "region": "Mbeya",
      "council": "Mbeya CC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 18080,
      "Enrolment_female": 17338,
      "enrolment_total": 35418,
      "Dropout_male": 189,
      "Dropout_female": 256,
      "dropout_total": 445,
      "PTR": 21,
      "PQTR": 21,
      "PCR": 32,
      "PLR": 18
    },
    {
      "region": "Mbeya",
      "council": "Rungwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 9358,
      "Enrolment_female": 8725,
      "enrolment_total": 18083,
      "Dropout_male": 238,
      "Dropout_female": 232,
      "dropout_total": 470,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 39,
      "PLR": 23
    },
    {
      "region": "Morogoro",
      "council": "Gairo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1435,
      "Enrolment_female": 1979,
      "enrolment_total": 3414,
      "Dropout_male": 92,
      "Dropout_female": 135,
      "dropout_total": 227,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 42,
      "PLR": 37
    },
    {
      "region": "Morogoro",
      "council": "Ifakara TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2759,
      "Enrolment_female": 3776,
      "enrolment_total": 6535,
      "Dropout_male": 120,
      "Dropout_female": 117,
      "dropout_total": 237,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 43,
      "PLR": 27
    },
    {
      "region": "Morogoro",
      "council": "Kilombero",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5527,
      "Enrolment_female": 5647,
      "enrolment_total": 11174,
      "Dropout_male": 98,
      "Dropout_female": 98,
      "dropout_total": 196,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 34,
      "PLR": 21
    },
    {
      "region": "Morogoro",
      "council": "Kilosa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 7237,
      "Enrolment_female": 6839,
      "enrolment_total": 14076,
      "Dropout_male": 178,
      "Dropout_female": 203,
      "dropout_total": 381,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 41,
      "PLR": 18
    },
    {
      "region": "Morogoro",
      "council": "Malinyi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2137,
      "Enrolment_female": 2003,
      "enrolment_total": 4140,
      "Dropout_male": 44,
      "Dropout_female": 33,
      "dropout_total": 77,
      "PTR": 12,
      "PQTR": 12,
      "PCR": 35,
      "PLR": 24
    },
    {
      "region": "Morogoro",
      "council": "Morogoro",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3698,
      "Enrolment_female": 3813,
      "enrolment_total": 7511,
      "Dropout_male": 149,
      "Dropout_female": 123,
      "dropout_total": 272,
      "PTR": 13,
      "PQTR": 14,
      "PCR": 35,
      "PLR": 36
    },
    {
      "region": "Morogoro",
      "council": "Morogoro MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10819,
      "Enrolment_female": 12594,
      "enrolment_total": 23413,
      "Dropout_male": 146,
      "Dropout_female": 132,
      "dropout_total": 278,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 45,
      "PLR": 22
    },
    {
      "region": "Morogoro",
      "council": "Mvomero",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4800,
      "Enrolment_female": 5449,
      "enrolment_total": 10249,
      "Dropout_male": 173,
      "Dropout_female": 222,
      "dropout_total": 395,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 37,
      "PLR": 39
    },
    {
      "region": "Morogoro",
      "council": "Ulanga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3591,
      "Enrolment_female": 2653,
      "enrolment_total": 6244,
      "Dropout_male": 75,
      "Dropout_female": 66,
      "dropout_total": 141,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 36,
      "PLR": 25
    },
    {
      "region": "Mtwara",
      "council": "Masasi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4637,
      "Enrolment_female": 3464,
      "enrolment_total": 8101,
      "Dropout_male": 221,
      "Dropout_female": 192,
      "dropout_total": 413,
      "PTR": 12,
      "PQTR": 13,
      "PCR": 38,
      "PLR": 24
    },
    {
      "region": "Mtwara",
      "council": "Masasi TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1530,
      "Enrolment_female": 2219,
      "enrolment_total": 3749,
      "Dropout_male": 164,
      "Dropout_female": 143,
      "dropout_total": 307,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 37,
      "PLR": 32
    },
    {
      "region": "Mtwara",
      "council": "Mtwara",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1827,
      "Enrolment_female": 2071,
      "enrolment_total": 3898,
      "Dropout_male": 156,
      "Dropout_female": 144,
      "dropout_total": 300,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 45,
      "PLR": 31
    },
    {
      "region": "Mtwara",
      "council": "Mtwara Mikindani MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4030,
      "Enrolment_female": 4663,
      "enrolment_total": 8693,
      "Dropout_male": 86,
      "Dropout_female": 58,
      "dropout_total": 144,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 47,
      "PLR": 21
    },
    {
      "region": "Mtwara",
      "council": "Nanyamba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1865,
      "Enrolment_female": 1913,
      "enrolment_total": 3778,
      "Dropout_male": 158,
      "Dropout_female": 190,
      "dropout_total": 348,
      "PTR": 10,
      "PQTR": 10,
      "PCR": 43,
      "PLR": 40
    },
    {
      "region": "Mtwara",
      "council": "Nanyumbu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1479,
      "Enrolment_female": 1559,
      "enrolment_total": 3038,
      "Dropout_male": 183,
      "Dropout_female": 191,
      "dropout_total": 374,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 40,
      "PLR": 28
    },
    {
      "region": "Mtwara",
      "council": "Newala",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1628,
      "Enrolment_female": 1719,
      "enrolment_total": 3347,
      "Dropout_male": 33,
      "Dropout_female": 33,
      "dropout_total": 66,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 36,
      "PLR": 20
    },
    {
      "region": "Mtwara",
      "council": "Newala TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1559,
      "Enrolment_female": 2023,
      "enrolment_total": 3582,
      "Dropout_male": 64,
      "Dropout_female": 38,
      "dropout_total": 102,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 34,
      "PLR": 29
    },
    {
      "region": "Mtwara",
      "council": "Tandahimba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3503,
      "Enrolment_female": 3947,
      "enrolment_total": 7450,
      "Dropout_male": 351,
      "Dropout_female": 300,
      "dropout_total": 651,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 36,
      "PLR": 30
    },
    {
      "region": "Mwanza",
      "council": "Buchosa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5720,
      "Enrolment_female": 3894,
      "enrolment_total": 9614,
      "Dropout_male": 502,
      "Dropout_female": 440,
      "dropout_total": 942,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 61,
      "PLR": 52
    },
    {
      "region": "Mwanza",
      "council": "Ilemela MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 12206,
      "Enrolment_female": 12462,
      "enrolment_total": 24668,
      "Dropout_male": 190,
      "Dropout_female": 174,
      "dropout_total": 364,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 53,
      "PLR": 29
    },
    {
      "region": "Mwanza",
      "council": "Kwimba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6479,
      "Enrolment_female": 6735,
      "enrolment_total": 13214,
      "Dropout_male": 558,
      "Dropout_female": 488,
      "dropout_total": 1046,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 47,
      "PLR": 32
    },
    {
      "region": "Mwanza",
      "council": "Magu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6991,
      "Enrolment_female": 6086,
      "enrolment_total": 13077,
      "Dropout_male": 390,
      "Dropout_female": 332,
      "dropout_total": 722,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 44,
      "PLR": 31
    },
    {
      "region": "Mwanza",
      "council": "Misungwi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5184,
      "Enrolment_female": 5435,
      "enrolment_total": 10619,
      "Dropout_male": 476,
      "Dropout_female": 508,
      "dropout_total": 984,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 49,
      "PLR": 34
    },
    {
      "region": "Mwanza",
      "council": "Mwanza CC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 16423,
      "Enrolment_female": 15908,
      "enrolment_total": 32331,
      "Dropout_male": 243,
      "Dropout_female": 247,
      "dropout_total": 490,
      "PTR": 24,
      "PQTR": 24,
      "PCR": 56,
      "PLR": 28
    },
    {
      "region": "Mwanza",
      "council": "Sengerema",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 9245,
      "Enrolment_female": 6630,
      "enrolment_total": 15875,
      "Dropout_male": 356,
      "Dropout_female": 278,
      "dropout_total": 634,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 54,
      "PLR": 31
    },
    {
      "region": "Mwanza",
      "council": "Ukerewe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 8822,
      "Enrolment_female": 6859,
      "enrolment_total": 15681,
      "Dropout_male": 390,
      "Dropout_female": 367,
      "dropout_total": 757,
      "PTR": 29,
      "PQTR": 29,
      "PCR": 57,
      "PLR": 47
    },
    {
      "region": "Njombe",
      "council": "Ludewa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2895,
      "Enrolment_female": 3012,
      "enrolment_total": 5907,
      "Dropout_male": 100,
      "Dropout_female": 84,
      "dropout_total": 184,
      "PTR": 12,
      "PQTR": 12,
      "PCR": 31,
      "PLR": 19
    },
    {
      "region": "Njombe",
      "council": "Makambako TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2329,
      "Enrolment_female": 3737,
      "enrolment_total": 6066,
      "Dropout_male": 79,
      "Dropout_female": 63,
      "dropout_total": 142,
      "PTR": 15,
      "PQTR": 16,
      "PCR": 39,
      "PLR": 19
    },
    {
      "region": "Njombe",
      "council": "Makete",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2739,
      "Enrolment_female": 2650,
      "enrolment_total": 5389,
      "Dropout_male": 171,
      "Dropout_female": 109,
      "dropout_total": 280,
      "PTR": 11,
      "PQTR": 11,
      "PCR": 35,
      "PLR": 17
    },
    {
      "region": "Njombe",
      "council": "Njombe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1439,
      "Enrolment_female": 2681,
      "enrolment_total": 4120,
      "Dropout_male": 135,
      "Dropout_female": 115,
      "dropout_total": 250,
      "PTR": 10,
      "PQTR": 10,
      "PCR": 41,
      "PLR": 20
    },
    {
      "region": "Njombe",
      "council": "Njombe TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4944,
      "Enrolment_female": 4933,
      "enrolment_total": 9877,
      "Dropout_male": 202,
      "Dropout_female": 155,
      "dropout_total": 357,
      "PTR": 11,
      "PQTR": 11,
      "PCR": 34,
      "PLR": 15
    },
    {
      "region": "Njombe",
      "council": "Wanging'ombe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3769,
      "Enrolment_female": 5303,
      "enrolment_total": 9072,
      "Dropout_male": 280,
      "Dropout_female": 233,
      "dropout_total": 513,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 42,
      "PLR": 21
    },
    {
      "region": "Pwani",
      "council": "Bagamoyo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5114,
      "Enrolment_female": 5393,
      "enrolment_total": 10507,
      "Dropout_male": 48,
      "Dropout_female": 36,
      "dropout_total": 84,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 35,
      "PLR": 14
    },
    {
      "region": "Pwani",
      "council": "Chalinze",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4657,
      "Enrolment_female": 5282,
      "enrolment_total": 9939,
      "Dropout_male": 138,
      "Dropout_female": 178,
      "dropout_total": 316,
      "PTR": 14,
      "PQTR": 15,
      "PCR": 39,
      "PLR": 25
    },
    {
      "region": "Pwani",
      "council": "Kibaha",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2219,
      "Enrolment_female": 3417,
      "enrolment_total": 5636,
      "Dropout_male": 116,
      "Dropout_female": 120,
      "dropout_total": 236,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 37,
      "PLR": 18
    },
    {
      "region": "Pwani",
      "council": "Kibaha TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4809,
      "Enrolment_female": 5453,
      "enrolment_total": 10262,
      "Dropout_male": 89,
      "Dropout_female": 99,
      "dropout_total": 188,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 42,
      "PLR": 15
    },
    {
      "region": "Pwani",
      "council": "Kibiti",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": "",
      "Enrolment_female": "",
      "enrolment_total": "",
      "Dropout_male": 29,
      "Dropout_female": 25,
      "dropout_total": 54,
      "PTR": "",
      "PQTR": "",
      "PCR": "",
      "PLR": ""
    },
    {
      "region": "Pwani",
      "council": "Kisarawe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3547,
      "Enrolment_female": 2364,
      "enrolment_total": 5911,
      "Dropout_male": 136,
      "Dropout_female": 84,
      "dropout_total": 220,
      "PTR": 10,
      "PQTR": 10,
      "PCR": 33,
      "PLR": 18
    },
    {
      "region": "Pwani",
      "council": "Mafia",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 754,
      "Enrolment_female": 1001,
      "enrolment_total": 1755,
      "Dropout_male": 8,
      "Dropout_female": 15,
      "dropout_total": 23,
      "PTR": 12,
      "PQTR": 13,
      "PCR": 22,
      "PLR": 29
    },
    {
      "region": "Pwani",
      "council": "Mkuranga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6686,
      "Enrolment_female": 5914,
      "enrolment_total": 12600,
      "Dropout_male": 220,
      "Dropout_female": 231,
      "dropout_total": 451,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 36,
      "PLR": 15
    },
    {
      "region": "Pwani",
      "council": "Rufiji",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4050,
      "Enrolment_female": 3709,
      "enrolment_total": 7759,
      "Dropout_male": 85,
      "Dropout_female": 58,
      "dropout_total": 143,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 37,
      "PLR": 28
    },
    {
      "region": "Rukwa",
      "council": "Kalambo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3053,
      "Enrolment_female": 1772,
      "enrolment_total": 4825,
      "Dropout_male": 278,
      "Dropout_female": 203,
      "dropout_total": 481,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 32,
      "PLR": 15
    },
    {
      "region": "Rukwa",
      "council": "Nkasi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3703,
      "Enrolment_female": 2848,
      "enrolment_total": 6551,
      "Dropout_male": 234,
      "Dropout_female": 212,
      "dropout_total": 446,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 40,
      "PLR": 24
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3250,
      "Enrolment_female": 2225,
      "enrolment_total": 5475,
      "Dropout_male": 104,
      "Dropout_female": 72,
      "dropout_total": 176,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 30,
      "PLR": 12
    },
    {
      "region": "Rukwa",
      "council": "Sumbawanga MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6941,
      "Enrolment_female": 6184,
      "enrolment_total": 13125,
      "Dropout_male": 103,
      "Dropout_female": 118,
      "dropout_total": 221,
      "PTR": 21,
      "PQTR": 22,
      "PCR": 38,
      "PLR": 25
    },
    {
      "region": "Ruvuma",
      "council": "Madaba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1470,
      "Enrolment_female": 1194,
      "enrolment_total": 2664,
      "Dropout_male": 38,
      "Dropout_female": 60,
      "dropout_total": 98,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 38,
      "PLR": 17
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5288,
      "Enrolment_female": 5937,
      "enrolment_total": 11225,
      "Dropout_male": 294,
      "Dropout_female": 253,
      "dropout_total": 547,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 38,
      "PLR": 22
    },
    {
      "region": "Ruvuma",
      "council": "Mbinga TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2518,
      "Enrolment_female": 2617,
      "enrolment_total": 5135,
      "Dropout_male": 77,
      "Dropout_female": 65,
      "dropout_total": 142,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 36,
      "PLR": 26
    },
    {
      "region": "Ruvuma",
      "council": "Namtumbo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3963,
      "Enrolment_female": 3475,
      "enrolment_total": 7438,
      "Dropout_male": 261,
      "Dropout_female": 239,
      "dropout_total": 500,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 38,
      "PLR": 18
    },
    {
      "region": "Ruvuma",
      "council": "Nyasa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2245,
      "Enrolment_female": 2148,
      "enrolment_total": 4393,
      "Dropout_male": 131,
      "Dropout_female": 156,
      "dropout_total": 287,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 39,
      "PLR": 25
    },
    {
      "region": "Ruvuma",
      "council": "Songea",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1975,
      "Enrolment_female": 2961,
      "enrolment_total": 4936,
      "Dropout_male": 69,
      "Dropout_female": 86,
      "dropout_total": 155,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 27,
      "PLR": 17
    },
    {
      "region": "Ruvuma",
      "council": "Songea MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 6748,
      "Enrolment_female": 7138,
      "enrolment_total": 13886,
      "Dropout_male": 33,
      "Dropout_female": 37,
      "dropout_total": 70,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 38,
      "PLR": 18
    },
    {
      "region": "Ruvuma",
      "council": "Tunduru",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4810,
      "Enrolment_female": 3329,
      "enrolment_total": 8139,
      "Dropout_male": 263,
      "Dropout_female": 235,
      "dropout_total": 498,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 45,
      "PLR": 22
    },
    {
      "region": "Shinyanga",
      "council": "Kahama TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5868,
      "Enrolment_female": 5898,
      "enrolment_total": 11766,
      "Dropout_male": 157,
      "Dropout_female": 147,
      "dropout_total": 304,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 49,
      "PLR": 29
    },
    {
      "region": "Shinyanga",
      "council": "Kishapu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5084,
      "Enrolment_female": 3779,
      "enrolment_total": 8863,
      "Dropout_male": 161,
      "Dropout_female": 167,
      "dropout_total": 328,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 55,
      "PLR": 37
    },
    {
      "region": "Shinyanga",
      "council": "Msalala",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3841,
      "Enrolment_female": 3429,
      "enrolment_total": 7270,
      "Dropout_male": 600,
      "Dropout_female": 491,
      "dropout_total": 1091,
      "PTR": 18,
      "PQTR": 18,
      "PCR": 54,
      "PLR": 33
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4407,
      "Enrolment_female": 3871,
      "enrolment_total": 8278,
      "Dropout_male": 249,
      "Dropout_female": 234,
      "dropout_total": 483,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 20
    },
    {
      "region": "Shinyanga",
      "council": "Shinyanga MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4428,
      "Enrolment_female": 4189,
      "enrolment_total": 8617,
      "Dropout_male": 59,
      "Dropout_female": 71,
      "dropout_total": 130,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 44,
      "PLR": 27
    },
    {
      "region": "Shinyanga",
      "council": "Ushetu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2774,
      "Enrolment_female": 2214,
      "enrolment_total": 4988,
      "Dropout_male": 211,
      "Dropout_female": 161,
      "dropout_total": 372,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 43,
      "PLR": 23
    },
    {
      "region": "Simiyu",
      "council": "Bariadi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3440,
      "Enrolment_female": 2512,
      "enrolment_total": 5952,
      "Dropout_male": 180,
      "Dropout_female": 131,
      "dropout_total": 311,
      "PTR": 21,
      "PQTR": 22,
      "PCR": 41,
      "PLR": 49
    },
    {
      "region": "Simiyu",
      "council": "Bariadi TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3573,
      "Enrolment_female": 2884,
      "enrolment_total": 6457,
      "Dropout_male": 178,
      "Dropout_female": 126,
      "dropout_total": 304,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 50,
      "PLR": 41
    },
    {
      "region": "Simiyu",
      "council": "Busega",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5477,
      "Enrolment_female": 4244,
      "enrolment_total": 9721,
      "Dropout_male": 156,
      "Dropout_female": 118,
      "dropout_total": 274,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 43,
      "PLR": 32
    },
    {
      "region": "Simiyu",
      "council": "Itilima",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3890,
      "Enrolment_female": 2649,
      "enrolment_total": 6539,
      "Dropout_male": 322,
      "Dropout_female": 185,
      "dropout_total": 507,
      "PTR": 18,
      "PQTR": 19,
      "PCR": 38,
      "PLR": 46
    },
    {
      "region": "Simiyu",
      "council": "Maswa",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5404,
      "Enrolment_female": 4543,
      "enrolment_total": 9947,
      "Dropout_male": 252,
      "Dropout_female": 240,
      "dropout_total": 492,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 34,
      "PLR": 24
    },
    {
      "region": "Simiyu",
      "council": "Meatu",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2922,
      "Enrolment_female": 2358,
      "enrolment_total": 5280,
      "Dropout_male": 141,
      "Dropout_female": 171,
      "dropout_total": 312,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 33,
      "PLR": 27
    },
    {
      "region": "Singida",
      "council": "Ikungi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3734,
      "Enrolment_female": 4630,
      "enrolment_total": 8364,
      "Dropout_male": 194,
      "Dropout_female": 162,
      "dropout_total": 356,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 34,
      "PLR": 26
    },
    {
      "region": "Singida",
      "council": "Iramba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3183,
      "Enrolment_female": 3428,
      "enrolment_total": 6611,
      "Dropout_male": 141,
      "Dropout_female": 111,
      "dropout_total": 252,
      "PTR": 17,
      "PQTR": 18,
      "PCR": 38,
      "PLR": 25
    },
    {
      "region": "Singida",
      "council": "Itigi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1460,
      "Enrolment_female": 1256,
      "enrolment_total": 2716,
      "Dropout_male": 22,
      "Dropout_female": 25,
      "dropout_total": 47,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 37,
      "PLR": 27
    },
    {
      "region": "Singida",
      "council": "Manyoni",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2175,
      "Enrolment_female": 2249,
      "enrolment_total": 4424,
      "Dropout_male": 61,
      "Dropout_female": 86,
      "dropout_total": 147,
      "PTR": 19,
      "PQTR": 19,
      "PCR": 36,
      "PLR": 18
    },
    {
      "region": "Singida",
      "council": "Mkalama",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2032,
      "Enrolment_female": 2364,
      "enrolment_total": 4396,
      "Dropout_male": 86,
      "Dropout_female": 78,
      "dropout_total": 164,
      "PTR": 16,
      "PQTR": 17,
      "PCR": 28,
      "PLR": 25
    },
    {
      "region": "Singida",
      "council": "Singida",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3670,
      "Enrolment_female": 4510,
      "enrolment_total": 8180,
      "Dropout_male": 260,
      "Dropout_female": 272,
      "dropout_total": 532,
      "PTR": 20,
      "PQTR": 21,
      "PCR": 37,
      "PLR": 25
    },
    {
      "region": "Singida",
      "council": "Singida MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4305,
      "Enrolment_female": 3751,
      "enrolment_total": 8056,
      "Dropout_male": 94,
      "Dropout_female": 104,
      "dropout_total": 198,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 37,
      "PLR": 21
    },
    {
      "region": "Songwe",
      "council": "Ileje",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2464,
      "Enrolment_female": 2983,
      "enrolment_total": 5447,
      "Dropout_male": 63,
      "Dropout_female": 96,
      "dropout_total": 159,
      "PTR": 25,
      "PQTR": 26,
      "PCR": 34,
      "PLR": 21
    },
    {
      "region": "Songwe",
      "council": "Mbozi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 10026,
      "Enrolment_female": 12294,
      "enrolment_total": 22320,
      "Dropout_male": 358,
      "Dropout_female": 399,
      "dropout_total": 757,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 37,
      "PLR": 23
    },
    {
      "region": "Songwe",
      "council": "Momba",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1301,
      "Enrolment_female": 747,
      "enrolment_total": 2048,
      "Dropout_male": 117,
      "Dropout_female": 45,
      "dropout_total": 162,
      "PTR": 11,
      "PQTR": 11,
      "PCR": 37,
      "PLR": 30
    },
    {
      "region": "Songwe",
      "council": "Songwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": "",
      "Enrolment_female": "",
      "enrolment_total": "",
      "Dropout_male": 124,
      "Dropout_female": 118,
      "dropout_total": 242,
      "PTR": "",
      "PQTR": "",
      "PCR": "",
      "PLR": ""
    },
    {
      "region": "Songwe",
      "council": "Tunduma TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2081,
      "Enrolment_female": 1845,
      "enrolment_total": 3926,
      "Dropout_male": 90,
      "Dropout_female": 47,
      "dropout_total": 137,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 43,
      "PLR": 49
    },
    {
      "region": "Tabora",
      "council": "Igunga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5092,
      "Enrolment_female": 4884,
      "enrolment_total": 9976,
      "Dropout_male": 362,
      "Dropout_female": 273,
      "dropout_total": 635,
      "PTR": 19,
      "PQTR": 20,
      "PCR": 34,
      "PLR": 18
    },
    {
      "region": "Tabora",
      "council": "Kaliua",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3798,
      "Enrolment_female": 2257,
      "enrolment_total": 6055,
      "Dropout_male": 434,
      "Dropout_female": 201,
      "dropout_total": 635,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 41,
      "PLR": 43
    },
    {
      "region": "Tabora",
      "council": "Nzega",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2951,
      "Enrolment_female": 2493,
      "enrolment_total": 5444,
      "Dropout_male": 333,
      "Dropout_female": 288,
      "dropout_total": 621,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 27,
      "PLR": 20
    },
    {
      "region": "Tabora",
      "council": "Nzega TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1288,
      "Enrolment_female": 1696,
      "enrolment_total": 2984,
      "Dropout_male": 40,
      "Dropout_female": 32,
      "dropout_total": 72,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 38,
      "PLR": 25
    },
    {
      "region": "Tabora",
      "council": "Sikonge",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3405,
      "Enrolment_female": 3276,
      "enrolment_total": 6681,
      "Dropout_male": 497,
      "Dropout_female": 486,
      "dropout_total": 983,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 59,
      "PLR": 47
    },
    {
      "region": "Tabora",
      "council": "Tabora MC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 8046,
      "Enrolment_female": 6490,
      "enrolment_total": 14536,
      "Dropout_male": 163,
      "Dropout_female": 128,
      "dropout_total": 291,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 37,
      "PLR": 26
    },
    {
      "region": "Tabora",
      "council": "Tabora/Uyui",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3565,
      "Enrolment_female": 3322,
      "enrolment_total": 6887,
      "Dropout_male": 735,
      "Dropout_female": 649,
      "dropout_total": 1384,
      "PTR": 16,
      "PQTR": 16,
      "PCR": 33,
      "PLR": 22
    },
    {
      "region": "Tabora",
      "council": "Urambo",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2812,
      "Enrolment_female": 2495,
      "enrolment_total": 5307,
      "Dropout_male": 132,
      "Dropout_female": 107,
      "dropout_total": 239,
      "PTR": 22,
      "PQTR": 22,
      "PCR": 41,
      "PLR": 42
    },
    {
      "region": "Tanga",
      "council": "Bumbuli",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3570,
      "Enrolment_female": 4181,
      "enrolment_total": 7751,
      "Dropout_male": 145,
      "Dropout_female": 135,
      "dropout_total": 280,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 44,
      "PLR": 25
    },
    {
      "region": "Tanga",
      "council": "Handeni",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 3433,
      "Enrolment_female": 3947,
      "enrolment_total": 7380,
      "Dropout_male": 267,
      "Dropout_female": 259,
      "dropout_total": 526,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 41,
      "PLR": 32
    },
    {
      "region": "Tanga",
      "council": "Handeni TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1799,
      "Enrolment_female": 2258,
      "enrolment_total": 4057,
      "Dropout_male": 35,
      "Dropout_female": 56,
      "dropout_total": 91,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 47,
      "PLR": 34
    },
    {
      "region": "Tanga",
      "council": "Kilindi",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2753,
      "Enrolment_female": 3521,
      "enrolment_total": 6274,
      "Dropout_male": 230,
      "Dropout_female": 308,
      "dropout_total": 538,
      "PTR": 14,
      "PQTR": 15,
      "PCR": 41,
      "PLR": 28
    },
    {
      "region": "Tanga",
      "council": "Korogwe",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4951,
      "Enrolment_female": 5437,
      "enrolment_total": 10388,
      "Dropout_male": 232,
      "Dropout_female": 179,
      "dropout_total": 411,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 36,
      "PLR": 42
    },
    {
      "region": "Tanga",
      "council": "Korogwe TC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1907,
      "Enrolment_female": 3534,
      "enrolment_total": 5441,
      "Dropout_male": 91,
      "Dropout_female": 94,
      "dropout_total": 185,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 39,
      "PLR": 20
    },
    {
      "region": "Tanga",
      "council": "Lushoto",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 5786,
      "Enrolment_female": 9771,
      "enrolment_total": 15557,
      "Dropout_male": 312,
      "Dropout_female": 410,
      "dropout_total": 722,
      "PTR": 13,
      "PQTR": 13,
      "PCR": 36,
      "PLR": 19
    },
    {
      "region": "Tanga",
      "council": "Mkinga",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 2032,
      "Enrolment_female": 2306,
      "enrolment_total": 4338,
      "Dropout_male": 147,
      "Dropout_female": 133,
      "dropout_total": 280,
      "PTR": 14,
      "PQTR": 14,
      "PCR": 41,
      "PLR": 26
    },
    {
      "region": "Tanga",
      "council": "Muheza",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 4884,
      "Enrolment_female": 5451,
      "enrolment_total": 10335,
      "Dropout_male": 247,
      "Dropout_female": 243,
      "dropout_total": 490,
      "PTR": 20,
      "PQTR": 20,
      "PCR": 39,
      "PLR": 31
    },
    {
      "region": "Tanga",
      "council": "Pangani",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 1206,
      "Enrolment_female": 1320,
      "enrolment_total": 2526,
      "Dropout_male": 42,
      "Dropout_female": 37,
      "dropout_total": 79,
      "PTR": 17,
      "PQTR": 17,
      "PCR": 33,
      "PLR": 20
    },
    {
      "region": "Tanga",
      "council": "Tanga CC",
      "Year": 2016,
      "Category": "Secondary",
      "Enrolment_male": 12013,
      "Enrolment_female": 10212,
      "enrolment_total": 22225,
      "Dropout_male": 118,
      "Dropout_female": 108,
      "dropout_total": 226,
      "PTR": 15,
      "PQTR": 15,
      "PCR": 40,
      "PLR": 27
    }
  ]